### ISSUE TITLE
09-03，新拉取的代码，启动vllm合并到了server.py ,但启动时报错

### ISSUE THREAD

**Issue by xcpuma** [xusenlinzy/api-for-open-llm#101]
### 提交前必须检查以下项目 | The following items must be checked before submission

- [X] 请确保使用的是仓库最新代码（git pull），一些问题已被解决和修复。 | Make sure you are using the latest code from the repository (git pull), some issues have already been addressed and fixed.
- [X] 我已阅读[项目文档](https://github.com/xusenlinzy/api-for-open-llm/blob/master/README.md)和[FAQ章节](https://github.com/xusenlinzy/api-for-open-llm/blob/master/docs/FAQ.md)并且已在Issue中对问题进行了搜索，没有找到相似问题和解决方案 | I have searched the existing issues / discussions

### 问题类型 | Type of problem

启动命令 | Startup command

### 操作系统 | Operating system

None

### 详细描述问题 | Detailed description of the problem

```
# 请在此处粘贴运行代码（如没有可删除该代码块）
# Paste the runtime code here (delete the code block if you don't have it)
```
执行python api/server.py 
报错
api-for-open-llm/api/server.py", line 1, in <module>
    from api.config import config
ModuleNotFoundError: No module named 'api'

### Dependencies

```
# 请在此处粘贴依赖情况
# Please paste the dependencies here
```

### 运行日志或截图 | Runtime logs or screenshots

```
# 请在此处粘贴运行日志
# Please paste the run log here
```

**Comment by xusenlinzy** [comment]
试一下将文件copy到上一级呢

```
cp api/server.py .
python server.py
```

**Comment by xcpuma** [comment]
ok了，谢谢。为什么做这种奇怪的改动呢？
