### ISSUE TITLE
💡 [REQUEST] - <title> 本地模型使用的是 chatglm2-6b-int4，请问QUANTIZE和LOAD_IN_4BIT参数分别要怎么设置

### ISSUE THREAD

**Issue by jinghai** [xusenlinzy/api-for-open-llm#102]
### 摘要 | Summary

本地模型使用的是 chatglm2-6b-int4，请问QUANTIZE和LOAD_IN_4BIT参数分别要怎么设置

### 基本示例 | Basic Example

本地模型使用的是 chatglm2-6b-int4，请问QUANTIZE和LOAD_IN_4BIT参数分别要怎么设置

### 缺陷 | Drawbacks

本地模型使用的是 chatglm2-6b-int4，请问QUANTIZE和LOAD_IN_4BIT参数分别要怎么设置

QUANTIZE = 4
LOAD_IN_4BIT = true

是这样设置吗？

**Comment by xusenlinzy** [comment]
下载的是 chatglm2-6b-int4 权重的话，其他参数不需要配置，跟 chatglm 一样的加载方式，QUANTIZE是在chatglm-6b模型的基础上进行量化

**Comment by jinghai** [comment]
> 下载的是 chatglm2-6b-int4 权重的话，其他参数不需要配置，跟 chatglm2 一样的加载方式，QUANTIZE是在chatglm2-6b模型的基础上进行量化

感谢
