### ISSUE TITLE
使用vLLM起服务得到的模型返回结果跟模型本身的结果区别挺大

### ISSUE THREAD

**Issue by hzs0828** [xusenlinzy/api-for-open-llm#103]
### 提交前必须检查以下项目 | The following items must be checked before submission

- [X] 请确保使用的是仓库最新代码（git pull），一些问题已被解决和修复。 | Make sure you are using the latest code from the repository (git pull), some issues have already been addressed and fixed.
- [X] 我已阅读[项目文档](https://github.com/xusenlinzy/api-for-open-llm/blob/master/README.md)和[FAQ章节](https://github.com/xusenlinzy/api-for-open-llm/blob/master/docs/FAQ.md)并且已在Issue中对问题进行了搜索，没有找到相似问题和解决方案 | I have searched the existing issues / discussions

### 问题类型 | Type of problem

效果问题 | Effectiveness issues

### 操作系统 | Operating system

Linux

### 详细描述问题 | Detailed description of the problem

```
# 请在此处粘贴运行代码（如没有可删除该代码块）
# Paste the runtime code here (delete the code block if you don't have it)
```
模型：Qwen 通义千问
起服务方式1：vLLM 推理加速启动服务
方式2：transformers 直接调用Qwen模型
结果：两种方式返回的结果不一致，而且差别挺大，而且第一种方式每次返回的结果都不一样
请问这是什么原因导致的呢，方式1的推理是做了什么改动吗，或者跟temperature这些参数的设置有关吗

### Dependencies

```
# 请在此处粘贴依赖情况
# Please paste the dependencies here
```
方式二代码：
tokenizer = AutoTokenizer.from_pretrained("Qwen/Qwen-7B-Chat", trust_remote_code=True)

# use bf16
# model = AutoModelForCausalLM.from_pretrained("Qwen/Qwen-7B-Chat", device_map="auto", trust_remote_code=True, bf16=True).eval()
# use fp16
# model = AutoModelForCausalLM.from_pretrained("Qwen/Qwen-7B-Chat", device_map="auto", trust_remote_code=True, fp16=True).eval()
# use cpu only
# model = AutoModelForCausalLM.from_pretrained("Qwen/Qwen-7B-Chat", device_map="cpu", trust_remote_code=True).eval()
# use auto mode, automatically select precision based on the device.
model = AutoModelForCausalLM.from_pretrained(
    "Qwen/Qwen-7B-Chat",
    device_map="auto",
    trust_remote_code=True
).eval()

### 运行日志或截图 | Runtime logs or screenshots

```
# 请在此处粘贴运行日志
# Please paste the run log here
```
返回的结果区别挺大

**Comment by xusenlinzy** [comment]
模型回答结果本身是具有随机性的，如果想要相对固定的回答，可以在调整设置 `temperature`、`top_p` 等参数，值越低，随机性越低。另外vllm项目的生成方式和transformers实现的生成方式不太一样，可以看一看。

**Comment by zhanzushun** [comment]
同样的困惑，vllm回答的质量太差，以至于完全无法使用
