### ISSUE TITLE
codellama 无多轮交互能力

### ISSUE THREAD

**Issue by anyshu** [xusenlinzy/api-for-open-llm#104]
### 提交前必须检查以下项目 | The following items must be checked before submission

- [X] 请确保使用的是仓库最新代码（git pull），一些问题已被解决和修复。 | Make sure you are using the latest code from the repository (git pull), some issues have already been addressed and fixed.
- [X] 我已阅读[项目文档](https://github.com/xusenlinzy/api-for-open-llm/blob/master/README.md)和[FAQ章节](https://github.com/xusenlinzy/api-for-open-llm/blob/master/docs/FAQ.md)并且已在Issue中对问题进行了搜索，没有找到相似问题和解决方案 | I have searched the existing issues / discussions

### 问题类型 | Type of problem

模型推理和部署 | Model inference and deployment

### 操作系统 | Operating system

Linux

### 详细描述问题 | Detailed description of the problem

```
# 请在此处粘贴运行代码（如没有可删除该代码块）
# Paste the runtime code here (delete the code block if you don't have it)
```
多轮聊天中，无法记住之前的聊天内容。

在conversation.py中去除“< s > < / s >”上下文就能正常支持，原因不知（主要是不懂😂），查看codellama的解析代码发现不需要。但huaggingface上的代码提示需要< s > < / s >的格式，很奇怪。 
<img width="411" alt="截屏2023-09-06 10 45 21" src="https://github.com/xusenlinzy/api-for-open-llm/assets/13213426/0ef8a04d-cd1f-4f1c-8d0d-b81809b194c0">

### Dependencies

```
# 请在此处粘贴依赖情况
# Please paste the dependencies here
```

### 运行日志或截图 | Runtime logs or screenshots

```
# 请在此处粘贴运行日志
# Please paste the run log here
```

**Comment by xusenlinzy** [comment]
```python
self.tokenizer.encode(
    f"{B_INST} {(prompt['content']).strip()} {E_INST} {(answer['content']).strip()} ",
    bos=True,
    eos=True,
)
```

codellama官方代码里是添加了 “< s > < / s >” 的
