### ISSUE TITLE
如何使用基于starcoder微调过的模型

### ISSUE THREAD

**Issue by steph730** [xusenlinzy/api-for-open-llm#108]
### 摘要 | Summary

请问如何使用其他基于starcoder微调的模型（codes），用法跟sqlcoder一样嘛，还是暂时不支持

### 基本示例 | Basic Example

无

### 缺陷 | Drawbacks

是否支持呢

**Comment by xusenlinzy** [comment]
与starcoder模型的使用方式是一致的

**Comment by steph730** [comment]
> 与starcoder模型的使用方式是一致的，如果是对话模型的话，需要注意对话的prompt模板
我看文档里没有startcoder的启动方式呀，只有starchat和sqlcoder，是使用sqlcoder的启动方式嘛

**Comment by xusenlinzy** [comment]
对的
