### ISSUE TITLE
使用vllm加载qwen-7b模型的时候显存占到40G左右，但关掉vllm时占用17G显存，我该如何在使用vllm的时候降低显存呢？

### ISSUE THREAD

**Issue by cgq0816** [xusenlinzy/api-for-open-llm#110]
### 提交前必须检查以下项目 | The following items must be checked before submission

- [X] 请确保使用的是仓库最新代码（git pull），一些问题已被解决和修复。 | Make sure you are using the latest code from the repository (git pull), some issues have already been addressed and fixed.
- [X] 我已阅读[项目文档](https://github.com/xusenlinzy/api-for-open-llm/blob/master/README.md)和[FAQ章节](https://github.com/xusenlinzy/api-for-open-llm/blob/master/docs/FAQ.md)并且已在Issue中对问题进行了搜索，没有找到相似问题和解决方案 | I have searched the existing issues / discussions

### 问题类型 | Type of problem

模型推理和部署 | Model inference and deployment

### 操作系统 | Operating system

Linux

### 详细描述问题 | Detailed description of the problem

使用vllm加载qwen-7b模型的时候显存占到40G左右，但关掉vllm时占用17G显存，我该如何在使用vllm的时候降低显存呢？
未使用vllm的时候以及显存情况
![image](https://github.com/xusenlinzy/api-for-open-llm/assets/42534237/e03eb887-ec43-4410-823f-97fadba00bb5)
![image](https://github.com/xusenlinzy/api-for-open-llm/assets/42534237/060c61a8-9301-466c-9a28-b6290a5dfdfa)
使用vllm的时候以及显存情况
![image](https://github.com/xusenlinzy/api-for-open-llm/assets/42534237/f412f729-c6c2-43f6-9935-aa50e7a46df0)
![image](https://github.com/xusenlinzy/api-for-open-llm/assets/42534237/51ed573a-9ca3-450e-bac0-6135e6158a77)

**Comment by xusenlinzy** [comment]
将 `GPU_MEMORY_UTILIZATION` 参数调低， `GPU_MEMORY_UTILIZATION` 默认是0.9，设置成0.5试试，因为vllm会缓存一些变量占用很多显存

**Comment by cgq0816** [comment]
> 将 `GPU_MEMORY_UTILIZATION` 参数调低， `GPU_MEMORY_UTILIZATION` 默认是0.9，设置成0.5试试，因为vllm会缓存一些变量占用很多显存

改小了占用显存也少了，但是这样会影响推理的精度吗？

**Comment by xusenlinzy** [comment]
应该不会，占用更多显存主要是为了处理更多请求，加快推理速度

**Comment by cgq0816** [comment]
> 应该不会，占用更多显存主要是为了处理更多请求，加快推理速度
好的，谢谢，那请问一下这个问题我该怎么解决呢？使用vllm加载的时候提示slow tokenizer，TOKENIZE_MODE已经设置auto了
WARNING 09-07 07:56:14 tokenizer.py:63] Using a slow tokenizer. This might cause a significant slowdown. Consider using a fast tokenizer instead.

**Comment by xusenlinzy** [comment]
qwen的tokenizer只能用slow模式，没有use_fast特性

**Comment by cgq0816** [comment]
> qwen的tokenizer只能用slow模式，没有use_fast特性

好的，谢谢

**Comment by Charimanhua** [comment]
请问您知道如何指定vllm使用哪张卡吗？我有两张15g的卡，每次都是第一张满了，第二张只用了一半不到。我想让vllm加载到第二章卡上，其余的都用第一张卡，但不知道如何做。。。
