### ISSUE TITLE
baichuan2-13b-chat报错

### ISSUE THREAD

**Issue by zhengxiang5965** [xusenlinzy/api-for-open-llm#112]
### 提交前必须检查以下项目 | The following items must be checked before submission

- [X] 请确保使用的是仓库最新代码（git pull），一些问题已被解决和修复。 | Make sure you are using the latest code from the repository (git pull), some issues have already been addressed and fixed.
- [X] 我已阅读[项目文档](https://github.com/xusenlinzy/api-for-open-llm/blob/master/README.md)和[FAQ章节](https://github.com/xusenlinzy/api-for-open-llm/blob/master/docs/FAQ.md)并且已在Issue中对问题进行了搜索，没有找到相似问题和解决方案 | I have searched the existing issues / discussions

### 问题类型 | Type of problem

安装环境 | Installation environment

### 操作系统 | Operating system

Linux

### 详细描述问题 | Detailed description of the problem

baichuan2升级torch到2.0以后，报错

RuntimeError: Failed to import transformers.models.bert.modeling_bert because of the following error (look up to see its traceback):
Failed to import transformers.generation.utils because of the following error (look up to see its traceback):
/usr/local/lib/python3.8/dist-packages/transformer_engine_extensions.cpython-38-x86_64-linux-gnu.so: undefined symbol: _ZN3c106detail23torchInternalAssertFailEPKcS2_jS2_RKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE

### Dependencies

peft                          0.5.0
pytorch-quantization          2.1.2
sentence-transformers         2.2.2
torch                         2.0.1
torch-tensorrt                1.3.0a0
torchtext                     0.13.0a0+fae8e8c
torchvision                   0.15.0a0
transformers                  4.33.1
transformers-stream-generator 0.0.4

### 运行日志或截图 | Runtime logs or screenshots

```
# 请在此处粘贴运行日志
# Please paste the run log here
```

**Comment by xusenlinzy** [comment]
试一下 `pip uninstall transformer-engine -y`

**Comment by zhengxiang5965** [comment]
> pip uninstall transformer-engine -y
解决了
成功运行
