### ISSUE TITLE
请问如何支持新的模型 chatglm2-6b-32k，我试了一下 没有任何响应

### ISSUE THREAD

**Issue by lonely1215225** [xusenlinzy/api-for-open-llm#116]
### 摘要 | Summary

...

### 基本示例 | Basic Example

...

### 缺陷 | Drawbacks

...

**Comment by xusenlinzy** [comment]
与chatglm2-6b的配置是一样的

```
MODEL_NAME=chatglm2
MODEL_PATH=THUDM/chatglm2-6b-32k
```

**Comment by lonely1215225** [comment]
> 

真的没有回复内容，请问你有试过吗？

**Comment by xusenlinzy** [comment]
![image](https://github.com/xusenlinzy/api-for-open-llm/assets/111472355/6c2cfb5f-455e-4f2d-ab46-ac0ad661d2a0)
