### ISSUE TITLE
💡 [REQUEST] - 如何支持YeungNLP/firefly-qwen-7b

### ISSUE THREAD

**Issue by tkokto** [xusenlinzy/api-for-open-llm#122]
### 摘要 | Summary

想用微调后的千问，请问大佬如何配置，这是我目前的配置
![image](https://github.com/xusenlinzy/api-for-open-llm/assets/43598273/7c775309-8008-4a1b-b8a8-53083b93218a)
启动时报错了：
![image](https://github.com/xusenlinzy/api-for-open-llm/assets/43598273/29bd7476-c9b5-4a3f-8140-5ece464b9d9e)

### 基本示例 | Basic Example

1

### 缺陷 | Drawbacks

1

**Comment by xusenlinzy** [comment]
```
PROMPT_NAME=firefly
DEVICE_MAP=auto
```

MODEL_PATH你换成绝对路径试试

**Comment by xusenlinzy** [comment]
刚刚更新了，拉取新的代码试试

```
PROMPT_NAME=firefly-qwen
DEVICE_MAP=auto
```

MODEL_PATH换成绝对路径试试，报错信息好像没找到模型文件

**Comment by tkokto** [comment]
感谢回复！
我刚更新了最新代码
![image](https://github.com/xusenlinzy/api-for-open-llm/assets/43598273/913ae913-72a4-4253-ab4c-806c7751df8b)
我把model_path改为了YeungNLP/firefly-qwen-7b，还是报错了，
![image](https://github.com/xusenlinzy/api-for-open-llm/assets/43598273/e4da70e8-61ca-4774-88f6-6bb11e32e18f)
是不是我的路径写的有问题？

**Comment by xusenlinzy** [comment]
你的模型文件下载到本地了吗

**Comment by tkokto** [comment]
下载到本地了，还是报错，
![image](https://github.com/xusenlinzy/api-for-open-llm/assets/43598273/a4b88c82-1c60-4065-afc8-216d11702fef)
我把model中的path也改了
![image](https://github.com/xusenlinzy/api-for-open-llm/assets/43598273/a4d0e86c-c220-4cca-aa3e-8ae030d20617)
但是报错日志中一直显示去下载

**Comment by tkokto** [comment]
这是下载后的路径：
![image](https://github.com/xusenlinzy/api-for-open-llm/assets/43598273/b066f041-fd07-401d-a265-cfb086b80a24)
好像一直去hugging face去下载qwen7b了，而不是本地的firefly qwen
![image](https://github.com/xusenlinzy/api-for-open-llm/assets/43598273/9315ef36-4e54-47a5-81bd-9be3765eabf8)

**Comment by xusenlinzy** [comment]
最近Qwen官方模型在huggingface删除了，你的模型文件还缺少一些，你看看能不能把少的文件从下载的Qwen-7b-chat模型复制过去
