### ISSUE TITLE
💡 [QUESTION] - <请问支持Chinese- alpaca-2吗>

### ISSUE THREAD

**Issue by Alberoyang** [xusenlinzy/api-for-open-llm#123]
### 摘要 | Summary

请问支持Chinese- alpaca2吗

### 基本示例 | Basic Example

使用llama2进行部署吗，我看代码里每个模型都会寻到一个部署路径。

### 缺陷 | Drawbacks

无

**Comment by xusenlinzy** [comment]
刚刚更新了代码，你可以试试修改下面的配置

```
MODEL_NAME=llama2
PROMPT_NAME=chinese-llama-alpaca2
```
