### ISSUE TITLE
采用Vllm方式启动baichuan2-7b模型，回复乱码

### ISSUE THREAD

**Issue by hzs0828** [xusenlinzy/api-for-open-llm#127]
### 提交前必须检查以下项目 | The following items must be checked before submission

- [X] 请确保使用的是仓库最新代码（git pull），一些问题已被解决和修复。 | Make sure you are using the latest code from the repository (git pull), some issues have already been addressed and fixed.
- [X] 我已阅读[项目文档](https://github.com/xusenlinzy/api-for-open-llm/blob/master/README.md)和[FAQ章节](https://github.com/xusenlinzy/api-for-open-llm/blob/master/docs/FAQ.md)并且已在Issue中对问题进行了搜索，没有找到相似问题和解决方案 | I have searched the existing issues / discussions

### 问题类型 | Type of problem

模型推理和部署 | Model inference and deployment

### 操作系统 | Operating system

Linux

### 详细描述问题 | Detailed description of the problem

```
# 请在此处粘贴运行代码（如没有可删除该代码块）
# Paste the runtime code here (delete the code block if you don't have it)
```
模型：baichuan2-7b
vllm方式启动回答是乱码，如下图
![image](https://github.com/xusenlinzy/api-for-open-llm/assets/52945343/24765814-4dad-4747-9277-96405c21c095)
vllm设置为false启动，回答效果如下图：
![image](https://github.com/xusenlinzy/api-for-open-llm/assets/52945343/3da6811f-6771-4436-bd68-0fe8a93948e0)

请问这个是什么原因导致的呢

### Dependencies

```
# 请在此处粘贴依赖情况
# Please paste the dependencies here
```

### 运行日志或截图 | Runtime logs or screenshots

```
# 请在此处粘贴运行日志
# Please paste the run log here
```

**Comment by hzs0828** [comment]
启动的是server.py脚本

**Comment by xusenlinzy** [comment]
https://github.com/vllm-project/vllm/issues/1085

应该是vllm的一个bug
