### ISSUE TITLE
请求的时候传了max_token==4000但是每次聊天返回只有500左右

### ISSUE THREAD

**Issue by lynnroyal** [xusenlinzy/api-for-open-llm#128]
### 提交前必须检查以下项目 | The following items must be checked before submission

- [X] 请确保使用的是仓库最新代码（git pull），一些问题已被解决和修复。 | Make sure you are using the latest code from the repository (git pull), some issues have already been addressed and fixed.
- [X] 我已阅读[项目文档](https://github.com/xusenlinzy/api-for-open-llm/blob/master/README.md)和[FAQ章节](https://github.com/xusenlinzy/api-for-open-llm/blob/master/docs/FAQ.md)并且已在Issue中对问题进行了搜索，没有找到相似问题和解决方案 | I have searched the existing issues / discussions

### 问题类型 | Type of problem

效果问题 | Effectiveness issues

### 操作系统 | Operating system

Linux

### 详细描述问题 | Detailed description of the problem

```
# 请在此处粘贴运行代码（如没有可删除该代码块）
# Paste the runtime code here (delete the code block if you don't have it)
```

### Dependencies

```
# 请在此处粘贴依赖情况
# Please paste the dependencies here
```

### 运行日志或截图 | Runtime logs or screenshots

```
# 请在此处粘贴运行日志
# Please paste the run log here
```

**Comment by xusenlinzy** [comment]
模型生成的长度受到多个参数的影响，你可以调整一下参数，比如温度调高一些，或者在问问题的时候，提示模型生成的内容更加详细具体一些

**Comment by adamwoo** [comment]
我也遇到了相同的问题，相同的模型，使用streamlit 设置相同的temperature top_p max_tokens的情况下，streamlit 返回正常，接口返回只有500多

**Comment by Tendo33** [comment]
因为接口默认就是512。更改一下参数
