### ISSUE TITLE
问一下

### ISSUE THREAD

**Issue by jinghai** [xusenlinzy/api-for-open-llm#13]
老哥，问一下：
git+https://github.com/huggingface/transformers.git
git+https://github.com/huggingface/peft.git
git+https://github.com/huggingface/accelerate.git
这三项为什么非要源码安装呢？

**Comment by jinghai** [comment]
比如第一项，如何换成：transformers，会怎么样

**Comment by jinghai** [comment]
![image](https://github.com/xusenlinzy/api-for-open-llm/assets/5433705/8789ea54-28d0-460c-9e30-a9ad73367d9e)
好难安装啊

**Comment by jinghai** [comment]
比如第一项，如何换成：transformers，会怎么样

**Comment by xusenlinzy** [comment]
> 比如第一项，如何换成：transformers，会怎么样

![image](https://github.com/xusenlinzy/api-for-open-llm/assets/111472355/2139f33a-6caa-4186-8d9a-14fa4ffc9bae)

主要是支持load_in_4bit，如果没有这个需求的话，直接安装transformers,peft,accelerate就行

**Comment by jinghai** [comment]
哦，谢谢
