### ISSUE TITLE
你好，支持书生20B吗

### ISSUE THREAD

**Issue by lucheng07082221** [xusenlinzy/api-for-open-llm#133]
### 实现PR | Implementation PR

你好，支持书生20B吗

### 摘要 | Summary

你好，支持书生20B吗

### 基本示例 | Basic Example

你好，支持书生20B吗

### 缺陷 | Drawbacks

你好，支持书生20B吗

**Comment by xusenlinzy** [comment]
应该是可以的，启动方式参考 https://github.com/xusenlinzy/api-for-open-llm/blob/master/docs/SCRIPT.md#internlm
