### ISSUE TITLE
💡 [REQUEST] - 需要支持Qwen-14B-chat

### ISSUE THREAD

**Issue by wuzechuan** [xusenlinzy/api-for-open-llm#134]
### 起始日期 | Start Date

09/25/2023

### 摘要 | Summary

qwen14B模型发布了，可以支持下这个模型吗

### 基本示例 | Basic Example

无

### 缺陷 | Drawbacks

无

### 未解决问题 | Unresolved questions

无

**Comment by xusenlinzy** [comment]
应该是可以的，和qwen-7b使用方式一样，模型的关键代码没什么变化

**Comment by wuzechuan** [comment]
vllm 启动不了，非vllm的可以

**Comment by xusenlinzy** [comment]
可以试试 https://github.com/vllm-project/vllm/pull/1173
