### ISSUE TITLE
💡 [REQUEST] - <title>请问，可以只跑embedding模型，而不启动LLM吗？

### ISSUE THREAD

**Issue by jinghai** [xusenlinzy/api-for-open-llm#138]
### 摘要 | Summary

请问，可以只跑embedding模型，而不启动LLM吗？

### 基本示例 | Basic Example

请问，可以只跑embedding模型，而不启动LLM吗？

### 缺陷 | Drawbacks

请问，可以只跑embedding模型，而不启动LLM吗？

**Comment by kv-chiu** [comment]
yes, i had tried it

**Comment by xusenlinzy** [comment]
拉取最新代码，环境变量增加 ONLY_EMBEDDING=true
