### ISSUE TITLE
💡 [REQUEST] - <title> wizardLM系列求更新！

### ISSUE THREAD

**Issue by 2018211801** [xusenlinzy/api-for-open-llm#142]
### 摘要 | Summary

你好呀，感谢你的工作！ wizardmath  wizardcode效果都很好，不知道你们是否有添加的打算~

### 基本示例 | Basic Example

1

### 缺陷 | Drawbacks

或者出个教程告诉我们自己怎么添加呀

**Comment by xusenlinzy** [comment]
你可以试试 https://github.com/xusenlinzy/api-for-open-llm/blob/master/docs/SCRIPT.md#wizard-coder

**Comment by 2018211801** [comment]
谢谢你及时的回复！！ 就是vllm/script.md 和 script.md 里面给出的可用模型不一样，这两个是除了环境，其他通用的吗？vllm下的没写wizard也可以用吗？我好像通过vllm方式正在下载wizard，但是还有半天才下完，不知道这样可以用吗？   再次感谢~

**Comment by 2018211801** [comment]
好像不行，已经报错了
