### ISSUE TITLE
💡 [REQUEST] - <title> 请问Qwen-14B-Chat-Int4模型可以跑在vllm的镜像上面吗？

### ISSUE THREAD

**Issue by jinghai** [xusenlinzy/api-for-open-llm#145]
### 摘要 | Summary

请问Qwen-14B-Chat-Int4模型可以跑在vllm的镜像上面吗？

### 基本示例 | Basic Example

请问Qwen-14B-Chat-Int4模型可以跑在vllm的镜像上面吗？

### 缺陷 | Drawbacks

请问Qwen-14B-Chat-Int4模型可以跑在vllm的镜像上面吗？

**Comment by xusenlinzy** [comment]
vllm还不支持gptq量化的模型
