### ISSUE TITLE
Qwen-14B-Chat-Int4 响应速度比未量化的版本慢很多

### ISSUE THREAD

**Issue by warrenwyf** [xusenlinzy/api-for-open-llm#149]
### 提交前必须检查以下项目 | The following items must be checked before submission

- [X] 请确保使用的是仓库最新代码（git pull），一些问题已被解决和修复。 | Make sure you are using the latest code from the repository (git pull), some issues have already been addressed and fixed.
- [X] 我已阅读[项目文档](https://github.com/xusenlinzy/api-for-open-llm/blob/master/README.md)和[FAQ章节](https://github.com/xusenlinzy/api-for-open-llm/blob/master/docs/FAQ.md)并且已在Issue中对问题进行了搜索，没有找到相似问题和解决方案 | I have searched the existing issues / discussions

### 问题类型 | Type of problem

效果问题 | Effectiveness issues

### 操作系统 | Operating system

Linux

### 详细描述问题 | Detailed description of the problem

千问的模型分别测试了 Qwen-7B-Chat（vllm）和 Qwen-14B-Chat-Int4（gptq），按文档编译不同的镜像并使用 docker compose 运行，然后用 curl 调用测试效果。(编译 gptq 镜像按照原始文档运行千问失败，注释掉 pip install torch 不更新 torch 后可以运行)

从体验上感觉 Qwen-7B-Chat 的响应是正常的，和其它模型类似，但 Qwen-14B-Chat-Int4 的响应速度会慢很多。

我注意到日志中有这样的警告，不知道是否有关系：

```
api-for-open-llm-apiserver-1  | Try importing flash-attention for faster inference...
api-for-open-llm-apiserver-1  | Warning: import flash_attn rotary fail, please install FlashAttention rotary to get higher efficiency https://github.com/Dao-AILab/flash-attention/tree/main/csrc/rotary
api-for-open-llm-apiserver-1  | Warning: import flash_attn rms_norm fail, please install FlashAttention layer_norm to get higher efficiency https://github.com/Dao-AILab/flash-attention/tree/main/csrc/layer_norm
api-for-open-llm-apiserver-1  | Warning: import flash_attn fail, please install FlashAttention to get higher efficiency https://github.com/Dao-AILab/flash-attention
api-for-open-llm-apiserver-1  | CUDA extension not installed.
```

**Comment by Gcsimple** [comment]
请问下gptq这个量化模型问题解决了吗?

**Comment by jayden222** [comment]
flash attention 和 auto-gptq都要从源码安装
```bash
git clone https://github.com/PanQiWei/AutoGPTQ & cd AutoGPTQ & pip install .
```

**Comment by EchoShoot** [comment]
遇到了同样的问题， 7B速度飞的起， 14B 与 14B-Int4 都慢的惊人
