### ISSUE TITLE
💡 [REQUEST] - 支持chatglm3-6B 

### ISSUE THREAD

**Issue by wuzechuan** [xusenlinzy/api-for-open-llm#151]
### 摘要 | Summary

希望能支持chatglm3-6b 模型的部署

### 基本示例 | Basic Example

无

### 缺陷 | Drawbacks

无

**Comment by LuneZ99** [comment]
模型项目地址 https://github.com/THUDM/ChatGLM3

**Comment by Lvjinhong** [comment]
可以直接换成glm3，可以正常运行
![image](https://github.com/xusenlinzy/api-for-open-llm/assets/96970081/4e93fbe7-2564-4f2c-a100-cb69a04c4b97)


但是streamlit的接口好像是有些问题：
当我使用 OPENAI_API_BASE=http://127.0.0.1:8000/v1 streamlit run streamlit_app.py 运行时，会出现问题：

![image](https://github.com/xusenlinzy/api-for-open-llm/assets/96970081/abd11e34-997e-4ad8-821b-8817a7ae8445)

是不是streamlit 提供的请求格式不正确？

**Comment by xusenlinzy** [comment]
最新代码已添加支持
