### ISSUE TITLE
用Qwen14B 的流式输出输出停不下来

### ISSUE THREAD

**Issue by lucheng07082221** [xusenlinzy/api-for-open-llm#153]
### 提交前必须检查以下项目 | The following items must be checked before submission

- [X] 请确保使用的是仓库最新代码（git pull），一些问题已被解决和修复。 | Make sure you are using the latest code from the repository (git pull), some issues have already been addressed and fixed.
- [X] 我已阅读[项目文档](https://github.com/xusenlinzy/api-for-open-llm/blob/master/README.md)和[FAQ章节](https://github.com/xusenlinzy/api-for-open-llm/blob/master/docs/FAQ.md)并且已在Issue中对问题进行了搜索，没有找到相似问题和解决方案 | I have searched the existing issues / discussions

### 问题类型 | Type of problem

效果问题 | Effectiveness issues

### 操作系统 | Operating system

None

### 详细描述问题 | Detailed description of the problem

```
# 请在此处粘贴运行代码（如没有可删除该代码块）
# Paste the runtime code here (delete the code block if you don't have it)
```

### Dependencies

```
# 请在此处粘贴依赖情况
# Please paste the dependencies here
```

### 运行日志或截图 | Runtime logs or screenshots

用Qwen14B 的流式输出输出停不下来
![Uploading 2023-10-30 15-04-20屏幕截图.png…]()

**Comment by lucheng07082221** [comment]
![2023-10-30 15-04-20屏幕截图](https://github.com/xusenlinzy/api-for-open-llm/assets/3146209/51ac291b-b039-4410-a4f4-62e6f8a2466d)

**Comment by lucheng07082221** [comment]
@xusenlinzy

**Comment by xusenlinzy** [comment]
拉取新的代码试试
