### ISSUE TITLE
💡 [REQUEST] - 如何多卡运行？

### ISSUE THREAD

**Issue by deku0818** [xusenlinzy/api-for-open-llm#156]
### 摘要 | Summary

请问怎么多卡运行，当单卡无法满足模型运行，如何多卡运行呢

### 基本示例 | Basic Example

请问怎么多卡运行，当单卡无法满足模型运行，如何多卡运行呢

### 缺陷 | Drawbacks

请问怎么多卡运行，当单卡无法满足模型运行，如何多卡运行呢

**Comment by deku0818** [comment]
用vllm  设置了 TENSOR_PARALLEL_SIZE=2 但还是用的一张卡

**Comment by xusenlinzy** [comment]
![image](https://github.com/xusenlinzy/api-for-open-llm/assets/111472355/0e12001c-f429-418e-b55d-ed43c4a41d20)
使用docker启动的话，这个地方也要修改，比如两张卡就写  `['0', '1']`
