### ISSUE TITLE
💡 [REQUEST] - <title>如何解决跨域问题？

### ISSUE THREAD

**Issue by coderwpf** [xusenlinzy/api-for-open-llm#158]
### 摘要 | Summary

如何解决跨域问题？

### 基本示例 | Basic Example

如何解决跨域问题？

### 缺陷 | Drawbacks

如何解决跨域问题？

**Comment by xusenlinzy** [comment]
在下面的代码中设置跨域参数就行 https://github.com/xusenlinzy/api-for-open-llm/blob/master/api/models.py#L11C4-L11C21

**Comment by coderwpf** [comment]
> 在下面的代码中设置跨域参数就行 https://github.com/xusenlinzy/api-for-open-llm/blob/master/api/models.py#L11C4-L11C21

感谢大佬，问题终于解决了。十分感谢
