### ISSUE TITLE
function call 调用功能来使用工具，当stream为True时，无法调用工具，False时可以调用

### ISSUE THREAD

**Issue by xiaoranchenwai** [xusenlinzy/api-for-open-llm#161]
### 提交前必须检查以下项目 | The following items must be checked before submission

- [X] 请确保使用的是仓库最新代码（git pull），一些问题已被解决和修复。 | Make sure you are using the latest code from the repository (git pull), some issues have already been addressed and fixed.
- [X] 我已阅读[项目文档](https://github.com/xusenlinzy/api-for-open-llm/blob/master/README.md)和[FAQ章节](https://github.com/xusenlinzy/api-for-open-llm/blob/master/docs/FAQ.md)并且已在Issue中对问题进行了搜索，没有找到相似问题和解决方案 | I have searched the existing issues / discussions

### 问题类型 | Type of problem

效果问题 | Effectiveness issues

### 操作系统 | Operating system

Linux

### 详细描述问题 | Detailed description of the problem

```
# 请在此处粘贴运行代码（如没有可删除该代码块）
# Paste the runtime code here (delete the code block if you don't have it)
```
当stream为True时，如下判断无法进入
chunk.choices[0].finish_reason == "function_call":

使用模型为Qwen14B

### Dependencies

```
# 请在此处粘贴依赖情况
# Please paste the dependencies here
```

### 运行日志或截图 | Runtime logs or screenshots

```
# 请在此处粘贴运行日志
# Please paste the run log here
```

**Comment by xusenlinzy** [comment]
能看一下你的调用代码吗

**Comment by xiaoranchenwai** [comment]
确实是用vllm启动的，试了下不用vllm，流式也可以调用工具，感谢！
