### ISSUE TITLE
在dify里使用api-for-open-llm暴露的embeddings接口，部分文档清洗报错

### ISSUE THREAD

**Issue by 760485464** [xusenlinzy/api-for-open-llm#165]
### 提交前必须检查以下项目 | The following items must be checked before submission

- [X] 请确保使用的是仓库最新代码（git pull），一些问题已被解决和修复。 | Make sure you are using the latest code from the repository (git pull), some issues have already been addressed and fixed.
- [X] 我已阅读[项目文档](https://github.com/xusenlinzy/api-for-open-llm/blob/master/README.md)和[FAQ章节](https://github.com/xusenlinzy/api-for-open-llm/blob/master/docs/FAQ.md)并且已在Issue中对问题进行了搜索，没有找到相似问题和解决方案 | I have searched the existing issues / discussions

### 问题类型 | Type of problem

None

### 操作系统 | Operating system

Linux

### 详细描述问题 | Detailed description of the problem

在dify里使用api-for-open-llm暴露的embeddings接口，部分文档清洗报错，同一文档换成openai接口无问题

### 运行日志或截图 | Runtime logs or screenshots

![image](https://github.com/xusenlinzy/api-for-open-llm/assets/48109376/f3848358-f912-4747-831a-ca021215b09f)

**Comment by xusenlinzy** [comment]
您好，可以试试拉取最新的代码看看有没有问题
