### ISSUE TITLE
请问有没有稳定版，目前我只需要chatglm2-6b和m3e-base，我拉取的master有些bug

### ISSUE THREAD

**Issue by rzechen** [xusenlinzy/api-for-open-llm#167]
### 提交前必须检查以下项目 | The following items must be checked before submission

- [X] 请确保使用的是仓库最新代码（git pull），一些问题已被解决和修复。 | Make sure you are using the latest code from the repository (git pull), some issues have already been addressed and fixed.
- [X] 我已阅读[项目文档](https://github.com/xusenlinzy/api-for-open-llm/blob/master/README.md)和[FAQ章节](https://github.com/xusenlinzy/api-for-open-llm/blob/master/docs/FAQ.md)并且已在Issue中对问题进行了搜索，没有找到相似问题和解决方案 | I have searched the existing issues / discussions

### 问题类型 | Type of problem

其他问题 | Other issues

### 操作系统 | Operating system

Linux

### 详细描述问题 | Detailed description of the problem

```
# 请在此处粘贴运行代码（如没有可删除该代码块）
# Paste the runtime code here (delete the code block if you don't have it)
```

### Dependencies

```
# 请在此处粘贴依赖情况
# Please paste the dependencies here
```

### 运行日志或截图 | Runtime logs or screenshots

```
# 请在此处粘贴运行日志
# Please paste the run log here
```

**Comment by xusenlinzy** [comment]
您好，刚刚修复了更新后的bug，您可以试试拉取最新的代码看看有没有问题

**Comment by rzechen** [comment]
> 您好，刚刚修复了更新后的bug，您可以试试拉取最新的代码看看有没有问题
这个是我在调用m3e-base的时候报的错误
<img width="1212" alt="image" src="https://github.com/xusenlinzy/api-for-open-llm/assets/24729413/8c173dc4-896a-4ff4-a23c-6288c4fc782d">

下方是调用代码，还有就是我想问下，env中并没有指定类似大模型一下样的MODEL_NAME（只有一个EMBEDDING_NAME，我指定的是m3e-base的绝对路径），所以参数model_name不知道作用在哪里
<img width="539" alt="image" src="https://github.com/xusenlinzy/api-for-open-llm/assets/24729413/38d6e45d-a62f-4269-a85a-5c001cfee7bd">

**Comment by xusenlinzy** [comment]
安装openai>=1.2.3

**Comment by rzechen** [comment]
> 安装openai>=1.2.3

感谢，解决了
