### ISSUE TITLE
更新到了最新版本，流式输出还是一直停不下来

### ISSUE THREAD

**Issue by lucheng07082221** [xusenlinzy/api-for-open-llm#169]
### 提交前必须检查以下项目 | The following items must be checked before submission

- [X] 请确保使用的是仓库最新代码（git pull），一些问题已被解决和修复。 | Make sure you are using the latest code from the repository (git pull), some issues have already been addressed and fixed.
- [X] 我已阅读[项目文档](https://github.com/xusenlinzy/api-for-open-llm/blob/master/README.md)和[FAQ章节](https://github.com/xusenlinzy/api-for-open-llm/blob/master/docs/FAQ.md)并且已在Issue中对问题进行了搜索，没有找到相似问题和解决方案 | I have searched the existing issues / discussions

### 问题类型 | Type of problem

None

### 操作系统 | Operating system

None

### 详细描述问题 | Detailed description of the problem

```
# 请在此处粘贴运行代码（如没有可删除该代码块）
# Paste the runtime code here (delete the code block if you don't have it)
```

### Dependencies

```
# 请在此处粘贴依赖情况
# Please paste the dependencies here
```

### 运行日志或截图 | Runtime logs or screenshots

你好

你好！很高兴见到你。你可以问我任何问题，我会尽力回答。
周王将宗周附近的土地分封给自己的儿子、亲戚、功臣、前代贵族后裔，让他们在封地里建立国家。材料反映的是（ ）
A. 分封制
B. 郡县制
C. 行省制
D. 科举制
答案：A
解析：依据所学，西周初年，周王为巩固统治，大规模分封诸侯。因此材料反映的是分封制。
故选：A。
本题以“周王将宗周附近的土地分封给自己的儿子、亲戚、功臣、前代贵族后裔，让他们在封地里建立国家”为切入点，考查分封制。
本题以分封制为背景，考查学生识记历史知识能力。
关键点：西周的分封制.2018年4月10日，习近平主席在博鳌亚洲论坛年会开幕式上的主旨演讲中强调：“各国要顺应时代发展潮流，坚持开放共赢，勇于变革创新，向着构建人类命运共同体的目标不断迈进。”这启示我们（ ）
A. 要把提升发展质量放在首位
B. 高质量的发展是当代世界发展的主题
C. 要积极参与全球规则制定，把握国际竞争主动权
D. 要努力推动世界各国经济政治发展均衡化
答案：C
解析：题干描述说明中国在国际社会中发挥着重要的建设性作用，启示我们要积极参与全球规则制定，把握国际竞争主动权，C符合题意；A与题

**Comment by xusenlinzy** [comment]
可以看一下的环境变量配置吗

**Comment by lucheng07082221** [comment]
USE_STREAMER_V2=false,流式输出正常
USE_STREAMER_V2=true，流式输出反而不正常了

**Comment by xusenlinzy** [comment]
请问你用的哪个模型，可能是停止词没有配置好
