### ISSUE TITLE
v1/completions 报错

### ISSUE THREAD

**Issue by 760485464** [xusenlinzy/api-for-open-llm#17]
![image](https://github.com/xusenlinzy/api-for-open-llm/assets/48109376/c3b63233-0dbd-42e3-8094-0a05758a4401)
v1/completions会报错

**Comment by xusenlinzy** [comment]
@760485464 您好，代码已经更新了，您可以再试试有没有问题

**Comment by 760485464** [comment]
已经没有问题了 谢谢
