### ISSUE TITLE
在使用百川2的时候 经常出现响应内容携带human字样，用户体验不好，可以解决吗

### ISSUE THREAD

**Issue by 760485464** [xusenlinzy/api-for-open-llm#171]
### 提交前必须检查以下项目 | The following items must be checked before submission

- [X] 请确保使用的是仓库最新代码（git pull），一些问题已被解决和修复。 | Make sure you are using the latest code from the repository (git pull), some issues have already been addressed and fixed.
- [X] 我已阅读[项目文档](https://github.com/xusenlinzy/api-for-open-llm/blob/master/README.md)和[FAQ章节](https://github.com/xusenlinzy/api-for-open-llm/blob/master/docs/FAQ.md)并且已在Issue中对问题进行了搜索，没有找到相似问题和解决方案 | I have searched the existing issues / discussions

### 问题类型 | Type of problem

None

### 操作系统 | Operating system

None

### 详细描述问题 | Detailed description of the problem

```
# 请在此处粘贴运行代码（如没有可删除该代码块）
# Paste the runtime code here (delete the code block if you don't have it)
```

### Dependencies

```
# 请在此处粘贴依赖情况
# Please paste the dependencies here
```

### 运行日志或截图 | Runtime logs or screenshots

![a730ebd92d07d0fc874184d15f5425b](https://github.com/xusenlinzy/api-for-open-llm/assets/48109376/1b922040-022d-44cf-96cc-98f96c6feb68)

**Comment by xusenlinzy** [comment]
能看一下你的环境变量配置吗

**Comment by 760485464** [comment]
![image](https://github.com/xusenlinzy/api-for-open-llm/assets/48109376/59acb368-9493-40d8-bccc-39104a96bc9c)

**Comment by xusenlinzy** [comment]
https://github.com/xusenlinzy/api-for-open-llm/blob/d03697aea3091073f0bdf953eb05c4c0d47df745/api/apapter/template.py#L565C56-L565C56

**Comment by 760485464** [comment]
好的 谢谢
加到strings数组里面对吧
