### ISSUE TITLE
💡 [REQUEST] - <请求增加OrionStar-Yi-34B-Chat，基于Yi-34B-Base的对话模型>

### ISSUE THREAD

**Issue by markliuyuxiang** [xusenlinzy/api-for-open-llm#174]
### 实现PR | Implementation PR

请求增加OrionStar-Yi-34B-Chat，基于Yi-34B-Base的对话模型
https://huggingface.co/OrionStarAI/OrionStar-Yi-34B-Chat

### 摘要 | Summary

请求增加OrionStar-Yi-34B-Chat，基于Yi-34B-Base的对话模型
https://huggingface.co/OrionStarAI/OrionStar-Yi-34B-Chat

### 基本示例 | Basic Example

请求增加OrionStar-Yi-34B-Chat，基于Yi-34B-Base的对话模型
https://huggingface.co/OrionStarAI/OrionStar-Yi-34B-Chat

### 缺陷 | Drawbacks

该模型比较厉害

**Comment by xusenlinzy** [comment]
刚刚更新了模板，你可以尝试使用下面的配置

```
MODEL_NAME=orionstar
MODEL_PATH=OrionStarAI/OrionStar-Yi-34B-Chat
PROMPT_NAME=orionstar
DEVICE_MAP=auto
```
