### ISSUE TITLE
💡 [REQUEST] - vllm支持更多模型

### ISSUE THREAD

**Issue by yinggoga** [xusenlinzy/api-for-open-llm#175]
### 摘要 | Summary

比如支持chatglm系列
https://docs.vllm.ai/en/latest/models/supported_models.html

### 基本示例 | Basic Example

比如支持chatglm系列
https://docs.vllm.ai/en/latest/models/supported_models.html

### 缺陷 | Drawbacks

比如支持chatglm系列
https://docs.vllm.ai/en/latest/models/supported_models.html

**Comment by xusenlinzy** [comment]
目前代码已经支持chatglm了
