### ISSUE TITLE
希望尽快能对Yi34B-chat模型进行支持

### ISSUE THREAD

**Issue by flyfg** [xusenlinzy/api-for-open-llm#180]
### 提交前必须检查以下项目 | The following items must be checked before submission

- [X] 请确保使用的是仓库最新代码（git pull），一些问题已被解决和修复。 | Make sure you are using the latest code from the repository (git pull), some issues have already been addressed and fixed.
- [X] 我已阅读[项目文档](https://github.com/xusenlinzy/api-for-open-llm/blob/master/README.md)和[FAQ章节](https://github.com/xusenlinzy/api-for-open-llm/blob/master/docs/FAQ.md)并且已在Issue中对问题进行了搜索，没有找到相似问题和解决方案 | I have searched the existing issues / discussions

### 问题类型 | Type of problem

模型推理和部署 | Model inference and deployment

### 操作系统 | Operating system

Linux

### 详细描述问题 | Detailed description of the problem

```

```

### Dependencies

```
```

### 运行日志或截图 | Runtime logs or screenshots

```
```

**Comment by Hapluckyy** [comment]
希望对34b的yi模型的4bit量化版本，8bit量化版本也进行一下支持
