### ISSUE TITLE
💡 [REQUEST] - <title> 请问一下，VLLM可以配置在多块GPU上运行吗，要怎么配置

### ISSUE THREAD

**Issue by jinghai** [xusenlinzy/api-for-open-llm#182]
### 摘要 | Summary

请问一下，VLLM可以配置在多块GPU上运行吗，要怎么配置

### 基本示例 | Basic Example

请问一下，VLLM可以配置在多块GPU上运行吗，要怎么配置

### 缺陷 | Drawbacks

请问一下，VLLM可以配置在多块GPU上运行吗，要怎么配置

**Comment by xusenlinzy** [comment]
TENSOR_PARALLEL_SIZE=2  # GPU数量
ENGINE=vllm

**Comment by jinghai** [comment]
请问我这样配置有错误吗？
- USE_VLLM=true
      - TRUST_REMOTE_CODE=true
      - ENGINE=vllm
      - TENSOR_PARALLEL_SIZE = 2

      - EMBEDDING_NAME=models/bge-large-en-v1.5
      - EMBEDDING_DEVICE=cuda    # CPU:EMBEDDING_DEVICE=cpu，GPU：EMBEDDING_DEVICE=cuda，3号GPU：EMBEDDING_DEVICE=cuda:3
      # - EMBEDDING_SIZE=1536
      - ONLY_EMBEDDING=false
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: ["1","2"]
              capabilities: [gpu]

**Comment by xusenlinzy** [comment]
应该是没问题的

**Comment by jinghai** [comment]
使用最新代码报错如下：
llm-2  | 2023-12-03 09:27:45,235        ERROR services.py:1329 -- Failed to start the dashboard , return code 1
llm-2  | 2023-12-03 09:27:45,236        ERROR services.py:1354 -- Error should be written to 'dashboard.log' or 'dashboard.err'. We are printing the last 20 lines for you. See 'https://docs.ray.io/en/master/ray-observability/ray-logging.html#logging-directory-structure' to find where the log file is.
llm-2  | 2023-12-03 09:27:45,237        ERROR services.py:1398 -- 
llm-2  | The last 20 lines of /tmp/ray/session_2023-12-03_09-27-43_040856_1/logs/dashboard.log (it contains the error message from the dashboard): 
llm-2  |   File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
llm-2  |     return _bootstrap._gcd_import(name[level:], package, level)
llm-2  |   File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
llm-2  |   File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
llm-2  |   File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
llm-2  |   File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
llm-2  |   File "<frozen importlib._bootstrap_external>", line 883, in exec_module
llm-2  |   File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
llm-2  |   File "/usr/local/lib/python3.10/dist-packages/ray/dashboard/modules/job/cli.py", line 16, in <module>
llm-2  |     from ray.job_submission import JobStatus, JobSubmissionClient
llm-2  |   File "/usr/local/lib/python3.10/dist-packages/ray/job_submission/__init__.py", line 2, in <module>
llm-2  |     from ray.dashboard.modules.job.pydantic_models import DriverInfo, JobDetails, JobType
llm-2  |   File "/usr/local/lib/python3.10/dist-packages/ray/dashboard/modules/job/pydantic_models.py", line 4, in <module>
llm-2  |     from ray._private.pydantic_compat import BaseModel, Field, PYDANTIC_INSTALLED
llm-2  |   File "/usr/local/lib/python3.10/dist-packages/ray/_private/pydantic_compat.py", line 100, in <module>
llm-2  |     monkeypatch_pydantic_2_for_cloudpickle()
llm-2  |   File "/usr/local/lib/python3.10/dist-packages/ray/_private/pydantic_compat.py", line 58, in monkeypatch_pydantic_2_for_cloudpickle
llm-2  |     pydantic._internal._model_construction.SchemaSerializer = (
llm-2  | AttributeError: module 'pydantic._internal' has no attribute '_model_construction'
llm-2  | 2023-12-03 09:27:46,501        INFO worker.py:1673 -- Started a local Ray instance.
llm-2  | [2023-12-03 09:27:48,116 E 1 1] core_worker.cc:205: Failed to register worker 01000000ffffffffffffffffffffffffffffffffffffffffffffffff to Raylet. IOError: [RayletClient] Unable to register worker with raylet. No such file or directory
llm-2 exited with code 0
---------------------------------------------------------------------------------
配置文件如下：
environment:
      - PORT=8000
      - ENGINE=vllm
      - USE_VLLM=true
      - TRUST_REMOTE_CODE=true
      - TOKENIZE_MODE=slow
      - TENSOR_PARALLEL_SIZE=2
      - DTYPE=half
      - NUM_GPUS=2
      - MODEL_NAME=Qwen-14B-Chat
      - MODEL_PATH=checkpoints/Qwen-14B-Chat
      

      - EMBEDDING_NAME=checkpoints/bge-large-zh-v1.5
      - EMBEDDING_DEVICE=cuda    # CPU:EMBEDDING_DEVICE=cpu，GPU：EMBEDDING_DEVICE=cuda，3号GPU：EMBEDDING_DEVICE=cuda:3
      # - EMBEDDING_SIZE=1536
      - ONLY_EMBEDDING=false
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: ['2','3']
              capabilities: [gpu]
    volumes:
      - /data0/models:/workspace/checkpoints

**Comment by jinghai** [comment]
启动时的参数打印：
llm-2  | 2023-12-03 09:27:50.931 | DEBUG    | api.config:<module>:237 - SETTINGS: {
llm-2  |     "host": "0.0.0.0",
llm-2  |     "port": 8000,
llm-2  |     "api_prefix": "/v1",
llm-2  |     "engine": "vllm",
llm-2  |     "model_name": "Qwen-14B-Chat",
llm-2  |     "model_path": "checkpoints/Qwen-14B-Chat",
llm-2  |     "adapter_model_path": null,
llm-2  |     "resize_embeddings": false,
llm-2  |     "dtype": "half",
llm-2  |     "device": "cuda",
llm-2  |     "device_map": null,
llm-2  |     "gpus": null,
llm-2  |     "num_gpus": 1,
llm-2  |     "only_embedding": false,
llm-2  |     "embedding_name": "checkpoints/bge-large-zh-v1.5",
llm-2  |     "embedding_size": -1,
llm-2  |     "embedding_device": "cuda",
llm-2  |     "quantize": 16,
llm-2  |     "load_in_8bit": false,
llm-2  |     "load_in_4bit": false,
llm-2  |     "using_ptuning_v2": false,
llm-2  |     "context_length": -1,
llm-2  |     "chat_template": null,
llm-2  |     "patch_type": null,
llm-2  |     "alpha": "auto",
llm-2  |     "trust_remote_code": true,
llm-2  |     "tokenize_mode": "slow",
llm-2  |     "tensor_parallel_size": 2,
llm-2  |     "gpu_memory_utilization": 0.9,
llm-2  |     "max_num_batched_tokens": -1,
llm-2  |     "max_num_seqs": 256,
llm-2  |     "quantization_method": null,
llm-2  |     "use_streamer_v2": false,
llm-2  |     "api_keys": null,
llm-2  |     "activate_inference": true,
llm-2  |     "interrupt_requests": true,
llm-2  |     "n_gpu_layers": 0,
llm-2  |     "main_gpu": 0,
llm-2  |     "tensor_split": null,
llm-2  |     "n_batch": 512,
llm-2  |     "n_threads": 40,
llm-2  |     "n_threads_batch": 40,
llm-2  |     "rope_scaling_type": -1,
llm-2  |     "rope_freq_base": 0.0,
llm-2  |     "rope_freq_scale": 0.0
llm-2  | }

**Comment by JadynWong** [comment]
> ## 使用最新代码报错如下：
> llm-2 | 2023-12-03 09:27:45,235 ERROR services.py:1329 -- Failed to start the dashboard , return code 1
> llm-2 | 2023-12-03 09:27:45,236 ERROR services.py:1354 -- Error should be written to 'dashboard.log' or 'dashboard.err'. We are printing the last 20 lines for you. See '[docs.ray.io/en/master/ray-observability/ray-logging.html#logging-directory-structure](https://docs.ray.io/en/master/ray-observability/ray-logging.html#logging-directory-structure)' to find where the log file is.
> llm-2 | 2023-12-03 09:27:45,237 ERROR services.py:1398 --
> llm-2 | The last 20 lines of /tmp/ray/session_2023-12-03_09-27-43_040856_1/logs/dashboard.log (it contains the error message from the dashboard):
> llm-2 | File "/usr/lib/python3.10/importlib/**init**.py", line 126, in import_module
> llm-2 | return _bootstrap._gcd_import(name[level:], package, level)
> llm-2 | File "", line 1050, in _gcd_import
> llm-2 | File "", line 1027, in _find_and_load
> llm-2 | File "", line 1006, in _find_and_load_unlocked
> llm-2 | File "", line 688, in _load_unlocked
> llm-2 | File "", line 883, in exec_module
> llm-2 | File "", line 241, in _call_with_frames_removed
> llm-2 | File "/usr/local/lib/python3.10/dist-packages/ray/dashboard/modules/job/cli.py", line 16, in
> llm-2 | from ray.job_submission import JobStatus, JobSubmissionClient
> llm-2 | File "/usr/local/lib/python3.10/dist-packages/ray/job_submission/**init**.py", line 2, in
> llm-2 | from ray.dashboard.modules.job.pydantic_models import DriverInfo, JobDetails, JobType
> llm-2 | File "/usr/local/lib/python3.10/dist-packages/ray/dashboard/modules/job/pydantic_models.py", line 4, in
> llm-2 | from ray._private.pydantic_compat import BaseModel, Field, PYDANTIC_INSTALLED
> llm-2 | File "/usr/local/lib/python3.10/dist-packages/ray/_private/pydantic_compat.py", line 100, in
> llm-2 | monkeypatch_pydantic_2_for_cloudpickle()
> llm-2 | File "/usr/local/lib/python3.10/dist-packages/ray/_private/pydantic_compat.py", line 58, in monkeypatch_pydantic_2_for_cloudpickle
> llm-2 | pydantic._internal._model_construction.SchemaSerializer = (
> llm-2 | AttributeError: module 'pydantic._internal' has no attribute '_model_construction'
> llm-2 | 2023-12-03 09:27:46,501 INFO worker.py:1673 -- Started a local Ray instance.
> llm-2 | [2023-12-03 09:27:48,116 E 1 1] core_worker.cc:205: Failed to register worker 01000000ffffffffffffffffffffffffffffffffffffffffffffffff to Raylet. IOError: [RayletClient] Unable to register worker with raylet. No such file or directory
> llm-2 exited with code 0
> 配置文件如下： environment: - PORT=8000 - ENGINE=vllm - USE_VLLM=true - TRUST_REMOTE_CODE=true - TOKENIZE_MODE=slow - TENSOR_PARALLEL_SIZE=2 - DTYPE=half - NUM_GPUS=2 - MODEL_NAME=Qwen-14B-Chat - MODEL_PATH=checkpoints/Qwen-14B-Chat
> 
> ```
>   - EMBEDDING_NAME=checkpoints/bge-large-zh-v1.5
>   - EMBEDDING_DEVICE=cuda    # CPU:EMBEDDING_DEVICE=cpu，GPU：EMBEDDING_DEVICE=cuda，3号GPU：EMBEDDING_DEVICE=cuda:3
>   # - EMBEDDING_SIZE=1536
>   - ONLY_EMBEDDING=false
> deploy:
>   resources:
>     reservations:
>       devices:
>         - driver: nvidia
>           device_ids: ['2','3']
>           capabilities: [gpu]
> volumes:
>   - /data0/models:/workspace/checkpoints
> ```

相同的报错, 多卡vllm. 单卡vllm启动没问题, 请问有解决方案吗?
