### ISSUE TITLE
打印异常信息traceback调用有误

### ISSUE THREAD

**Issue by lzhfe** [xusenlinzy/api-for-open-llm#183]
### 提交前必须检查以下项目 | The following items must be checked before submission

- [X] 请确保使用的是仓库最新代码（git pull），一些问题已被解决和修复。 | Make sure you are using the latest code from the repository (git pull), some issues have already been addressed and fixed.
- [X] 我已阅读[项目文档](https://github.com/xusenlinzy/api-for-open-llm/blob/master/README.md)和[FAQ章节](https://github.com/xusenlinzy/api-for-open-llm/blob/master/docs/FAQ.md)并且已在Issue中对问题进行了搜索，没有找到相似问题和解决方案 | I have searched the existing issues / discussions

### 问题类型 | Type of problem

模型推理和部署 | Model inference and deployment

### 操作系统 | Operating system

macOS

### 详细描述问题 | Detailed description of the problem

https://github.com/xusenlinzy/api-for-open-llm/blob/master/api/generation/core.py#L130
是否应该为：
```
traceback.print_exc()
```

### Dependencies

```
# 请在此处粘贴依赖情况
# Please paste the dependencies here
```

### 运行日志或截图 | Runtime logs or screenshots

<img width="784" alt="image" src="https://github.com/xusenlinzy/api-for-open-llm/assets/59367267/5284ee44-0430-4fce-b581-4ad4cab740a4">

**Comment by xusenlinzy** [comment]
是的，这里写错了
