### ISSUE TITLE
AttributeError: type object 'BaseModel' has no attribute 'model_config'

### ISSUE THREAD

**Issue by wuxiulike** [xusenlinzy/api-for-open-llm#184]
### 提交前必须检查以下项目 | The following items must be checked before submission

- [X] 请确保使用的是仓库最新代码（git pull），一些问题已被解决和修复。 | Make sure you are using the latest code from the repository (git pull), some issues have already been addressed and fixed.
- [X] 我已阅读[项目文档](https://github.com/xusenlinzy/api-for-open-llm/blob/master/README.md)和[FAQ章节](https://github.com/xusenlinzy/api-for-open-llm/blob/master/docs/FAQ.md)并且已在Issue中对问题进行了搜索，没有找到相似问题和解决方案 | I have searched the existing issues / discussions

### 问题类型 | Type of problem

启动命令 | Startup command

### 操作系统 | Operating system

Linux

### 详细描述问题 | Detailed description of the problem

```
# 请在此处粘贴运行代码（如没有可删除该代码块）
# Paste the runtime code here (delete the code block if you don't have it)
```
之前python server.py一直运行正常，今天git pull之后，再运行就报错了。
AttributeError: type object 'BaseModel' has no attribute 'model_config'

### Dependencies

```
# 请在此处粘贴依赖情况
# Please paste the dependencies here
```
(api-for-open-llm) root@estar-ESC8000-G4:~/api-for-open-llm# pip list | grep -E 'transformers|peft|torch'
peft                          0.5.0
sentence-transformers         2.2.2
torch                         2.0.1
torchaudio                    2.0.2
torchvision                   0.15.2
transformers                  4.33.2
transformers-stream-generator 0.0.4
(api-for-open-llm) root@estar-ESC8000-G4:~/api-for-open-llm# 

### 运行日志或截图 | Runtime logs or screenshots

```
# 请在此处粘贴运行日志
# Please paste the run log here
```
.env文件内容：
PORT=8000

# model related
MODEL_NAME=chatglm
MODEL_PATH=/opt/models/chatglm3-6b
EMBEDDING_NAME=
ADAPTER_MODEL_PATH=
QUANTIZE=16
CONTEXT_LEN=
LOAD_IN_8BIT=false
LOAD_IN_4BIT=false
USING_PTUNING_V2=false
STREAM_INTERVERL=2
PROMPT_NAME=

# device related
DEVICE=cuda
DEVICE_MAP=
GPUS=
NUM_GPUs=1
DTYPE=half

# patch related
PATCH_TYPE=

# api related
API_PREFIX=/v1

USE_STREAMER_V2=false
ENGINE=default
~                    

运行报错日志
(api-for-open-llm) root@estar-ESC8000-G4:~/api-for-open-llm# python server.py 
Traceback (most recent call last):
  File "/root/api-for-open-llm/server.py", line 1, in <module>
    from api.config import SETTINGS
  File "/root/api-for-open-llm/api/config.py", line 11, in <module>
    BaseModel.model_config["protected_namespaces"] = ()
AttributeError: type object 'BaseModel' has no attribute 'model_config'

**Comment by xusenlinzy** [comment]
https://github.com/xusenlinzy/api-for-open-llm/blob/master/requirements.txt

你好，最近项目更新了，请按照 requirements.txt 升级一下相关的库

**Comment by Pzeyang** [comment]
最新的还是有这个错

**Comment by xusenlinzy** [comment]
先安装vllm0.2.2再pip install -r requirements.txt应该是可以的

**Comment by Pzeyang** [comment]
我先安装vllm0.2.2再pip install -r requirements.txt后，是vllm0.2.2搭配pydantic-2.5.2，报了这个错AttributeError: module 'pydantic._internal' has no attribute '_model_construction'。我觉得是pydantic版本的问题，所以再pip安装了vllm0.2.2搭配pydantic-1.10.13，就报AttributeError: type object 'BaseModel' has no attribute 'model_config'。我用的cuda11.8搭配的torch2.1.0

**Comment by Pzeyang** [comment]
好的
