### ISSUE TITLE
vLLM启动时报错“then set the option `trust_remote_code=True` to remove this error”

### ISSUE THREAD

**Issue by wuxiulike** [xusenlinzy/api-for-open-llm#185]
### 提交前必须检查以下项目 | The following items must be checked before submission

- [X] 请确保使用的是仓库最新代码（git pull），一些问题已被解决和修复。 | Make sure you are using the latest code from the repository (git pull), some issues have already been addressed and fixed.
- [X] 我已阅读[项目文档](https://github.com/xusenlinzy/api-for-open-llm/blob/master/README.md)和[FAQ章节](https://github.com/xusenlinzy/api-for-open-llm/blob/master/docs/FAQ.md)并且已在Issue中对问题进行了搜索，没有找到相似问题和解决方案 | I have searched the existing issues / discussions

### 问题类型 | Type of problem

启动命令 | Startup command

### 操作系统 | Operating system

Linux

### 详细描述问题 | Detailed description of the problem

```
# 请在此处粘贴运行代码（如没有可删除该代码块）
# Paste the runtime code here (delete the code block if you don't have it)
```
按照文档进行了安装：
pip install -r requirements.txt
pip install torch==2.0.1
pip install xformers --no-deps
pip install vllm==0.2.0
pip uninstall transformer-engine -y

这里就有个问题，requirements.txt默认安装的事torch2.1.1。装完之后可以python server.py
报错如下：

(apiall) root@estar-ESC8000-G4:~/api-for-open-llm# python server.py 
2023-11-29 13:33:40.849 | DEBUG    | api.config:<module>:237 - SETTINGS: {
    "host": "0.0.0.0",
    "port": 8000,
    "api_prefix": "/v1",
    "engine": "vllm",
    "model_name": "baichuan-13b-chat",
    "model_path": "/opt/models/Baichuan2-13B-Chat",
    "adapter_model_path": null,
    "resize_embeddings": false,
    "dtype": "half",
    "device": "cuda",
    "device_map": null,
    "gpus": null,
    "num_gpus": 1,
    "only_embedding": false,
    "embedding_name": null,
    "embedding_size": -1,
    "embedding_device": "cuda",
    "quantize": 16,
    "load_in_8bit": false,
    "load_in_4bit": false,
    "using_ptuning_v2": false,
    "context_length": -1,
    "chat_template": null,
    "patch_type": null,
    "alpha": "auto",
    "trust_remote_code": false,
    "tokenize_mode": "auto",
    "tensor_parallel_size": 2,
    "gpu_memory_utilization": 0.9,
    "max_num_batched_tokens": -1,
    "max_num_seqs": 256,
    "quantization_method": null,
    "use_streamer_v2": false,
    "api_keys": null,
    "activate_inference": true,
    "interrupt_requests": true,
    "n_gpu_layers": 0,
    "main_gpu": 0,
    "tensor_split": null,
    "n_batch": 512,
    "n_threads": 40,
    "n_threads_batch": 40,
    "rope_scaling_type": -1,
    "rope_freq_base": 0.0,
    "rope_freq_scale": 0.0
}
Traceback (most recent call last):
  File "/root/anaconda3/envs/apiall/lib/python3.10/site-packages/vllm/transformers_utils/config.py", line 30, in get_config
    config = AutoConfig.from_pretrained(
  File "/root/anaconda3/envs/apiall/lib/python3.10/site-packages/transformers/models/auto/configuration_auto.py", line 1037, in from_pretrained
    trust_remote_code = resolve_trust_remote_code(
  File "/root/anaconda3/envs/apiall/lib/python3.10/site-packages/transformers/dynamic_module_utils.py", line 618, in resolve_trust_remote_code
    raise ValueError(
ValueError: Loading /opt/models/Baichuan2-13B-Chat requires you to execute the configuration file in that repo on your local machine. Make sure you have read the code there to avoid malicious use, then set the option `trust_remote_code=True` to remove this error.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/root/api-for-open-llm/server.py", line 2, in <module>
    from api.models import app, EMBEDDED_MODEL, GENERATE_ENGINE
  File "/root/api-for-open-llm/api/models.py", line 144, in <module>
    GENERATE_ENGINE = create_vllm_engine()
  File "/root/api-for-open-llm/api/models.py", line 89, in create_vllm_engine
    engine = AsyncLLMEngine.from_engine_args(engine_args)
  File "/root/anaconda3/envs/apiall/lib/python3.10/site-packages/vllm/engine/async_llm_engine.py", line 480, in from_engine_args
    engine_configs = engine_args.create_engine_configs()
  File "/root/anaconda3/envs/apiall/lib/python3.10/site-packages/vllm/engine/arg_utils.py", line 174, in create_engine_configs
    model_config = ModelConfig(self.model, self.tokenizer,
  File "/root/anaconda3/envs/apiall/lib/python3.10/site-packages/vllm/config.py", line 74, in __init__
    self.hf_config = get_config(model, trust_remote_code, revision)
  File "/root/anaconda3/envs/apiall/lib/python3.10/site-packages/vllm/transformers_utils/config.py", line 40, in get_config
    raise RuntimeError(err_msg) from e
RuntimeError: Failed to load the model config. If the model is a custom model not yet available in the HuggingFace transformers library, consider setting `trust_remote_code=True` in LLM or using the `--trust-remote-code` flag in the CLI.

然后安装pip install vllm==0.2.0之后torch降级==2.0.1，再运行python server.py
报错
(apiall) root@estar-ESC8000-G4:~/api-for-open-llm# python server.py 
Traceback (most recent call last):
  File "/root/api-for-open-llm/server.py", line 1, in <module>
    from api.config import SETTINGS
  File "/root/api-for-open-llm/api/config.py", line 11, in <module>
    BaseModel.model_config["protected_namespaces"] = ()
AttributeError: type object 'BaseModel' has no attribute 'model_config'

### Dependencies

```
# 请在此处粘贴依赖情况
# Please paste the dependencies here
```
(apiall) root@estar-ESC8000-G4:~/api-for-open-llm# pip list | grep -E 'transformers|peft|torch'
peft                          0.6.2
sentence-transformers         2.2.2
torch                         2.1.0
torchvision                   0.16.1
transformers                  4.34.1
transformers-stream-generator 0.0.4
(apiall) root@estar-ESC8000-G4:~/api-for-open-llm# 

.env内容为
ORT=8000

# model related
MODEL_NAME=baichuan-13b-chat
MODEL_PATH=/opt/models/Baichuan2-13B-Chat
EMBEDDING_NAME=
TENSOR_PARALLEL_SIZE=2
ADAPTER_MODEL_PATH=
QUANTIZE=16
CONTEXT_LEN=
LOAD_IN_8BIT=false
LOAD_IN_4BIT=false
USING_PTUNING_V2=false
STREAM_INTERVERL=2
PROMPT_NAME=

# device related
DEVICE=cuda
DEVICE_MAP=
GPUS=
NUM_GPUs=1
DTYPE=half

# patch related
PATCH_TYPE=

# api related
API_PREFIX=/v1

USE_STREAMER_V2=false
ENGINE=vllm
trust_remote_code=True
~                                                                                                                                           
".env" 32L, 462B                                                                                                          32,22         All

### 运行日志或截图 | Runtime logs or screenshots

```
# 请在此处粘贴运行日志
# Please paste the run log here
```

**Comment by wuxiulike** [comment]
哦，抱歉，我可能用错了.env.example

**Comment by xusenlinzy** [comment]
vllm的本地环境忘记改了，应该是下面的

https://github.com/xusenlinzy/api-for-open-llm/blob/master/docs/VLLM_SCRIPT.md#%E6%9C%AC%E5%9C%B0%E7%8E%AF%E5%A2%83
