### ISSUE TITLE
WARNING： Some paramters are on the meta device device beacuase they were offloaded to the cpu.

### ISSUE THREAD

**Issue by EchoShoot** [xusenlinzy/api-for-open-llm#191]
### 提交前必须检查以下项目 | The following items must be checked before submission

- [X] 请确保使用的是仓库最新代码（git pull），一些问题已被解决和修复。 | Make sure you are using the latest code from the repository (git pull), some issues have already been addressed and fixed.
- [X] 我已阅读[项目文档](https://github.com/xusenlinzy/api-for-open-llm/blob/master/README.md)和[FAQ章节](https://github.com/xusenlinzy/api-for-open-llm/blob/master/docs/FAQ.md)并且已在Issue中对问题进行了搜索，没有找到相似问题和解决方案 | I have searched the existing issues / discussions

### 问题类型 | Type of problem

模型推理和部署 | Model inference and deployment

### 操作系统 | Operating system

Linux

### 详细描述问题 | Detailed description of the problem

在 docker 中跑 qwen-14b-chat 非常的慢，日志里有如下提示
```
WARNING： Some paramters are on the meta device device beacuase they were offloaded to the cpu.
```

### Dependencies

```
# 请在此处粘贴依赖情况
# Please paste the dependencies here
```

### 运行日志或截图 | Runtime logs or screenshots

```
llm-apiserver-1  | Warning: please make sure that you are using the latest codes and checkpoints, especially if you used Qwen-7B before 09.25.2023.请使用最新模型和代码，尤其如果你在9月25日前已经开始使用Qwe[0/1381]万注意不要使用错误代码和模型。                       
llm-apiserver-1  | Try importing flash-attention for faster inference...
Loading checkpoint shards: 100%|██████████| 15/15 [00:11<00:00,  1.29it/s]
llm-apiserver-1  | WARNING:root:Some parameters are on the meta device device because they were offloaded to the cpu.
llm-apiserver-1  | 2023-12-06 03:17:09.098 | INFO     | api.models:create_generate_model:54 - Using default engine
llm-apiserver-1  | 2023-12-06 03:17:09.099 | INFO     | api.core.default:_check_construct_prompt:117 - Using Qwen Model for Chat!
llm-apiserver-1  | 2023-12-06 03:17:09.099 | INFO     | api.core.default:_fix_tokenizer:126 - Add eos token: <|endoftext|>
llm-apiserver-1  | 2023-12-06 03:17:09.099 | INFO     | api.core.default:_fix_tokenizer:133 - Add pad token: <|endoftext|>
llm-apiserver-1  | INFO:     Started server process [1]
llm-apiserver-1  | INFO:     Waiting for application startup.
llm-apiserver-1  | INFO:     Application startup complete.
llm-apiserver-1  | INFO:     Uvicorn running on http://0.0.0.0:8000 (Press CTRL+C to quit)
llm-apiserver-1  | 2023-12-06 03:17:18.237 | DEBUG    | api.routes.chat:create_chat_completion:46 - ==== request ====
llm-apiserver-1  | {'model': 'gpt-3.5-turbo', 'frequency_penalty': 0.0, 'function_call': None, 'functions': None, 'logit_bias': None, 'max_tokens': 1024, 'n': 1, 'presence_penalty': 0.0, 'response_format': None, 'seed': None, 'stop': ['<|endoftext|>', '<|im_end|>'], 'temperature': 0.5, 'tool_choice': None, 'tools': None, 'top_p': 1.0, 'user': None, 'stream': True, 'prompt_or_messages': [{'content': '\nYou are ChatGPT, a la
rge language model trained by OpenAI.\nKnowledge cutoff: 2021-09\nCurrent model: gpt-3.5-turbo\nCurrent time: 2023/12/6 11:17:17\nLatex inline: $x^2$ \nLatex block: $$e=mc^2$$\n\n', 'role': 'system'}, {'content': '你好', 'role': 'user'}, {'content': '你好！', 'role': 'assistant'}, {'content': '请帮我写一个 fastapi 的用例', 'role': 'user'}], 'echo': False, 'stop_token_ids': [151643, 151644, 151645]}

```

**Comment by xusenlinzy** [comment]
请问你用的是单卡吗，我使用双卡3090测试速度还行
![image](https://github.com/xusenlinzy/api-for-open-llm/assets/111472355/6fd37c18-51df-4f17-938a-d174842ecc41)

**Comment by EchoShoot** [comment]
> 请问你用的是单卡吗，我使用双卡3090测试速度还行 ![image](https://private-user-images.githubusercontent.com/111472355/288274096-6fd37c18-51df-4f17-938a-d174842ecc41.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDE4NDA4MDIsIm5iZiI6MTcwMTg0MDUwMiwicGF0aCI6Ii8xMTE0NzIzNTUvMjg4Mjc0MDk2LTZmZDM3YzE4LTUxZGYtNGYxNy05MzhhLWQxNzQ4NDJlY2M0MS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjA2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIwNlQwNTI4MjJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xZWQ0Y2YzNzgxZDk0ODQ3OWQ1ZmYwMzkzMjc0ZjcxMzlhNWRkOTYyOGNiYzBkNTBjYWUyNjM0OTc2NGFlMmQ1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.VDz6Bwvj7epZUqkGVedMzQL56ylHKnzuZgB4GnT9ABY)

我用的是单卡，3090，显存能装下 qwen-14b-chat。但速度也太慢了，一秒钟蹦出两个字。感觉有问题。
