### ISSUE TITLE
vllm启动qwen72B出错

### ISSUE THREAD

**Issue by T0L0ve** [xusenlinzy/api-for-open-llm#196]
### 提交前必须检查以下项目 | The following items must be checked before submission

- [X] 请确保使用的是仓库最新代码（git pull），一些问题已被解决和修复。 | Make sure you are using the latest code from the repository (git pull), some issues have already been addressed and fixed.
- [X] 我已阅读[项目文档](https://github.com/xusenlinzy/api-for-open-llm/blob/master/README.md)和[FAQ章节](https://github.com/xusenlinzy/api-for-open-llm/blob/master/docs/FAQ.md)并且已在Issue中对问题进行了搜索，没有找到相似问题和解决方案 | I have searched the existing issues / discussions

### 问题类型 | Type of problem

模型推理和部署 | Model inference and deployment

### 操作系统 | Operating system

Linux

### 详细描述问题 | Detailed description of the problem

运行server.py出现错误
`ValueError: Unknown quantization method: gptq. Must be one of ['awq', 'squeezellm'].`
这是vllm不支持gptq量化的模型吗

### Dependencies

‘’‘
peft                          0.7.0
sentence-transformers         2.2.2
torch                         2.1.0+cu118
torchaudio                    2.1.0+cu118
torchvision                   0.16.0+cu118
transformers                  4.34.1
transformers-stream-generator 0.0.4
‘’’

### 运行日志或截图 | Runtime logs or screenshots

`2023-12-08 17:04:02.455 | DEBUG    | api.config:<module>:244 - SETTINGS: {
    "host": "0.0.0.0",
    "port": 8000,
    "api_prefix": "/v1",
    "engine": "vllm",
    "model_name": "qwen",
    "model_path": "/workspace/AIProjects/models/Qwen-72B-Chat-Int4",
    "adapter_model_path": null,
    "resize_embeddings": false,
    "dtype": "half",
    "device": "cuda",
    "device_map": null,
    "gpus": null,
    "num_gpus": 1,
    "only_embedding": false,
    "embedding_name": null,
    "embedding_size": -1,
    "embedding_device": "cuda",
    "quantize": 16,
    "load_in_8bit": false,
    "load_in_4bit": false,
    "using_ptuning_v2": false,
    "pre_seq_len": 128,
    "context_length": -1,
    "chat_template": null,
    "patch_type": null,
    "alpha": "auto",
    "trust_remote_code": true,
    "tokenize_mode": "slow",
    "tensor_parallel_size": 1,
    "gpu_memory_utilization": 0.9,
    "max_num_batched_tokens": -1,
    "max_num_seqs": 256,
    "quantization_method": null,
    "use_streamer_v2": false,
    "api_keys": null,
    "activate_inference": true,
    "interrupt_requests": true,
    "n_gpu_layers": 0,
    "main_gpu": 0,
    "tensor_split": null,
    "n_batch": 512,
    "n_threads": 40,
    "n_threads_batch": 40,
    "rope_scaling_type": -1,
    "rope_freq_base": 0.0,
    "rope_freq_scale": 0.0
}
Traceback (most recent call last):
  File "/workspace/edit/api-for-open-llm/server.py", line 2, in <module>
    from api.models import app, EMBEDDED_MODEL, GENERATE_ENGINE
  File "/workspace/edit/api-for-open-llm/api/models.py", line 145, in <module>
    GENERATE_ENGINE = create_vllm_engine()
  File "/workspace/edit/api-for-open-llm/api/models.py", line 90, in create_vllm_engine
    engine = AsyncLLMEngine.from_engine_args(engine_args)
  File "/workspace/anaconda3/envs/vllm/lib/python3.10/site-packages/vllm/engine/async_llm_engine.py", line 480, in from_engine_args
    engine_configs = engine_args.create_engine_configs()
  File "/workspace/anaconda3/envs/vllm/lib/python3.10/site-packages/vllm/engine/arg_utils.py", line 187, in create_engine_configs
    model_config = ModelConfig(self.model, self.tokenizer,
  File "/workspace/anaconda3/envs/vllm/lib/python3.10/site-packages/vllm/config.py", line 97, in __init__
    self._verify_quantization()
  File "/workspace/anaconda3/envs/vllm/lib/python3.10/site-packages/vllm/config.py", line 137, in _verify_quantization
    raise ValueError(
ValueError: Unknown quantization method: gptq. Must be one of ['awq', 'squeezellm'].`

**Comment by xusenlinzy** [comment]
是的，vllm现在不支持gptq

**Comment by T0L0ve** [comment]
还想问一下，为什么四卡启动的时候显存并不是平均分配的



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年12月8日(周五) 下午5:46
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [xusenlinzy/api-for-open-llm] vllm启动qwen72B出错 (Issue #196)




 
是的，vllm现在不支持gptq
