### ISSUE TITLE
BaiChuan2Template不支持system prompt，需要添加以下模板支持

### ISSUE THREAD

**Issue by DarkDance** [xusenlinzy/api-for-open-llm#203]
### 提交前必须检查以下项目 | The following items must be checked before submission

- [X] 请确保使用的是仓库最新代码（git pull），一些问题已被解决和修复。 | Make sure you are using the latest code from the repository (git pull), some issues have already been addressed and fixed.
- [X] 我已阅读[项目文档](https://github.com/xusenlinzy/api-for-open-llm/blob/master/README.md)和[FAQ章节](https://github.com/xusenlinzy/api-for-open-llm/blob/master/docs/FAQ.md)并且已在Issue中对问题进行了搜索，没有找到相似问题和解决方案 | I have searched the existing issues / discussions

### 问题类型 | Type of problem

效果问题 | Effectiveness issues

### 操作系统 | Operating system

Windows

### 详细描述问题 | Detailed description of the problem

class BaiChuan2Template(BaseTemplate)  里面返回的模板开头没有system_prompt的处理，导致模型测试的时候实际上没有效果

### Dependencies

加上下面的代码就好了
            "{% if messages[0]['role'] == 'system' %}"
            "{{ messages[0]['content'] }}"
            "{% else %}"
            "{{ system_prompt }}"
            "{% endif %}"

**Comment by xusenlinzy** [comment]
已经加上了，使用时需要指定PROMPT_NAME=baichuan2
