### ISSUE TITLE
能提供模型训练的完整框架吗

### ISSUE THREAD

**Issue by lucheng07082221** [xusenlinzy/api-for-open-llm#205]
### 实现PR | Implementation PR

能提供模型训练的完整框架吗

### 相关Issues | Reference Issues

能提供模型训练的完整框架吗

### 摘要 | Summary

能提供模型训练的完整框架吗

### 基本示例 | Basic Example

能提供模型训练的完整框架吗

### 缺陷 | Drawbacks

能提供模型训练的完整框架吗

**Comment by xusenlinzy** [comment]
你可以使用这个训练模型 https://github.com/hiyouga/LLaMA-Factory
