### ISSUE TITLE
💡 [REQUEST] - 对于 API 类大语言模型的支持

### ISSUE THREAD

**Issue by DevXiaolan** [xusenlinzy/api-for-open-llm#207]
### 起始日期 | Start Date

12/20/2023

### 摘要 | Summary

Gemini
ChatGLM
文心一言4

### 基本示例 | Basic Example

--

### 缺陷 | Drawbacks

--

**Comment by 2catycm** [comment]
项目的名字叫做OpenLLM，但是感觉完全不必作茧自缚。既然本地都能支持，API应该更简单

**Comment by 2catycm** [comment]
要不fork一个api-for-closed-llm，然后在里面写
