### ISSUE TITLE
baichuan2-13b-chat，正常启动之后，无法使用gpu资源

### ISSUE THREAD

**Issue by TangSY** [xusenlinzy/api-for-open-llm#209]
### 提交前必须检查以下项目 | The following items must be checked before submission

- [X] 请确保使用的是仓库最新代码（git pull），一些问题已被解决和修复。 | Make sure you are using the latest code from the repository (git pull), some issues have already been addressed and fixed.
- [X] 我已阅读[项目文档](https://github.com/xusenlinzy/api-for-open-llm/blob/master/README.md)和[FAQ章节](https://github.com/xusenlinzy/api-for-open-llm/blob/master/docs/FAQ.md)并且已在Issue中对问题进行了搜索，没有找到相似问题和解决方案 | I have searched the existing issues / discussions

### 问题类型 | Type of problem

模型推理和部署 | Model inference and deployment

### 操作系统 | Operating system

Linux

### 运行日志或截图 | Runtime logs or screenshots

![image](https://github.com/xusenlinzy/api-for-open-llm/assets/16008985/746689bc-157e-48f2-843f-8fb24f908388)
这是GPU资源使用情况

![image](https://github.com/xusenlinzy/api-for-open-llm/assets/16008985/786ddc94-1b8f-45cc-b9f7-8e477f1d1299)
这个是env配置文件内容

启动命令：python server.py

**Comment by xusenlinzy** [comment]
启动之后的日志能看一下吗，有没有报错

**Comment by TangSY** [comment]
<img width="989" alt="image" src="https://github.com/xusenlinzy/api-for-open-llm/assets/16008985/8e2d4534-2536-4ad7-8e72-7b851a61e46d">
这是报错信息吗？还是只是建议

**Comment by xusenlinzy** [comment]
可能是pytorch和cuda版本的问题，升级一下pytorch试试

**Comment by TangSY** [comment]
pytorch是最新版了

**Comment by xusenlinzy** [comment]
升级一下CUDA版本呢

**Comment by TangSY** [comment]
我试试

**Comment by Tendo33** [comment]
GPUS=0吧
