### ISSUE TITLE
baichuan模型服务的的基础镜像是什么？

### ISSUE THREAD

**Issue by Smile-L** [xusenlinzy/api-for-open-llm#21]
百川模型的镜像 llm:pytorch-1.14 和其他模型的不同
想问下这个image的基础是哪个？ 是不是要修改：FROM nvcr.io/nvidia/pytorch:22.12-py3

**Comment by xusenlinzy** [comment]
不好意思写错了，但是原镜像需要安装新的包 transformers_stream_generator，需要重新构建镜像
启动命令见：https://github.com/xusenlinzy/api-for-open-llm/blob/master/SCRIPT.md#baichuan-13b-chat
