### ISSUE TITLE
VLLM已经支持gptq，可以支持gptq吗

### ISSUE THREAD

**Issue by Alberoyang** [xusenlinzy/api-for-open-llm#210]
### 提交前必须检查以下项目 | The following items must be checked before submission

- [X] 请确保使用的是仓库最新代码（git pull），一些问题已被解决和修复。 | Make sure you are using the latest code from the repository (git pull), some issues have already been addressed and fixed.
- [X] 我已阅读[项目文档](https://github.com/xusenlinzy/api-for-open-llm/blob/master/README.md)和[FAQ章节](https://github.com/xusenlinzy/api-for-open-llm/blob/master/docs/FAQ.md)并且已在Issue中对问题进行了搜索，没有找到相似问题和解决方案 | I have searched the existing issues / discussions

### 问题类型 | Type of problem

其他问题 | Other issues

### 操作系统 | Operating system

Linux

### 详细描述问题 | Detailed description of the problem

```
https://github.com/vllm-project/vllm/pull/916  vllm支持gptq的pr 并且在cuda环境下应该是可用的

```
![image](https://github.com/xusenlinzy/api-for-open-llm/assets/39474846/78279e39-2947-4d56-8ced-59c364ea6f15)
![image](https://github.com/xusenlinzy/api-for-open-llm/assets/39474846/56c78663-04cc-45ac-88d2-babfb6ddac7c)

**Comment by xusenlinzy** [comment]
更新vllm到最新版本就可以用的
