### ISSUE TITLE
能解试下这个presence_penalty 参数应该设置多少吗？

### ISSUE THREAD

**Issue by lucheng07082221** [xusenlinzy/api-for-open-llm#214]
### 实现PR | Implementation PR

能解试下这个presence_penalty 参数应该设置多少吗？

### 摘要 | Summary

能解试下这个presence_penalty 参数应该设置多少吗？

### 基本示例 | Basic Example

能解试下这个presence_penalty 参数应该设置多少吗？

### 缺陷 | Drawbacks

能解试下这个presence_penalty 参数应该设置多少吗？

**Comment by xusenlinzy** [comment]
这个参数暂时没有生效

**Comment by lucheng07082221** [comment]
收到，谢谢
