### ISSUE TITLE
vllm 加载 llama2 设置多卡不生效

### ISSUE THREAD

**Issue by Maydaytyh** [xusenlinzy/api-for-open-llm#218]
### 提交前必须检查以下项目 | The following items must be checked before submission

- [X] 请确保使用的是仓库最新代码（git pull），一些问题已被解决和修复。 | Make sure you are using the latest code from the repository (git pull), some issues have already been addressed and fixed.
- [X] 我已阅读[项目文档](https://github.com/xusenlinzy/api-for-open-llm/blob/master/README.md)和[FAQ章节](https://github.com/xusenlinzy/api-for-open-llm/blob/master/docs/FAQ.md)并且已在Issue中对问题进行了搜索，没有找到相似问题和解决方案 | I have searched the existing issues / discussions

### 问题类型 | Type of problem

启动命令 | Startup command

### 操作系统 | Operating system

Linux

### 详细描述问题 | Detailed description of the problem

进行如下设置，本地启动会在第一张卡上启动，然后因为显存不足而报
```
PORT=8009

# model related
MODEL_NAME=llama2
MODEL_PATH=meta-llama/Llama-2-13b-chat-hf
PROMPT_NAME=
EMBEDDING_NAME=

# api related
API_PREFIX=/v1

# vllm related
TENSOR_PARALLEL_SIZE=2
ENGINE=vllm
DEVICE=cuda
DEVICE_MAP=auto
GPUS=3,4
NUM_GPUS=2
TRUST_REMOTE_CODE=true
TOKENIZE_MODE=auto
TENSOR_PARALLEL_SIZE=1
DTYPE=half
```

### Dependencies

```
# 请在此处粘贴依赖情况
# Please paste the dependencies here
```

### 运行日志或截图 | Runtime logs or screenshots

<img width="1244" alt="image" src="https://github.com/xusenlinzy/api-for-open-llm/assets/13815598/9bf0997a-dd6d-498d-a2cb-905a72406653">

**Comment by xusenlinzy** [comment]
请问是vllm启动吗，你的TENSOR_PARALLEL_SIZE设置了两次，TENSOR_PARALLEL_SIZE=2就是两张卡

**Comment by Maydaytyh** [comment]
是这里的问题，我没注意到，谢谢！
