### ISSUE TITLE
bug:fix 非docker镜像下，加载模型使用--gpus参数指定无效

### ISSUE THREAD

**Issue by gsy44355** [xusenlinzy/api-for-open-llm#22]
多张显卡的情况下，如果想指定不从0开始的显卡，会指定不成功，原始代码中的os.environment设置实际上是无效的。
作者可以看下我fork的解决方案，如果OK请留言，我把类名调整一下合并起来

https://github.com/gsy44355/api-for-open-llm

**Comment by xusenlinzy** [comment]
确实存在这个问题，麻烦你整合一下哈~

**Comment by xusenlinzy** [comment]
本地环境使用的话，其实可以在运行之前设置 `CUDA_VISIBLE_DEVICES`环境变量，之后再启动模型，这样应该就行了

**Comment by gsy44355** [comment]
> 本地环境使用的话，其实可以在运行之前设置 `CUDA_VISIBLE_DEVICES`环境变量，之后再启动模型，这样应该就行了

确实可以，就是不够优雅hhhhhhhhhhh
