### ISSUE TITLE
React Prompt Observation Stop Words判断逻辑优化

### ISSUE THREAD

**Issue by lzhfe** [xusenlinzy/api-for-open-llm#223]
### 提交前必须检查以下项目 | The following items must be checked before submission

- [X] 请确保使用的是仓库最新代码（git pull），一些问题已被解决和修复。 | Make sure you are using the latest code from the repository (git pull), some issues have already been addressed and fixed.
- [X] 我已阅读[项目文档](https://github.com/xusenlinzy/api-for-open-llm/blob/master/README.md)和[FAQ章节](https://github.com/xusenlinzy/api-for-open-llm/blob/master/docs/FAQ.md)并且已在Issue中对问题进行了搜索，没有找到相似问题和解决方案 | I have searched the existing issues / discussions

### 问题类型 | Type of problem

模型推理和部署 | Model inference and deployment

### 操作系统 | Operating system

None

### 详细描述问题 | Detailed description of the problem

https://github.com/xusenlinzy/api-for-open-llm/blob/e39f0e05504f1d6b2d79862317cda70aad1b2e2e/api/utils/request.py#L78
![image](https://github.com/xusenlinzy/api-for-open-llm/assets/59367267/bf7e571b-23d8-4aba-87bd-c7c4ac959f4f)

遗漏 `request.tools` 判断
`
if chat and ("qwen" in SETTINGS.model_name.lower() and (request.functions or request.tools)):
        request.stop.append("Observation:")
`

**Comment by xusenlinzy** [comment]
最新代码已经修复了
