### ISSUE TITLE
internlm2-chat-7b 部署完停不下来，是不是模板的问题啊

### ISSUE THREAD

**Issue by Tendo33** [xusenlinzy/api-for-open-llm#226]
### 提交前必须检查以下项目 | The following items must be checked before submission

- [X] 请确保使用的是仓库最新代码（git pull），一些问题已被解决和修复。 | Make sure you are using the latest code from the repository (git pull), some issues have already been addressed and fixed.
- [X] 我已阅读[项目文档](https://github.com/xusenlinzy/api-for-open-llm/blob/master/README.md)和[FAQ章节](https://github.com/xusenlinzy/api-for-open-llm/blob/master/docs/FAQ.md)并且已在Issue中对问题进行了搜索，没有找到相似问题和解决方案 | I have searched the existing issues / discussions

### 问题类型 | Type of problem

效果问题 | Effectiveness issues

### 操作系统 | Operating system

Linux

### 详细描述问题 | Detailed description of the problem

使用internlm2 模板部署过之后，模型在输出正常问题之后还是会继续输出直到最大token

### Dependencies

```
# 请在此处粘贴依赖情况
# Please paste the dependencies here
```

### 运行日志或截图 | Runtime logs or screenshots

```
# 请在此处粘贴运行日志
# Please paste the run log here
```

**Comment by xusenlinzy** [comment]
输出内容中有特殊字符吗

**Comment by Tendo33** [comment]
> PROMPT_NAME指定为internlm2 输出内容中有特殊字符吗

就是指定的internlm2
![image](https://github.com/xusenlinzy/api-for-open-llm/assets/86536994/05403354-475b-4b5d-86a7-be2ef60455e2)

**Comment by Tendo33** [comment]
还有orionstar 的template是不是也需要更新啊
这是官网的：
![image](https://github.com/xusenlinzy/api-for-open-llm/assets/86536994/57729677-48dd-4194-a6e6-ff37195e4232)

**Comment by xusenlinzy** [comment]
> @xusenlinzy 还有orionstar 的template是不是也需要更新啊 这是官网的： ![image](https://private-user-images.githubusercontent.com/86536994/299918062-57729677-48dd-4194-a6e6-ff37195e4232.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDYzMjEzMjAsIm5iZiI6MTcwNjMyMTAyMCwicGF0aCI6Ii84NjUzNjk5NC8yOTk5MTgwNjItNTc3Mjk2NzctNDhkZC00MTk0LWE2ZTYtZmYzNzE5NWU0MjMyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTI3VDAyMDM0MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThkNWM1YTIwMDMzODZiYmNiZjM2ZDRhN2M2ZTc4MTExMjNiZTQyMzVlYjc0OGMzNGJjZmI1YzVhN2NhZDhiYmMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.57PdWU7IB5nb5lttZleY4FOVLD4V_bAnvBaUFU3mozs)

是的，需要更新一下
