### ISSUE TITLE
如何加载微调之后的checkpoint呢

### ISSUE THREAD

**Issue by SmallZhangZhang** [xusenlinzy/api-for-open-llm#228]
### 提交前必须检查以下项目 | The following items must be checked before submission

- [X] 请确保使用的是仓库最新代码（git pull），一些问题已被解决和修复。 | Make sure you are using the latest code from the repository (git pull), some issues have already been addressed and fixed.
- [X] 我已阅读[项目文档](https://github.com/xusenlinzy/api-for-open-llm/blob/master/README.md)和[FAQ章节](https://github.com/xusenlinzy/api-for-open-llm/blob/master/docs/FAQ.md)并且已在Issue中对问题进行了搜索，没有找到相似问题和解决方案 | I have searched the existing issues / discussions

### 问题类型 | Type of problem

None

### 操作系统 | Operating system

None

### 详细描述问题 | Detailed description of the problem

```
# 请在此处粘贴运行代码（如没有可删除该代码块）
# Paste the runtime code here (delete the code block if you don't have it)
```
![image](https://github.com/xusenlinzy/api-for-open-llm/assets/71963087/ce8cd5d5-1175-4553-a8a4-55ea05628ba2)

我在.env文件中更改了ADAPTER_MODEL_PATH和USING_PTUNING_V2，也试过只改ADAPTER_MODEL_PATH，但是看起来像是没有用成功。对同一个问题模型的答案是一模一样的。

### Dependencies

```
# 请在此处粘贴依赖情况
# Please paste the dependencies here
```

### 运行日志或截图 | Runtime logs or screenshots

```
# 请在此处粘贴运行日志
# Please paste the run log here
```

**Comment by nolynn** [comment]
这个问题怎么解决的，我也遇到了 @SmallZhangZhang
