### ISSUE TITLE
使用 vllm 推理，在文本末尾缺失信息

### ISSUE THREAD

**Issue by parasol-ry** [xusenlinzy/api-for-open-llm#236]
### 提交前必须检查以下项目 | The following items must be checked before submission

- [X] 请确保使用的是仓库最新代码（git pull），一些问题已被解决和修复。 | Make sure you are using the latest code from the repository (git pull), some issues have already been addressed and fixed.
- [X] 我已阅读[项目文档](https://github.com/xusenlinzy/api-for-open-llm/blob/master/README.md)和[FAQ章节](https://github.com/xusenlinzy/api-for-open-llm/blob/master/docs/FAQ.md)并且已在Issue中对问题进行了搜索，没有找到相似问题和解决方案 | I have searched the existing issues / discussions

### 问题类型 | Type of problem

效果问题 | Effectiveness issues

### 操作系统 | Operating system

Linux

### 详细描述问题 | Detailed description of the problem

.env 如下所示
```
PORT=9993

# model related
MODEL_NAME=qwen
MODEL_PATH=/data//Model/outputs
PROMPT_NAME=
EMBEDDING_NAME=

# api related
API_PREFIX=/v1

LOAD_IN_4BIT=true

GPUS=2
NUM_GPUs=1

# vllm related
ENGINE=vllm
TRUST_REMOTE_CODE=true
TOKENIZE_MODE=auto
TENSOR_PARALLEL_SIZE=1
DTYPE=half
```

### Dependencies

```
# 请在此处粘贴依赖情况
# Please paste the dependencies here
```
在用 vllm 长文本推理时，生成的内容明显不完整，不用 vllm，或者用官方的 vllm 启动则不会出现此问题

### 运行日志或截图 | Runtime logs or screenshots

```
# 请在此处粘贴运行日志
# Please paste the run log here
```
<img width="559" alt="image" src="https://github.com/xusenlinzy/api-for-open-llm/assets/75149667/08f15eb7-bb0d-424a-ac40-578f4c2bdbd6">
<img width="444" alt="image" src="https://github.com/xusenlinzy/api-for-open-llm/assets/75149667/9f772437-7dc2-4f26-abd9-7c66aaaf0e52">
<img width="310" alt="image" src="https://github.com/xusenlinzy/api-for-open-llm/assets/75149667/ce007054-95b2-4045-9ef1-d831da1bfe29">

**Comment by parasol-ry** [comment]
而且 我发现一般会少最后 10 个字左右，如果生成的部分文本较短，则会直接显示空，我可以提供微调的模型和部分有问题的数据，希望大佬可以解决一下此问题

**Comment by xusenlinzy** [comment]
请问你使用的是qwen1.5吗

**Comment by parasol-ry** [comment]
是之前版本的 qwen，1.8B 微调过的

**Comment by xusenlinzy** [comment]
![image](https://github.com/xusenlinzy/api-for-open-llm/assets/111472355/1a0918a0-4181-441a-ad73-4fef3e78b042)

**Comment by dusens** [comment]
我也遇到这种情况了用的是sqlcoder-7b-2 也是截断了

**Comment by parasol-ry** [comment]
直接用官方的 vllm 推理命令就没事了

**Comment by wangzan** [comment]
我也遇到了，尾巴截断了，baichuan2-13B基座
![image](https://github.com/xusenlinzy/api-for-open-llm/assets/1593169/a81fc2c8-bb02-44d7-b4e0-bb4fd4ee7df9)

**Comment by wangzan** [comment]
> 我也遇到了，尾巴截断了，baichuan2-13B基座 ![image](https://private-user-images.githubusercontent.com/1593169/326235441-a81fc2c8-bb02-44d7-b4e0-bb4fd4ee7df9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQyODc1MTgsIm5iZiI6MTcxNDI4NzIxOCwicGF0aCI6Ii8xNTkzMTY5LzMyNjIzNTQ0MS1hODFmYzJjOC1iYjAyLTQ0ZDctYjRlMC1iYjRmZDRlZTdkZjkucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDQyOCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA0MjhUMDY1MzM4WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MDJhM2E2ZDMzZjM1NWM2ZDAxY2MzNzNjY2I3ODllNTdlODk4NDk4NGVhNjliMmIzNmRjNWY1NjYwOGE4MWFlNCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.TLKSb8_CghoL3xDCIQHmLxAG9ZaxqEV0EyYTcq0HcAU)

我这个问题已经解决，stream输出过程中，最后一个chunk输出为空。最新源码中修改可解决。
diff --git a/api/vllm_routes/chat.py b/api/vllm_routes/chat.py
index a13e782..26a05a2 100644
--- a/api/vllm_routes/chat.py
+++ b/api/vllm_routes/chat.py
@@ -278,7 +278,7 @@ async def create_chat_completion_stream(
                 
                 choice = ChunkChoice(
                     index=i,
-                    delta=delta or ChoiceDelta(),
+                    delta=delta or ChoiceDelta(content=delta_text),
                     finish_reason=finish_reason,
                     logprobs=None,
                 )
@xusenlinzy @parasol-ry

**Comment by wangzan** [comment]
我这个问题已经解决，stream输出过程中，最后一个chunk输出为空。最新源码中修改可解决。
```git
diff --git a/api/vllm_routes/chat.py b/api/vllm_routes/chat.py
index a13e782..573c3be 100644
--- a/api/vllm_routes/chat.py
+++ b/api/vllm_routes/chat.py
@@ -278,7 +278,7 @@ async def create_chat_completion_stream(
                 
                 choice = ChunkChoice(
                     index=i,
-                    delta=delta or ChoiceDelta(),
+                    delta=delta or ChoiceDelta(content=delta_text),
                     finish_reason=finish_reason,
                     logprobs=None,
                 )
```

@xusenlinzy @parasol-ry
