### ISSUE TITLE
关于多个LLM的同时部署的问题

### ISSUE THREAD

**Issue by myweihp** [xusenlinzy/api-for-open-llm#24]
Hi，我想在自己的服务器上同时部署多个开源LLM（比如ChatGLM2-6B、Baichuan-13B等），怎样能够使api里面的“model”字段生效，可以在同一个api_base上支持不同的模型选择？

**Comment by myweihp** [comment]
好的！谢谢您的回复！

**Comment by FrankWhh** [comment]
大佬，按照chatgpt.py文件的写法，不能异步转发吗？
