### ISSUE TITLE
Qwen1.5 提示模板缺少默认 system message

### ISSUE THREAD

**Issue by liuyanyi** [xusenlinzy/api-for-open-llm#240]
### 提交前必须检查以下项目 | The following items must be checked before submission

- [X] 请确保使用的是仓库最新代码（git pull），一些问题已被解决和修复。 | Make sure you are using the latest code from the repository (git pull), some issues have already been addressed and fixed.
- [X] 我已阅读[项目文档](https://github.com/xusenlinzy/api-for-open-llm/blob/master/README.md)和[FAQ章节](https://github.com/xusenlinzy/api-for-open-llm/blob/master/docs/FAQ.md)并且已在Issue中对问题进行了搜索，没有找到相似问题和解决方案 | I have searched the existing issues / discussions

### 问题类型 | Type of problem

其他问题 | Other issues

### 操作系统 | Operating system

None

### 详细描述问题 | Detailed description of the problem

使用 qwen tokenizer 的 chat_template 和 api-for-open-llm 中的 template, 如果messages中没有system信息，前面会缺一个system提示

``` python
if __name__ == '__main__':
    tokenizer = AutoTokenizer.from_pretrained("/large-storage/model/Qwen1.5/Qwen1.5-72B-Chat/")


    chat = [
        {"role": "user", "content": "Hello, how are you?"}
    ]

    template = get_prompt_adapter(prompt_name="qwen2")
    messages = template.postprocess_messages(chat)


    text_ori = tokenizer.apply_chat_template(
        messages,
        tokenize=False,
        add_generation_prompt=True
    )

    text_api = template.apply_chat_template(messages, add_generation_prompt=True)

    print("========== text_ori ==========")
    print(text_ori)

    print("========== text_api ==========")
    print(text_api)
```

输出：
```bash
========== text_ori ==========
<|im_start|>system
You are a helpful assistant<|im_end|>
<|im_start|>user
Hello, how are you?<|im_end|>
<|im_start|>assistant

========== text_api ==========
<|im_start|>user
Hello, how are you?<|im_end|>
<|im_start|>assistant

```

参考原始 qwen 的分词器模板，里面有这样一段：
```
{% if loop.first and messages[0]['role'] != 'system' %}{{ '<|im_start|>system\nYou are a helpful assistant<|im_end|>\n' }}{% endif %}
```

### Dependencies

```
# 请在此处粘贴依赖情况
# Please paste the dependencies here
```

### 运行日志或截图 | Runtime logs or screenshots

```
# 请在此处粘贴运行日志
# Please paste the run log here
```

**Comment by xusenlinzy** [comment]
已经更新了
