### ISSUE TITLE
💡 [REQUEST] - <请问可以支持一下Xai新发布的Grok-1模型吗>

### ISSUE THREAD

**Issue by Hapluckyy** [xusenlinzy/api-for-open-llm#248]
### 起始日期 | Start Date

3/19/2024

### 实现PR | Implementation PR

https://github.com/xai-org/grok-1

### 相关Issues | Reference Issues

https://github.com/xai-org/grok-1

### 摘要 | Summary

https://github.com/xai-org/grok-1

### 基本示例 | Basic Example

https://github.com/xai-org/grok-1

### 缺陷 | Drawbacks

https://github.com/xai-org/grok-1

### 未解决问题 | Unresolved questions

https://github.com/xai-org/grok-1

**Comment by Tendo33** [comment]
MiniCPM支持吗
