### ISSUE TITLE
docker打包报错：ERROR: failed to solve: process "/bin/sh -c pip config set global.index-url https://pypi.tuna.tsinghua.edu.cn/simple &&     pip install bitsandbytes --upgrade &&     pip install vllm==0.3.3 &&     pip install --no-cache-dir -r /workspace/requirements.txt &&     pip uninstall transformer-engine -y" did not complete successfully: exit code: 1

### ISSUE THREAD

**Issue by syusama** [xusenlinzy/api-for-open-llm#249]
### 提交前必须检查以下项目 | The following items must be checked before submission

- [X] 请确保使用的是仓库最新代码（git pull），一些问题已被解决和修复。 | Make sure you are using the latest code from the repository (git pull), some issues have already been addressed and fixed.
- [X] 我已阅读[项目文档](https://github.com/xusenlinzy/api-for-open-llm/blob/master/README.md)和[FAQ章节](https://github.com/xusenlinzy/api-for-open-llm/blob/master/docs/FAQ.md)并且已在Issue中对问题进行了搜索，没有找到相似问题和解决方案 | I have searched the existing issues / discussions

### 问题类型 | Type of problem

安装环境 | Installation environment

### 操作系统 | Operating system

Linux

### 详细描述问题 | Detailed description of the problem

```
# 请在此处粘贴运行代码（如没有可删除该代码块）
# Paste the runtime code here (delete the code block if you don't have it)
docker build -f docker/Dockerfile.vllm -t llm-api:vllm .
```
docker打包报错
ERROR: failed to solve: process "/bin/sh -c pip config set global.index-url https://pypi.tuna.tsinghua.edu.cn/simple &&     pip install bitsandbytes --upgrade &&     pip install vllm==0.3.3 &&     pip install --no-cache-dir -r /workspace/requirements.txt &&     pip uninstall transformer-engine -y" did not complete successfully: exit code: 1

### Dependencies

```
# 请在此处粘贴依赖情况
# Please paste the dependencies here
```

### 运行日志或截图 | Runtime logs or screenshots
![微信截图_20240321155204](https://github.com/xusenlinzy/api-for-open-llm/assets/16223129/63a317fe-2ab1-4207-85c7-69e49dbd8c25)

**Comment by oo90909** [comment]
我也遇到了，解决了吗

**Comment by syusama** [comment]
> 我也遇到了，解决了吗

没有啊，没人回复
