### ISSUE TITLE
[Bug] vLLM 镜像中Pydantic版本冲突

### ISSUE THREAD

**Issue by liuyanyi** [xusenlinzy/api-for-open-llm#251]
### 提交前必须检查以下项目 | The following items must be checked before submission

- [X] 请确保使用的是仓库最新代码（git pull），一些问题已被解决和修复。 | Make sure you are using the latest code from the repository (git pull), some issues have already been addressed and fixed.
- [X] 我已阅读[项目文档](https://github.com/xusenlinzy/api-for-open-llm/blob/master/README.md)和[FAQ章节](https://github.com/xusenlinzy/api-for-open-llm/blob/master/docs/FAQ.md)并且已在Issue中对问题进行了搜索，没有找到相似问题和解决方案 | I have searched the existing issues / discussions

### 问题类型 | Type of problem

安装环境 | Installation environment

### 操作系统 | Operating system

Linux

### 详细描述问题 | Detailed description of the problem

https://github.com/xusenlinzy/api-for-open-llm/blob/9d1ff578a43619a505d8ead9147557cd98bc8e46/docker/Dockerfile.vllm#L9-L10

当前的 Dockerfile.vllm 中的安装顺序是先安装vLLM再安装requirements，项目中的requirements固定了pydantic版本为1.10.13，与 vLLM 中 pydantic>2 冲突，启动时会报错，#250 也是相似的issue

项目代码似乎已经兼容了pydantic 1 和 2 , 是否可以考虑放宽依赖版本到 `pydantic>=1.10.13`

### 运行日志或截图 | Runtime logs or screenshots

```
# 请在此处粘贴运行日志
# Please paste the run log here
```

**Comment by xusenlinzy** [comment]
可以的

**Comment by syusama** [comment]
我当时也遇到这个问题，搞了我一个周末
