### ISSUE TITLE
用langchain调用bge时报错

### ISSUE THREAD

**Issue by Qoooooooooooo** [xusenlinzy/api-for-open-llm#252]
### 提交前必须检查以下项目 | The following items must be checked before submission

- [X] 请确保使用的是仓库最新代码（git pull），一些问题已被解决和修复。 | Make sure you are using the latest code from the repository (git pull), some issues have already been addressed and fixed.
- [X] 我已阅读[项目文档](https://github.com/xusenlinzy/api-for-open-llm/blob/master/README.md)和[FAQ章节](https://github.com/xusenlinzy/api-for-open-llm/blob/master/docs/FAQ.md)并且已在Issue中对问题进行了搜索，没有找到相似问题和解决方案 | I have searched the existing issues / discussions

### 问题类型 | Type of problem

其他问题 | Other issues

### 操作系统 | Operating system

Windows

### 详细描述问题 | Detailed description of the problem

```
    model = "bge-large-zh"
    # model = "text-embedding-ada-002"

    embeddings = OpenAIEmbeddings(model=model, openai_api_key=openai_api_key, openai_api_base=openai_api_base)
```
    其中嵌入为bge-large-zh
    model由bge-large-zh换成text-embedding-ada-002就没问题

**Comment by Qoooooooooooo** [comment]
Warning: model not found. Using cl100k_base encoding.

**Comment by darvsum** [comment]
你去掉model=model试试
    embeddings = OpenAIEmbeddings(openai_api_key=openai_api_key, openai_api_base=openai_api_base)
