### ISSUE TITLE
💡 [REQUEST] - <title>vllm支持Qwen1.5-14B-Chat-AWQ和Qwen1.5-14B-Chat-GPTQ-int4吗

### ISSUE THREAD

**Issue by dickpy** [xusenlinzy/api-for-open-llm#253]
### 摘要 | Summary

vllm支持Qwen1.5-14B-Chat-AWQ和Qwen1.5-14B-Chat-GPTQ-int4吗

### 基本示例 | Basic Example

无

### 缺陷 | Drawbacks

无

### 未解决问题 | Unresolved questions

无

**Comment by xusenlinzy** [comment]
支持的



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2024年03月27日 17:36 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***> |
| 主题 | [xusenlinzy/api-for-open-llm] 💡 [REQUEST] - <title>vllm支持Qwen1.5-14B-Chat-AWQ和Qwen1.5-14B-Chat-GPTQ-int4吗 (Issue #253) |

起始日期 | Start Date

No response

实现PR | Implementation PR

No response

相关Issues | Reference Issues

No response

摘要 | Summary

vllm支持Qwen1.5-14B-Chat-AWQ和Qwen1.5-14B-Chat-GPTQ-int4吗

基本示例 | Basic Example

无

缺陷 | Drawbacks

无

未解决问题 | Unresolved questions

无

**Comment by dickpy** [comment]
好的谢谢，是不是.env的配置就按照default里面的来，在vllm里面没看到那些模型，还以为不通用
