### ISSUE TITLE
我想使用的模型不在模型支持列表，是否说明无法使用此项目生成openai的接口

### ISSUE THREAD

**Issue by xiaoma444** [xusenlinzy/api-for-open-llm#258]
### 起始日期 | Start Date

2024/4.12

### 实现PR | Implementation PR

编辑生成openai格式接口宫langchai-chatchat调用

### 相关Issues | Reference Issues

无

### 摘要 | Summary

我想使用电信公司大模型Telechat

### 基本示例 | Basic Example

无

### 缺陷 | Drawbacks

无

### 未解决问题 | Unresolved questions

无

**Comment by VastOcean-Yang** [comment]
同问

**Comment by xusenlinzy** [comment]
模型支持列表很久没更新了。。请问你想使用的是哪个模型
