### ISSUE TITLE
升级后报错

### ISSUE THREAD

**Issue by darvsum** [xusenlinzy/api-for-open-llm#264]
### 提交前必须检查以下项目 | The following items must be checked before submission

- [X] 请确保使用的是仓库最新代码（git pull），一些问题已被解决和修复。 | Make sure you are using the latest code from the repository (git pull), some issues have already been addressed and fixed.
- [X] 我已阅读[项目文档](https://github.com/xusenlinzy/api-for-open-llm/blob/master/README.md)和[FAQ章节](https://github.com/xusenlinzy/api-for-open-llm/blob/master/docs/FAQ.md)并且已在Issue中对问题进行了搜索，没有找到相似问题和解决方案 | I have searched the existing issues / discussions

### 问题类型 | Type of problem

启动命令 | Startup command

### 操作系统 | Operating system

Linux

### 详细描述问题 | Detailed description of the problem

```
Traceback (most recent call last):
  File "/tools/codes/llm/server.py", line 2, in <module>
    from api.models import (
  File "/tools/codes/llm/api/models.py", line 192, in <module>
    EMBEDDING_MODEL, RERANK_MODEL = create_rag_models()
  File "/tools/codes/llm/api/models.py", line 48, in create_rag_models
    RAGEmbedding(SETTINGS.embedding_name, SETTINGS.embedding_device)
  File "/tools/codes/llm/api/rag/models/embedding.py", line 34, in __init__
    self.client = SentenceTransformer(
TypeError: SentenceTransformer.__init__() got an unexpected keyword argument 'trust_remote_code'

```

### Dependencies

```
# 请在此处粘贴依赖情况
# Please paste the dependencies here
```

### 运行日志或截图 | Runtime logs or screenshots

```
# 请在此处粘贴运行日志
# Please paste the run log here
```

**Comment by xusenlinzy** [comment]
升级一下版本 pip install sentence-transformers -U
