### ISSUE TITLE
llama3提问后回答不停止

### ISSUE THREAD

**Issue by gptcod** [xusenlinzy/api-for-open-llm#266]
### 提交前必须检查以下项目 | The following items must be checked before submission

- [X] 请确保使用的是仓库最新代码（git pull），一些问题已被解决和修复。 | Make sure you are using the latest code from the repository (git pull), some issues have already been addressed and fixed.
- [X] 我已阅读[项目文档](https://github.com/xusenlinzy/api-for-open-llm/blob/master/README.md)和[FAQ章节](https://github.com/xusenlinzy/api-for-open-llm/blob/master/docs/FAQ.md)并且已在Issue中对问题进行了搜索，没有找到相似问题和解决方案 | I have searched the existing issues / discussions

### 问题类型 | Type of problem

效果问题 | Effectiveness issues

### 操作系统 | Operating system

Linux

### 详细描述问题 | Detailed description of the problem

python server.py后再使用streamlit启动前端界面，不管是使用中文还是英文提问，都是回答不停止。

### Dependencies

```
# 请在此处粘贴依赖情况
# Please paste the dependencies here
```

### 运行日志或截图 | Runtime logs or screenshots

![image](https://github.com/xusenlinzy/api-for-open-llm/assets/24822076/6c5aba94-67b9-4457-a902-a9c136a932d1)

**Comment by xusenlinzy** [comment]
更新一下代码试试

**Comment by claudegpt** [comment]
> 更新一下代码试试

可以了，请您再略微修改下代码："token_ids" [128001, 128009]，中间少了个冒号。
