### ISSUE TITLE
请求增加Aquila模型 | Request for adding Aquila Family

### ISSUE THREAD

**Issue by myweihp** [xusenlinzy/api-for-open-llm#27]
Hi, 再次感谢你的工作。请问可以支持[AquilaChat-7B](https://huggingface.co/BAAI/AquilaChat-7B)和[Aquila-7B](https://huggingface.co/BAAI/Aquila-7B)两个模型吗？或者，如果我手动添加的话，如何找到该模型合适的system_prompt、user_prompt、assistant_prompt以及stop参数用于构建api/prompt.py中需要的PromptAdapter呢？

**Comment by myweihp** [comment]
我好像自己找到了答案。按照[cyg_conversation.py](https://github.com/FlagAI-Open/FlagAI/blob/6f5d412558d73d5d12b8b55d56f51942f80252c1/examples/Aquila/Aquila-chat/cyg_conversation.py)文件的描述以及[hf](https://huggingface.co/BAAI/AquilaChat-7B)上述参数**可能**是：
system_prompt = "A chat between a curious human and an artificial intelligence assistant. The assistant gives helpful, detailed, and polite answers to the human's questions."
user_prompt = "Human: {}###Assistant:"
assistant_prompt = "{}\n</s>"
stop = ["[UNK]", "</s>", "###"]
仅供参考。

**Comment by xusenlinzy** [comment]
> 我好像自己找到了答案。按照[cyg_conversation.py](https://github.com/FlagAI-Open/FlagAI/blob/6f5d412558d73d5d12b8b55d56f51942f80252c1/examples/Aquila/Aquila-chat/cyg_conversation.py)文件的描述以及[hf](https://huggingface.co/BAAI/AquilaChat-7B)的测试脚本，上述参数**可能**是： system_prompt = "A chat between a curious human and an artificial intelligence assistant. The assistant gives helpful, detailed, and polite answers to the human's questions." user_prompt = "Human: {}###Assistant: " assistant_prompt = "{}\n" stop = ["[UNK]", "</s>", "###"] 仅供参考。

根据项目信息应该是这样的，我把相关的代码整理了一下，你可以测试一下哈~

**Comment by myweihp** [comment]
经测试是没有问题的🤭
