### ISSUE TITLE
dcoker 部署 vllm 出现 404 Not Found

### ISSUE THREAD

**Issue by skyliwq** [xusenlinzy/api-for-open-llm#271]
docker 部署 vllm qwen模型 启动成功，调用出现 "POST /v1/chat/completions HTTP/1.1" 404 Not Found 什么原因无法解决，请大神帮帮忙.

http://127.0.0.1:7891/docs 显示 No operations defined in spec!

2024-05-09 07:00:03 INFO:     Started server process [1]
2024-05-09 07:00:03 INFO:     Waiting for application startup.
2024-05-09 07:00:03 INFO:     Application startup complete.
2024-05-09 07:00:03 INFO:     Uvicorn running on http://0.0.0.0:8000 (Press CTRL+C to quit)
2024-05-09 07:00:04 INFO:     172.16.1.1:57384 - "POST /v1/chat/completions HTTP/1.1" 404 Not Found

**Comment by Tendo33** [comment]
发一下，请求的脚本

**Comment by skyliwq** [comment]
client = OpenAI(
    api_key="EMPTY",
    base_url="http://192.168.20.44:7861/v1/",
)


# List models API
models = client.models.list()
print(models.model_dump())


# Chat completion API
chat_completion = client.chat.completions.create(
    messages=[
        {
            "role": "user",
            "content": "感冒了怎么办",
        }
    ],
    model="gpt-3.5-turbo",
)
print(chat_completion)


stream = client.chat.completions.create(
    messages=[
        {
            "role": "user",
            "content": "感冒了怎么办",
        }
    ],
    model="gpt-3.5-turbo",
    stream=True,
)
for part in stream:
    print(part.choices[0].delta.content or "", end="", flush=True)

请求超时错误

**Comment by skyliwq** [comment]
> 发一下，请求的脚本

我是用psotman 请求的 显示
{
    "detail": "Not Found"
}
用官方提供的 tests chat.py 也显示错误

docker-compose
 vllmapiserver:
    image: llm-api:vllm
    command: python api/server.py
    ulimits:
      stack: 67108864
      memlock: -1
    environment:
      - PORT=8000
      - MODEL_NAME=qwen
      - MODEL_PATH=checkpoints/qwen-7b-chat
      - EMBEDDING_NAME=checkpoints/text2vec-large-chinese
    volumes:
      - E:\\docker/llm2-chat:/workspace
      # model path need to be specified if not in pwd
#      - /data/checkpoints:/workspace/checkpoints
    env_file:
      - .env.vllm.example
    ports:
      - "7891:8000"
    restart: always
    networks:
      - vllmapinet
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: ['0']  # 指定gpu
              capabilities: [gpu]

networks:
  vllmapinet:
    driver: bridge
    name: vllmapinet

**Comment by Tendo33** [comment]
> > 发一下，请求的脚本
> 
> 我是用psotman 请求的 显示 { "detail": "Not Found" } 用官方提供的 tests chat.py 也显示错误 部署用的官方docke-compose 文件 配置都没问题

请求的地址有加 /v1 吗？
如果不行可以去部署地址的 /docs 看一下fastapi 接口，可以直接在线起到跟 psotman 一样的效果

**Comment by skyliwq** [comment]
> Reference i

http://127.0.0.1:7891/docs 显示 No operations defined in spec!

**Comment by skyliwq** [comment]
> > Reference i
> 请求参数 部署参数都对的 核实了很多遍
> http://127.0.0.1:7891/docs 显示 No operations defined in spec!

**Comment by skyliwq** [comment]
配置为 ENGINE=vllm 报错 ENGINE=default 正常

**Comment by xusenlinzy** [comment]
那应该是vllm安装没有成功

**Comment by skyliwq** [comment]
> 那应该是vllm安装没有成功
直接docker部署的 如何从新安装，大神指点

**Comment by Tendo33** [comment]
你 docker build 镜像的时候用的哪个docker File ？换成 vllm 那个

**Comment by skyliwq** [comment]
> vllm

换的是这个

**Comment by JadynWong** [comment]
同样的问题, 最新的代码, 使用docker-compose vllm部署, GPU没有任何占用, 也不报错. 请求404

**Comment by JadynWong** [comment]
![Clip_2024-05-21_19-28-39](https://github.com/xusenlinzy/api-for-open-llm/assets/13699353/23b9595a-564c-43ad-bac1-c8cb1cc18622)

https://github.com/xusenlinzy/api-for-open-llm/blob/e46e48056a02ffbd90e0dfe4bc2f803df1e7e4e1/api/models.py#L100 
此处加了一行打印异常日志

今天下午才拉取的代码, 重新构建的镜像, 期间没有任何报错
```
docker build -f docker/Dockerfile.vllm -t llm-api:vllm .
```

**Comment by liho00** [comment]
遇到一样的问题，看来是vllm的问题？
