### ISSUE TITLE
我现在部署了很多模型，有没有一个webui 界面让我来统一调用部署的模型进行推理

### ISSUE THREAD

**Issue by Tendo33** [xusenlinzy/api-for-open-llm#278]
### 摘要 | Summary

可以将部署的模型统一在webui 进行管理和推理，只需要填写模型名和本地的api-base 就可以调用到

### 基本示例 | Basic Example

None

### 缺陷 | Drawbacks

streamlit-demo 只能选择一个模型进行对话

**Comment by xusenlinzy** [comment]
更新一下代码试试
![image](https://github.com/xusenlinzy/api-for-open-llm/assets/111472355/37219425-cae3-462c-8ca2-133095f17331)

**Comment by Tendo33** [comment]
GLM4 出了，template 可能要更新一下

**Comment by xusenlinzy** [comment]
已经更新了
