### ISSUE TITLE
添加知识库后报错

### ISSUE THREAD

**Issue by whh1009** [xusenlinzy/api-for-open-llm#28]
环境：本地部署
已经可以通过web_demo访问页面并进行聊天，点击“知识库”上传了一个txt，并添加到知识库后

![image](https://github.com/xusenlinzy/api-for-open-llm/assets/10083033/fa8528c7-3894-43fc-9f0d-15f59920d857)

api.py  控制台报错：
![image](https://github.com/xusenlinzy/api-for-open-llm/assets/10083033/4d193c66-485f-4a3b-a685-2d055fc29eb1)

web_demo.py 控制台报错：
![image](https://github.com/xusenlinzy/api-for-open-llm/assets/10083033/0ea50f95-8497-4a80-b3b8-a90a19df1dfe)

大佬们帮忙看看

**Comment by xusenlinzy** [comment]
我已经更新了代码，您可以试试行不行

**Comment by whh1009** [comment]
可以了，可以正常使用了！
默认我使用Baichuan的模型替换了GLM，

**Comment by xusenlinzy** [comment]
是的，如果有多个模型想测试的话，在模型框配置好模型名称和对应的api_base，点击添加模型之后就可以选择添加的模型了
