### ISSUE TITLE
glm4用default和vllm方式部署，都不能正常的停止，流式和非流式都有同样的问题，不知道其他朋友是否遇到同样的问题

### ISSUE THREAD

**Issue by LiuDQ-wm** [xusenlinzy/api-for-open-llm#281]
### 提交前必须检查以下项目 | The following items must be checked before submission

- [X] 请确保使用的是仓库最新代码（git pull），一些问题已被解决和修复。 | Make sure you are using the latest code from the repository (git pull), some issues have already been addressed and fixed.
- [X] 我已阅读[项目文档](https://github.com/xusenlinzy/api-for-open-llm/blob/master/README.md)和[FAQ章节](https://github.com/xusenlinzy/api-for-open-llm/blob/master/docs/FAQ.md)并且已在Issue中对问题进行了搜索，没有找到相似问题和解决方案 | I have searched the existing issues / discussions

### 问题类型 | Type of problem

模型推理和部署 | Model inference and deployment

### 操作系统 | Operating system

Linux

### 详细描述问题 | Detailed description of the problem

```
# 请在此处粘贴运行代码（如没有可删除该代码块）
# Paste the runtime code here (delete the code block if you don't have it)
```

### Dependencies

```
# 请在此处粘贴依赖情况
# Please paste the dependencies here
```

### 运行日志或截图 | Runtime logs or screenshots

```
# 请在此处粘贴运行日志
# Please paste the run log here
```

**Comment by xusenlinzy** [comment]
我这里测试glm4使用vllm是正常的，default方式暂时还没有更新

**Comment by LiuDQ-wm** [comment]
> 我这里测试glm4使用vllm是正常的，default方式暂时还没有更新，有示例吗，我测试一下

![Uploading 1717641933668.png…]()

**Comment by LiuDQ-wm** [comment]
![微信图片_20240606104716](https://github.com/xusenlinzy/api-for-open-llm/assets/151293455/15e06040-81b4-43b0-86db-a1c6800e1c5f)

**Comment by LiuDQ-wm** [comment]
> 我这里测试glm4使用vllm是正常的，default方式暂时还没有更新，有示例吗，我测试一下

vllm是0.4.2的版本吗？vllm我们测试的还是0.4.1的版本

**Comment by xusenlinzy** [comment]
看返回内容应该是对话模板用错了，
![Uploading image.png…]()
这两个环境变量确认是上面这样吗

**Comment by LiuDQ-wm** [comment]
![微信图片_20240606110210](https://github.com/xusenlinzy/api-for-open-llm/assets/151293455/7b533b34-a30f-4089-803c-0fc643e8622a)
环境变量应该是正确的，刚特意加上 PROMPT_NAME=chatglm4，还是有同样的问题

**Comment by xusenlinzy** [comment]
![image](https://github.com/xusenlinzy/api-for-open-llm/assets/111472355/623437b5-e0c4-4d45-80f7-1860b84f2047)
![Uploading image.png…]()
我测试是正常，难道是没有更新代码吗

**Comment by LiuDQ-wm** [comment]
> ![image](https://private-user-images.githubusercontent.com/111472355/337086910-623437b5-e0c4-4d45-80f7-1860b84f2047.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc2NDQ4ODIsIm5iZiI6MTcxNzY0NDU4MiwicGF0aCI6Ii8xMTE0NzIzNTUvMzM3MDg2OTEwLTYyMzQzN2I1LWUwYzQtNGQ0NS04MGY3LTE4NjBiODRmMjA0Ny5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjA2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYwNlQwMzI5NDJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yMGJkZDg1OGIzNmY2NmExNWY3MDRmNzczNzE3MDM3ZjM3NWE1NjZiNzJhZDJjNDQwYjdhOGI0MmYyZmIwMjdmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.goY9K7H6pZ6N_b90l2iKDBrOizS9BQot7EeokuXFts8) ![image](https://private-user-images.githubusercontent.com/111472355/337087314-6c0e44b7-f978-49e5-b092-29c352c0247e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc2NDQ4ODIsIm5iZiI6MTcxNzY0NDU4MiwicGF0aCI6Ii8xMTE0NzIzNTUvMzM3MDg3MzE0LTZjMGU0NGI3LWY5NzgtNDllNS1iMDkyLTI5YzM1MmMwMjQ3ZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjA2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYwNlQwMzI5NDJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00NzM5ZWVhNjAwYTY2YmQwODRmZWI2ZmNkNWNjMGU0OTU4ODU5Zjk2Yjg3YTczMTI3MmNhOTA4MzU5NjQ2ZTIxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.iaYm3I6AxN0HfRvhZTj7HSPzmbFfgkdfq43FTmaM1oA) 我测试是正常，难道是没有更新代码吗

这里不是用的vllm引擎吗？不是default方式哦

**Comment by xusenlinzy** [comment]
是的

> 我这里测试glm4使用vllm是正常的，default方式暂时还没有更新，有示例吗，我测试一下

**Comment by xusenlinzy** [comment]
刚刚更新了，已经支持default模式的推理

**Comment by LiuDQ-wm** [comment]
好的，感谢，我更新一下试试

**Comment by Tendo33** [comment]
只要chatglm4字段在MODEL_NAME里面就可以是吗？只能小写？

**Comment by xusenlinzy** [comment]
意思是使用其他对话模板吗

**Comment by Tendo33** [comment]
> 意思是使用其他对话模板吗，如果是在chat模型的基础上微调，最好还是保持glm4自身的对话模板

我现在训练base 一般用chatml模板 ，但是我看代码如果MODEL_NAME里面带chatglm4之间就应用glm4自身的对话模板了。这样是不是我就只能在改模型名了啊

**Comment by xusenlinzy** [comment]
现在的代码是的，你可以试试MODEL_NAME=glm4, PROMPT_NAME=chatml
