### ISSUE TITLE
docker无法下载image

### ISSUE THREAD

**Issue by xqinshan** [xusenlinzy/api-for-open-llm#284]
### 提交前必须检查以下项目 | The following items must be checked before submission

- [X] 请确保使用的是仓库最新代码（git pull），一些问题已被解决和修复。 | Make sure you are using the latest code from the repository (git pull), some issues have already been addressed and fixed.
- [X] 我已阅读[项目文档](https://github.com/xusenlinzy/api-for-open-llm/blob/master/README.md)和[FAQ章节](https://github.com/xusenlinzy/api-for-open-llm/blob/master/docs/FAQ.md)并且已在Issue中对问题进行了搜索，没有找到相似问题和解决方案 | I have searched the existing issues / discussions

### 问题类型 | Type of problem

安装环境 | Installation environment

### 操作系统 | Operating system

Windows

### 详细描述问题 | Detailed description of the problem

希望在docker运行，但
docker pull xusenlinzy/llm-api
Using default tag: latest
latest: Pulling from xusenlinzy/llm-api
failed to copy: httpReadSeeker: failed open: unexpected status code https://0y3buaaq.mirror.aliyuncs.com/v2/xusenlinzy/llm-api/blobs/sha256:a2882b64d80fccfe731d1602e49f35d93860dafb7a0fcbe6d5978876ac7cb399?ns=docker.io: 500 Internal Server Error - Server message: unknown: unknown error
试了几个代理都不行，怎样获得 xusenlinzy/llm-api:pytorch?

### Dependencies

```
# 请在此处粘贴依赖情况
# Please paste the dependencies here
```

### 运行日志或截图 | Runtime logs or screenshots

```
# 请在此处粘贴运行日志
# Please paste the run log here
```

**Comment by xusenlinzy** [comment]
需要自己构建的哈~
在项目目录下执行
```shell
docker build -t llm-api:vllm -f docker/Dockerfile.vllm .
```
