### ISSUE TITLE
ModuleNotFoundError: No module named 'api'

### ISSUE THREAD

**Issue by shenli0502** [xusenlinzy/api-for-open-llm#3]
执行：
python api/app.py --port 8090 --allow-credentials --model_path D:\Project\ChatGLM\chatglm-6b-int4 --embedding_name GanymedeNil/text2vec-large-chinese

返回：
Traceback (most recent call last):
  File "D:\Project\ChatGLM\api-for-open-llm-master\api\app.py", line 13, in <module>
    from api.constants import ErrorCode
ModuleNotFoundError: No module named 'api'

麻烦帮忙看一下是什么原因呢~谢谢~

**Comment by xusenlinzy** [comment]
@shenli0502 应该是python环境的问题，你可以执行命令前试一下：
```
export PYTHONPATH=.
```

**Comment by shenli0502** [comment]
可能因为我是在windows上用。我把api.去掉就好了。
然后发现windows好像用不了bitsandbytes
