### ISSUE TITLE
对baichuan 13b chat的代码存在疑问。

### ISSUE THREAD

**Issue by askintution** [xusenlinzy/api-for-open-llm#31]
我看到代码中api/prompt_adapter.py‎中对baichuan的支持中，写着

user_prompt = "<reserved_102> {}<reserved_103> "
assistant_prompt = "{}</s>"
stop = ["<reserved_102>", "<reserved_103>"]

但我看huggingface中generation_config.json中配置的user token id和assistant token id跟这个并不一致。

{
  "pad_token_id": 0,
  "bos_token_id": 1,
  "eos_token_id": 2,
  "user_token_id": 195,
  "assistant_token_id": 196,
  "max_new_tokens": 2048,
  "temperature": 0.3,
  "top_k": 5,
  "top_p": 0.85,
  "repetition_penalty": 1.1,
  "do_sample": true,
  "transformers_version": "4.29.2"
}

这到底是什么原因呢？

**Comment by askintution** [comment]
是不是<reserved_102>encode之后是195？

**Comment by xusenlinzy** [comment]
@askintution 是的

下面是一些测试示例，您可以看一下

```python
from transformers import AutoTokenizer
tokenizer = AutoTokenizer.from_pretrained("baichuan-inc/Baichuan-13B-Chat", trust_remote_code=True)

tokenizer.decode(195)
# <reserved_102>

tokenizer.decode(196)
# <reserved_103>

# 1. 字符串拼接方式（本项目的prompt模板）
tokenizer.encode("<reserved_102> 你好<reserved_103> 我是人工智能助理</s>")
# [31106, 195, 9875, 31213, 196, 6323, 31161, 22073, 19745, 2]

# 2. id拼接方式（baichuan官方：https://huggingface.co/baichuan-inc/Baichuan-13B-Chat/blob/f5f47be2adbbdceb784f334d6fa1ca2c73e65097/modeling_baichuan.py#L502）
[195] + tokenizer.encode("你好") + [196] + tokenizer.encode("我是人工智能助理") + [2]
# [195, 9875, 31213, 196, 6323, 31161, 22073, 19745, 2]

[195] + tokenizer.encode("你好") + [196] + tokenizer.encode("请问有什么可以帮你？") + [2, 195] + tokenizer.encode("没事，退下吧") + [196]
# [195, 9875, 31213, 196, 31106, 20389, 7713, 1231, 17346, 75, 2, 195, 31106, 25639, 72, 31991, 31214, 31793, 196]
```

两种方式的唯一区别就在于每轮对话多了一个31106（空字符串），基本上保持一致

**Comment by askintution** [comment]
多谢
