### ISSUE TITLE
请问如何使用指定的卡

### ISSUE THREAD

**Issue by jinghai** [xusenlinzy/api-for-open-llm#32]
机器上有4块卡，我想使用第3块显卡启动应用，命令如下：
docker run -it -d --gpus 2 --ipc=host --net=bridge -p 6011:6006 --name=chatglm \
    --ulimit memlock=-1 --ulimit stack=67108864 \
    -v `pwd`:/workspace \
    -v /data0/models:/workspace/models \
    llm-api:pytorch \
    python api/app.py \
    --port 6006 \
    --allow-credentials \
    --model_name chatglm \
    --model_path models/chatglm-6b \
    --device cuda \
    --embedding_name models/m3e-base
但是跑起来以后，还是使用第一块显卡，是命令参数不对吗？

**Comment by xusenlinzy** [comment]
@jinghai  使用  `–gpus "device=2”` 试试，`--gpus 2` 应该是使用前两块显卡
