### ISSUE TITLE
访问出错

### ISSUE THREAD

**Issue by lucheng07082221** [xusenlinzy/api-for-open-llm#34]
我在服务器上启动了容器：
docker run -it -d --gpus all --ipc=host --net=bridge -p 6006:6006 --name=baichuan-13b-chat     --ulimit memlock=-1 --ulimit stack=67108864   -v `pwd`:/workspace  -v /data/models:/workspace/models     llm-api:pytorch

在容器里面运行：
python3 api/app.py     --port 6006     --allow-credentials     --model_name baichuan-13b-chat     --model_path ../models/Baichuan-13B-Chat     --device cuda     --embedding_name ../models/text2vec-large-chinese --gpus 2,3,4,5

在本地访问服务器：
ssh -L 7860:127.0.0.1:7860 root@10.8.113.77
ssh -L 7860:0.0.0.0:6006 root@172.16.0.8

然后浏览器输入IP：
http://127.0.0.1:7860/

报错：

![2023-07-28 18-48-09屏幕截图](https://github.com/xusenlinzy/api-for-open-llm/assets/3146209/5ac6b58c-03f0-4ec2-8fed-0ce24349b5fb)

![2023-07-28 18-49-55屏幕截图](https://github.com/xusenlinzy/api-for-open-llm/assets/3146209/d21ff157-c5d0-405f-86e6-a213d69c6351)
![2023-07-28 18-50-43屏幕截图](https://github.com/xusenlinzy/api-for-open-llm/assets/3146209/92b25902-dc24-4e69-b7d2-9a0136ee8e28)

知道什么原因吗？

**Comment by xusenlinzy** [comment]
你好，您可以试试使用 `ip` 地址访问，例如 `http://192.168.0.53:7890/docs`，查看所有接口

**Comment by lucheng07082221** [comment]
thank you
