### ISSUE TITLE
尝试加载本地firefly-baichuan13b的模型时显存占用翻倍

### ISSUE THREAD

**Issue by bswaterb** [xusenlinzy/api-for-open-llm#38]
服务正常，但是总显存占用量达到了 50 GB 左右，相比单独加载的13B模型，显存占用量翻倍，启动命令如下：  
```
python api/app.py \
--port 80 \
--allow-credentials \
--model_name baichuan13b-firefly \
--model_path /usr/repo/firefly-baichuan-13b \
--device cuda \
--embedding_name /usr/repo/text2vec-large-chinese \
--gpus 0,1 \
--num_gpus 2 \
--prompt_name firefly
```

**Comment by bswaterb** [comment]
启动原版 baichuan13b-chat 的显存占用是正常的（26GB左右）：  
```
python api/app.py \
--port 80 \
--allow-credentials \
--model_name baichuan13b \
--model_path /usr/repo/Baichuan-13B-Chat \
--device cuda \
--embedding_name /usr/repo/text2vec-large-chinese \
--gpus 0,1 \
--num_gpus 2
```

**Comment by xusenlinzy** [comment]
您好，有可能是模型加载使用了以下的类：

https://github.com/xusenlinzy/api-for-open-llm/blob/31e7b514fcc74dc3cbd7f3aeae6ee75fe1977f27/api/model_adapter.py#L305

您可以试一下把 `model_name` 改成 `--model_name baichuan13b`

**Comment by bswaterb** [comment]
> python api/app.py \
> --port 80 \
> --allow-credentials \
> --model_name baichuan13b-firefly \
> --model_path /usr/repo/firefly-baichuan-13b \
> --device cuda \
> --embedding_name /usr/repo/text2vec-large-chinese \
> --gpus 0,1 \
> --num_gpus 2 \
> --prompt_name firefly

测试正常，感谢！

**Comment by bswaterb** [comment]
> 您好，有可能是模型加载使用了以下的类：
> 
> https://github.com/xusenlinzy/api-for-open-llm/blob/31e7b514fcc74dc3cbd7f3aeae6ee75fe1977f27/api/model_adapter.py#L305
> 
> 您可以试一下把 `model_name` 改成 `--model_name baichuan13b`

测试正常，十分感谢
