### ISSUE TITLE
可以支持llama2-hf么？

### ISSUE THREAD

**Issue by Smile-L** [xusenlinzy/api-for-open-llm#41]
可以支持llama2-hf么？
https://huggingface.co/meta-llama/Llama-2-70b-chat-hf

**Comment by xusenlinzy** [comment]
支持的，启动命令参考

```
docker run -it -d --gpus all --ipc=host --net=host -p 80:80 --name=llama2\
    --ulimit memlock=-1 --ulimit stack=67108864 \
    -v `pwd`:/workspace \
    llm-api:pytorch \
    python api/app.py \
    --port 80 \
    --allow-credentials \
    --model_name llama2 \
    --model_path meta-llama/Llama-2-70b-chat-hf \
    --device cuda \
    --num_gpus 8 \
    --gpus 0,1,2,3,4,5,6,7
```

**Comment by chensimian** [comment]
llama2-hf 启动server.py应该如何配置？为什么启动会报错？
ImportError: 
The new behaviour of LlamaTokenizer (with `self.legacy = False`) requires the protobuf library but it was not found in your environment. Checkout the instructions on the
installation page of its repo: https://github.com/protocolbuffers/protobuf/tree/master/python#installation and follow the ones
that match your environment. Please note that you may need to restart your runtime after installation.
