### ISSUE TITLE
推理速度疑问（很快）

### ISSUE THREAD

**Issue by onlyfish79** [xusenlinzy/api-for-open-llm#42]
**模型:** Baichuan-13B-Chat

**问题**：使用官方提供的web_demo.py，以及在一些群里有些人反馈Baichuan-13B-Chat越聊会越慢（对话多或者输入和生成token较大），但是这个项目的推理速度就比较快．

- 对比了一下Baichuan-13B-Chat使用vllm加速推理和这个项目的推理速度比较接近，请问这个项目对推理做了什么优化吗？
- 如果对推理做了优化，是否牺牲了推理生成内容质量？

**Comment by xusenlinzy** [comment]
您好，本项目的推理代码参考了 [fastchat](https://github.com/lm-sys/FastChat/blob/main/fastchat/serve/inference.py)，速度上没有什么优化，生成内容应该也区别不大，我实际使用时，文本越长速度确实也是越来越慢的

**Comment by onlyfish79** [comment]
明白．

还有个现象：当使用2个卡推理，比单卡推理慢了很多，单卡输入1500字左右，生成token: 1500左右，每秒40字, 但是如果使用2个卡，差不多每秒1各字，是否正常？

**Comment by xusenlinzy** [comment]
我使用时也是双卡会变慢，可能显卡之间通信很花时间，也可能是没有配置好😅，可以看一下这个 https://github.com/THUDM/ChatGLM-6B/issues/595

**Comment by onlyfish79** [comment]
好的，谢谢．

另外看了一下代码， 速度快的原因一方面应该是使用了@torch.inference_mode()装饰器，应该还有其他原因．**torch.inference_mode()作用:** 

- 禁用自动梯度（Autograd）： 在推理阶段，我们通常不需要计算梯度，因为我们不会进行模型参数的更新。torch.inference_mode 会禁用自动梯度，这样可以节省存储梯度所需要的内存，也可以避免进行不必要的梯度计算。

- 改变某些操作的行为： torch.inference_mode 还会改变某些 PyTorch 操作的行为，使它们在推理阶段更加高效。例如，它会禁用某些对于推理来说不必要的检查。

**Comment by chelovek21** [comment]
@onlyfish79 你好，Baichuan-13B-Chat用vllm加速可以实现吗？能做8bit量化吗？谢谢

**Comment by onlyfish79** [comment]
1. 上周使用的是这个项目：https://github.com/ericzhou571/vllm， 支持baichuan-13b-chat, 目前vllm官方代码已经支持baichuan-13b。
2. 使用 https://github.com/ericzhou571/vllm 这个项目，推理是比较快，但是发现temperature和top_p除了设置为1，其他参数效果都比较差，生成内容也比未加速的差很多。不知道是不是我哪用的不对，还是这个项目的问题。
3. 建议直接使用vllm官方的代码试试，我这边如果试完有结论在同步
4. 没使用量化，不确认是否支持。

**Comment by xusenlinzy** [comment]
@onlyfish79  本项目最近增加了vllm的支持，主要对模型输入做了一些修改，支持baichuan和qwen等模型，使用方式见 https://github.com/xusenlinzy/api-for-open-llm/blob/master/docs/VLLM_SCRIPT.md，你可以测试一下效果怎么样

**Comment by onlyfish79** [comment]
好的，谢谢
