### ISSUE TITLE
chat/completions和completions接口的结果差异较大

### ISSUE THREAD

**Issue by TheBobbyliu** [xusenlinzy/api-for-open-llm#43]
最近使用的时候发现，同样的请求，调用chat/completions和completions的效果差异较大，在Baichuan-13B和Qwen上都发现这个现象。
我使用的prompt都是一样的，top-p和temperature也一样。
这是chat请求接收到后的gen_params:
chat generated params: {'model': 'gpt-turbo-3.5', 'prompt': [{'role': 'user', 'content': "内容"}], 'temperature': 1.0, 'top_p': 0.95, 'max_new_tokens': 1024, 'echo': False, 'stream': False, 'stop': ['<|im_end|>']}
这是completion请求接收到后的gen_params:
completion generated params: {'model': 'text-davinci-003', 'prompt': 'xxx', 'temperature': 1.0, 'top_p': 0.95, 'max_new_tokens': 256, 'echo': False, 'stream': False, 'stop': ['<|im_end|>']}
因为我是使用langchain.OpenAI和langchain.chat_models.ChatOpenAI分别调用api的，所以model那块自动填充的是上面这两个模型，底下跑的还是Qwen哈。

使用completion接口的时候，经常会出现模型直接返回空或者多个换行符，不返回实质性内容。使用chat接口就会正常一些。

**Comment by TheBobbyliu** [comment]
当时是处于什么考虑，对completion接口输入的prompt不做prompt adapt的呢？

**Comment by xusenlinzy** [comment]
> 当时是处于什么考虑，对completion接口输入的prompt不做prompt adapt的呢？

因为非对话模型是没有模板的，比如baichuan-inc/Baichuan-13B-Base和Qwen/Qwen-7B

**Comment by TheBobbyliu** [comment]
好的明白了，是我使用方法有一些问题
