### ISSUE TITLE
建议增加llama2系列模型的call function功能

### ISSUE THREAD

**Issue by skingko** [xusenlinzy/api-for-open-llm#45]
千问代码生成能力较弱，这方面llama2系列相对好很多，如果增加了call function功能，类似代码解释器的实现就很容易了~

**Comment by huangchen007** [comment]
@xusenlinzy 这个issue一直没有更新，是否有难度？主要的难点是什么呢？

**Comment by thiner** [comment]
最新的Qwen 模型已经支持call function功能了。
