### ISSUE TITLE
报错：更新了最新代码后报错

### ISSUE THREAD

**Issue by jinghai** [xusenlinzy/api-for-open-llm#46]
File "/workspace/./api/router.py", line 270, in create_chat_completion
    gen_params = get_gen_params(
  File "/workspace/./api/router.py", line 115, in get_gen_params
    messages = get_qwen_react_prompt(messages, functions, function_call)
  File "/workspace/./api/react_prompt.py", line 35, in get_qwen_react_prompt
    name_for_model=info["name_for_model"],
KeyError: 'name_for_model'

**Comment by jinghai** [comment]
建议对较稳定的版本打Tag

**Comment by xusenlinzy** [comment]
目前 `functions` 参数的格式是使用下面的，和 [openai](https://platform.openai.com/docs/guides/gpt/function-calling) 的不t太一样 

```python
functions = [
      {
          "name_for_human":
              "定积分计算器",
          "name_for_model":
              "calculate_quad",
          "description_for_model":
              "定积分计算器是一个可以计算给定区间内函数定积分数值的工具。",
          "parameters": [
              {
                  'name': 'formula_str',
                  'description': '一个数学函数的表达式，例如x**2',
                  'required': True,
                  'schema': {
                      'type': 'string'
                  },
              },
              {
                  'name': 'a',
                  'description': '积分区间的左端点，例如1.0',
                  'required': True,
                  'schema': {
                      'type': 'string'
                  },
              },
              {
                  'name': 'b',
                  'description': '积分区间的右端点，例如5.0',
                  'required': True,
                  'schema': {
                      'type': 'string'
                  },
              },
          ],
      },
]
```

**Comment by jinghai** [comment]
我使用的是chatglm2，做为dify.ai的后端模型，在带插件的场景下出错：
![image](https://github.com/xusenlinzy/api-for-open-llm/assets/5433705/26dcc375-7041-4afd-8d4c-4cde829cc6ed)

**Comment by jinghai** [comment]
另外，chatglm2-32K模型下，普通的问答也会报错，报错没做截图，可以对接dify.ai试一下

**Comment by xusenlinzy** [comment]
您好，我这边测试 chatglm2-32K 对话是正常的

![image](https://github.com/xusenlinzy/api-for-open-llm/assets/111472355/9b4c3321-e215-4d50-b043-4c7225215fa0)
