### ISSUE TITLE
千问的加速依赖是要加到docker中吗？

### ISSUE THREAD

**Issue by jinghai** [xusenlinzy/api-for-open-llm#47]
除已有的环境之外，推荐安装下面的依赖以提高运行效率和降低显存占用

git clone -b v1.0.8 https://github.com/Dao-AILab/flash-attention
cd flash-attention && pip install .

pip install csrc/layer_norm
pip install csrc/rotary

上面的安装要在docker中执行还是在宿主机上执行？

**Comment by xusenlinzy** [comment]
进入docker容器后安装

**Comment by jinghai** [comment]
建议写在文档里
