### ISSUE TITLE
希望并发处理多个请求

### ISSUE THREAD

**Issue by Huangyajuan-123** [xusenlinzy/api-for-open-llm#48]
请求只能同时处理一个?

**Comment by xusenlinzy** [comment]
本项目最近增加了vllm的支持，主要对模型输入做了一些修改，支持baichuan和qwen等模型，你可以测试一下效果怎么样使用方式见 https://github.com/xusenlinzy/api-for-open-llm/blob/master/docs/VLLM_SCRIPT.md

**Comment by Huangyajuan-123** [comment]
谢谢! 为什么在没有添加vllm之前的代码, 推理速度比hf模型推理速度,是做了哪方面的改进?

**Comment by xusenlinzy** [comment]
模型的解码方式统一采用了 
https://github.com/xusenlinzy/api-for-open-llm/blob/a6a7b1152a54ab8fdb201bbe893549abca942717/api/generate.py#L206
有可能是解码方式相对简单
