### ISSUE TITLE
你好，能出一个非docker环境下的执行流程吗，目前服务器无法安装docker，很多命令都执行不了，谢谢。

### ISSUE THREAD

**Issue by wenyu332** [xusenlinzy/api-for-open-llm#49]

**Comment by xusenlinzy** [comment]
非docker环境下命令是类似的，

比如 docker命令为：

```
docker run -it -d --gpus all --ipc=host --net=host -p 80:80 --name=chatglm \
    --ulimit memlock=-1 --ulimit stack=67108864 \
    -v `pwd`:/workspace \
    llm-api:pytorch \
    python api/app.py \
    --port 80 \
    --allow-credentials \
    --model_name chatglm \
    --model_path THUDM/chatglm-6b \
    --device cuda \
    --embedding_name moka-ai/m3e-base
```

则本地启动的话只需要  `python api/app.py` 后面的命令

```
python api/app.py \
    --port 80 \
    --allow-credentials \
    --model_name chatglm \
    --model_path THUDM/chatglm-6b \
    --device cuda \
    --embedding_name moka-ai/m3e-base
```

**Comment by wenyu332** [comment]
这个命令我可以正常启动，后面我应该怎么调用呢，卡在了下一步

**Comment by xusenlinzy** [comment]
代码调用方式，其中api_base是需要修改的，192.168.0.xx改成服务器的ip地址，80改成你启动时暴露的端口

```
import openai

openai.api_base = "http://192.168.0.xx:80/v1"

# Enter any non-empty API key to pass the client library's check.
openai.api_key = "xxx"

# Enter any non-empty model name to pass the client library's check.
completion = openai.ChatCompletion.create(
    model="chatglm-6b",
    messages=[
        {"role": "user", "content": "你好"},
    ],
    stream=False,
)

print(completion.choices[0].message.content)
# 你好👋！我是人工智能助手 ChatGLM-6B，很高兴见到你，欢迎问我任何问题。
```

**Comment by Con-Ming** [comment]
> 非docker环境下命令是类似的，
> 
> 比如 docker命令为：
> 
> ```
> docker run -it -d --gpus all --ipc=host --net=host -p 80:80 --name=chatglm \
>     --ulimit memlock=-1 --ulimit stack=67108864 \
>     -v `pwd`:/workspace \
>     llm-api:pytorch \
>     python api/app.py \
>     --port 80 \
>     --allow-credentials \
>     --model_name chatglm \
>     --model_path THUDM/chatglm-6b \
>     --device cuda \
>     --embedding_name moka-ai/m3e-base
> ```
> 
> 则本地启动的话只需要 `python api/app.py` 后面的命令
> 
> ```
> python api/app.py \
>     --port 80 \
>     --allow-credentials \
>     --model_name chatglm \
>     --model_path THUDM/chatglm-6b \
>     --device cuda \
>     --embedding_name moka-ai/m3e-base
> ```

你好，我今天运行报错没有api/app.py文件，想问下应该怎么解决？我的启动代码是
python api/app.py \
  --port 2818 \
  --allow-credentials \
  --model_name baichuan-13b-chat \
  --model_path /home/maming/llm_tuning/LLaMA-Efficient-Tuning/output/WL-baichuan-13b-chat \
  --device cuda \
  --ADAPTER_MODEL_PATH lora
