### ISSUE TITLE
为什么每次回答的内容都不一样阿

### ISSUE THREAD

**Issue by lucheng07082221** [xusenlinzy/api-for-open-llm#51]
![2023-08-09 10-23-41屏幕截图](https://github.com/xusenlinzy/api-for-open-llm/assets/3146209/af37f094-5175-458f-8a19-f7df240ee734)

**Comment by xusenlinzy** [comment]
您好，模型回答结果本身是具有随机性的，如果想要相对固定的回答，可以在 `OpenAI`  中设置  `temperature`  参数，值越低，随机性越低。此外，`OpenAI` 没有预设对话 `prompt`，如果想要更好的对话效果，推荐使用 `ChatOpenAI` ，使用方式参考 https://python.langchain.com/docs/modules/model_io/models/chat/
