### ISSUE TITLE
stream模式下，function call 不兼容

### ISSUE THREAD

**Issue by zhengxiang5965** [xusenlinzy/api-for-open-llm#52]
stream模式下，function call 不兼容
这是非stream模式下响应体
![image](https://github.com/xusenlinzy/api-for-open-llm/assets/31379313/6cca126b-92a1-456e-8ca7-08ceb817f9bc)
这是stream模式下
![image](https://github.com/xusenlinzy/api-for-open-llm/assets/31379313/9cc6a89c-c6a7-440c-b4e6-3b7fa165c90f)

stream没有对function call做适配,没有function_call属性
![image](https://github.com/xusenlinzy/api-for-open-llm/assets/31379313/cfca6949-628d-42a7-835a-0c5697e80e56)

@xusenlinzy

_Originally posted by @zhengxiang5965 in https://github.com/xusenlinzy/api-for-open-llm/issues/12#issuecomment-1671097913_

**Comment by zhengxiang5965** [comment]
@xusenlinzy 我关注了最近的代码变更 这个字段加上去了好像没有赋值

**Comment by xusenlinzy** [comment]
暂时还没有增加 stream 模式下的 function call

**Comment by zhengxiang5965** [comment]
> 暂时还没有增加 stream 模式下的 function call

这个大概计划在哪个版本增加呢

**Comment by zhengxiang5965** [comment]
@xusenlinzy 可以组建一个交流群吗？
