### ISSUE TITLE
求助：Baichuan-13b-chat运行报错

### ISSUE THREAD

**Issue by happyfire** [xusenlinzy/api-for-open-llm#56]
docker run报错：
docker: Error response from daemon: could not select device driver "" with capabilities: [[gpu]].

运行环境为win10 WSL2 (Ubuntu 22.04)
同样的环境，Baichuan13b-chat的web_demo和cli_demo都可以运行，使用的是8bit量化模式。（GPU显存24G,分给WSL 20G）

以下是docker run命令行，请问问题出在哪儿？软硬件环境应该都满足运行该模型

sudo docker run -it -d --gpus all --ipc=host --net=host -p 80:80 --name=baichuan-13b-chat \
    --ulimit memlock=-1 --ulimit stack=67108864 \
    -v `pwd`:/workspace \
    llm-api:pytorch \
    python api/app.py \
    --port 6666 \
    --allow-credentials \
    --model_name baichuan-13b-chat \
    --model_path /home/wmjy/llm/baichuan-inc/Baichuan-13B-Chat \
    --device cuda \
    --quantize 8

其中model_path 是本地下载下来的模型权重

**Comment by xusenlinzy** [comment]
您好，您的docker环境没有安装nvidia-container-runtime，所以使用GPU会有问题

**Comment by xusenlinzy** [comment]
或者你也可以本地启动模型

```
pip install -r requirements.txt
```

```
python api/app.py
  --port 6666
  --allow-credentials
  --model_name baichuan-13b-chat
  --model_path /home/wmjy/llm/baichuan-inc/Baichuan-13B-Chat
  --device cuda
  --quantize 8
```

**Comment by happyfire** [comment]
> 或者你也可以本地启动模型
> 
> ```
> pip install -r requirements.txt
> ```
> 
> ```
> python api/app.py
>   --port 6666
>   --allow-credentials
>   --model_name baichuan-13b-chat
>   --model_path /home/wmjy/llm/baichuan-inc/Baichuan-13B-Chat
>   --device cuda
>   --quantize 8
> ```

你好，我试了一下本地启动，使用的是之前运行baichuan13b-chat web demo的conda虚拟环境，python 3.10的，我就没有重新创建虚拟环境。但是报错了，您看下，是虚拟环境的问题吗？

`(baichuan-13b) wmjy@BuildMachine:~/api-for-open-llm$ sh runBaichuan13b.sh
╭─────────────────────────────── Traceback (most recent call last) ────────────────────────────────╮
│ /home/wmjy/api-for-open-llm/api/app.py:97 in <module>                                            │
│                                                                                                  │
│    94 │   │   │   )                                                                              │
│    95 │   │   os.environ["CUDA_VISIBLE_DEVICES"] = args.gpus                                     │
│    96 │                                                                                          │
│ ❱  97 │   from api.router import main                                                            │
│    98 │                                                                                          │
│    99 │   if args.patch_type == "rerope":                                                        │
│   100 │   │   from api.patches import apply_rerope_patch                                         │
│                                                                                                  │
│ /home/wmjy/api-for-open-llm/./api/router.py:17 in <module>                                       │
│                                                                                                  │
│    14                                                                                            │
│    15 from api.constants import ErrorCode                                                        │
│    16 from api.generate import ModelServer                                                       │
│ ❱  17 from api.model_adapter import load_model                                                   │
│    18 from api.protocol import (                                                                 │
│    19 │   ChatCompletionRequest,                                                                 │
│    20 │   ChatCompletionResponse,                                                                │
│                                                                                                  │
│ /home/wmjy/api-for-open-llm/./api/model_adapter.py:9 in <module>                                 │
│                                                                                                  │
│     6                                                                                            │
│     7 import torch                                                                               │
│     8 from loguru import logger                                                                  │
│ ❱   9 from peft import PeftModel                                                                 │
│    10 from tqdm import tqdm                                                                      │
│    11 from transformers import (                                                                 │
│    12 │   AutoModel,                                                                             │
│                                                                                                  │
│ /home/wmjy/.local/lib/python3.10/site-packages/peft/__init__.py:22 in <module>                   │
│                                                                                                  │
│   19                                                                                             │
│   20 __version__ = "0.5.0.dev0"                                                                  │
│   21                                                                                             │
│ ❱ 22 from .auto import (                                                                         │
│   23 │   AutoPeftModel,                                                                          │
│   24 │   AutoPeftModelForCausalLM,                                                               │
│   25 │   AutoPeftModelForSequenceClassification,                                                 │
│                                                                                                  │
│ /home/wmjy/.local/lib/python3.10/site-packages/peft/auto.py:30 in <module>                       │
│                                                                                                  │
│    27 │   AutoModelForTokenClassification,                                                       │
│    28 )                                                                                          │
│    29                                                                                            │
│ ❱  30 from .config import PeftConfig                                                             │
│    31 from .mapping import MODEL_TYPE_TO_PEFT_MODEL_MAPPING                                      │
│    32 from .peft_model import (                                                                  │
│    33 │   PeftModel,                                                                             │
│                                                                                                  │
│ /home/wmjy/.local/lib/python3.10/site-packages/peft/config.py:24 in <module>                     │
│                                                                                                  │
│    21 from huggingface_hub import hf_hub_download                                                │
│    22 from transformers.utils import PushToHubMixin                                              │
│    23                                                                                            │
│ ❱  24 from .utils import CONFIG_NAME, PeftType, TaskType                                         │
│    25                                                                                            │
│    26                                                                                            │
│    27 @dataclass                                                                                 │
│                                                                                                  │
│ /home/wmjy/.local/lib/python3.10/site-packages/peft/utils/__init__.py:22 in <module>             │
│                                                                                                  │
│   19                                                                                             │
│   20 # from .config import PeftConfig, PeftType, PromptLearningConfig, TaskType                  │
│   21 from .peft_types import PeftType, TaskType                                                  │
│ ❱ 22 from .other import (                                                                        │
│   23 │   TRANSFORMERS_MODELS_TO_PREFIX_TUNING_POSTPROCESS_MAPPING,                               │
│   24 │   TRANSFORMERS_MODELS_TO_LORA_TARGET_MODULES_MAPPING,                                     │
│   25 │   TRANSFORMERS_MODELS_TO_ADALORA_TARGET_MODULES_MAPPING,                                  │
│                                                                                                  │
│ /home/wmjy/.local/lib/python3.10/site-packages/peft/utils/other.py:24 in <module>                │
│                                                                                                  │
│    21 import accelerate                                                                          │
│    22 import torch                                                                               │
│    23 from accelerate.hooks import add_hook_to_module, remove_hook_from_module                   │
│ ❱  24 from accelerate.utils import is_npu_available, is_xpu_available                            │
│    25                                                                                            │
│    26                                                                                            │
│    27 # Get current device name based on available devices                                       │
╰──────────────────────────────────────────────────────────────────────────────────────────────────╯
ImportError: cannot import name 'is_npu_available' from 'accelerate.utils'
(/home/wmjy/.local/lib/python3.10/site-packages/accelerate/utils/__init__.py)`
