### ISSUE TITLE
My Qwen LLM startup failed

### ISSUE THREAD

**Issue by Hkaisense** [xusenlinzy/api-for-open-llm#57]
ValueError: Model architectures ['QWenLMHeadModel'] are not supported for now. Supported architectures: ['BaiChuanForCausalLM', 'BaichuanForCausalLM', 'BloomForCausalLM', 'FalconForCausalLM', 'GPT2LMHeadModel', 'GPTBigCodeForCausalLM', 'GPTJForCausalLM', 'GPTNeoXForCausalLM', 'LlamaForCausalLM', 'LLaMAForCausalLM', 'MPTForCausalLM', 'OPTForCausalLM', 'RWForCausalLM']

**Comment by xusenlinzy** [comment]
please install vllm from source code

```
pip install torch>=2.0.0
pip install git+https://github.com/vllm-project/vllm.git
```

**Comment by Hkaisense** [comment]
Thanks! It seems that the problem has been improved, but a new problem has come

INFO 08-11 12:24:40 llm_engine.py:70] Initializing an LLM engine with config: model='source/model/models--Qwen--Qwen-7B-Chat', tokenizer='source/model/models--Qwen--Qwen-7B-Chat', tokenizer_mode=slow, trust_remote_code=True, dtype=torch.float16, use_dummy_weights=False, download_dir=None, use_np_weights=False, tensor_parallel_size=1, seed=0)
WARNING 08-11 12:24:41 tokenizer.py:63] Using a slow tokenizer. This might cause a significant slowdown. Consider using a fast tokenizer instead.
Traceback (most recent call last):
  File "api/vllm_server.py", line 637, in <module>
    engine = AsyncLLMEngine.from_engine_args(engine_args)
  File "/usr/local/lib/python3.8/dist-packages/vllm/engine/async_llm_engine.py", line 232, in from_engine_args
    engine = cls(engine_args.worker_use_ray,
  File "/usr/local/lib/python3.8/dist-packages/vllm/engine/async_llm_engine.py", line 55, in __init__
    self.engine = engine_class(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/vllm/engine/llm_engine.py", line 101, in __init__
    self._init_workers(distributed_init_method)
  File "/usr/local/lib/python3.8/dist-packages/vllm/engine/llm_engine.py", line 119, in _init_workers
    from vllm.worker.worker import Worker  # pylint: disable=import-outside-toplevel
  File "/usr/local/lib/python3.8/dist-packages/vllm/worker/worker.py", line 10, in <module>
    from vllm.model_executor import get_model, InputMetadata, set_random_seed
  File "/usr/local/lib/python3.8/dist-packages/vllm/model_executor/__init__.py", line 2, in <module>
    from vllm.model_executor.model_loader import get_model
  File "/usr/local/lib/python3.8/dist-packages/vllm/model_executor/model_loader.py", line 9, in <module>
    from vllm.model_executor.models import *  # pylint: disable=wildcard-import
  File "/usr/local/lib/python3.8/dist-packages/vllm/model_executor/models/__init__.py", line 1, in <module>
    from vllm.model_executor.models.baichuan import (BaiChuanForCausalLM,
  File "/usr/local/lib/python3.8/dist-packages/vllm/model_executor/models/baichuan.py", line 33, in <module>
    from vllm.model_executor.layers.activation import SiluAndMul
  File "/usr/local/lib/python3.8/dist-packages/vllm/model_executor/layers/activation.py", line 5, in <module>
    from vllm import activation_ops
ImportError: /usr/local/lib/python3.8/dist-packages/vllm/activation_ops.cpython-38-x86_64-linux-gnu.so: undefined symbol: _ZN3c106detail14torchCheckFailEPKcS2_jRKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE

**Comment by xusenlinzy** [comment]
`pip install torch - U`  before `pip install git+https://github.com/vllm-project/vllm.git`

**Comment by Hkaisense** [comment]
FROM nvcr.io/nvidia/pytorch:22.12-py3

WORKDIR /workspace/
ENV PYTHONPATH /workspace/
COPY requirements.txt /workspace/
COPY . /workspace

RUN pip install --no-cache-dir -r /workspace/requirements.txt -i https://mirror.baidu.com/pypi/simple
RUN pip install bitsandbytes --upgrade -i https://mirror.baidu.com/pypi/simple && \
    pip install torch -U -i https://mirror.baidu.com/pypi/simple && \
    pip install vllm -i https://pypi.tuna.tsinghua.edu.cn/simple --trusted-host pypi.tuna.tsinghua.edu.cn

**Comment by Hkaisense** [comment]
Thank you very much for your patience, is the docker configuration file I set up like this correct?

**Comment by xusenlinzy** [comment]
yes, here is the dockerfile content:

```
FROM nvcr.io/nvidia/pytorch:22.12-py3

WORKDIR /workspace/
ENV PYTHONPATH /workspace/
COPY requirements.txt /workspace/
COPY . /workspace

RUN pip install --no-cache-dir -r /workspace/requirements.txt -i https://mirror.baidu.com/pypi/simple
RUN pip install bitsandbytes --upgrade -i https://mirror.baidu.com/pypi/simple && \
    pip install torch -U -i https://mirror.baidu.com/pypi/simple && \
    pip install git+https://github.com/vllm-project/vllm.git
```

**Comment by Hkaisense** [comment]
FROM nvcr.io/nvidia/pytorch:22.12-py3
  
WORKDIR /workspace/
ENV PYTHONPATH /workspace/
COPY requirements.txt /workspace/
COPY . /workspace

RUN pip install --no-cache-dir -r /workspace/requirements.txt -i https://mirror.baidu.com/pypi/simple
RUN pip install bitsandbytes --upgrade -i https://mirror.baidu.com/pypi/simple && \
    pip install torch -U  -i https://pypi.tuna.tsinghua.edu.cn/simple --trusted-host pypi.tuna.tsinghua.edu.cn && \
    http_proxy="http://192.168.2.181:7890" https_proxy="http://192.168.2.181:7890" pip install git+https://github.com/vllm-project/vllm.git

**Comment by Hkaisense** [comment]
Thanks a lot for your patience, it's done!
