### ISSUE TITLE
安装成功，调用几次就会报错。

### ISSUE THREAD

**Issue by Hkaisense** [xusenlinzy/api-for-open-llm#59]
### 提交前必须检查以下项目 | The following items must be checked before submission

- [X] 请确保使用的是仓库最新代码（git pull），一些问题已被解决和修复。 | Make sure you are using the latest code from the repository (git pull), some issues have already been addressed and fixed.
- [X] 我已阅读[项目文档](https://github.com/xusenlinzy/api-for-open-llm/blob/master/README.md)和[FAQ章节](https://github.com/xusenlinzy/api-for-open-llm/blob/master/docs/FAQ.md)并且已在Issue中对问题进行了搜索，没有找到相似问题和解决方案 | I have searched the existing issues / discussions

### 问题类型 | Type of problem

模型推理和部署 | Model inference and deployment

### 操作系统 | Operating system

Linux

### 详细描述问题 | Detailed description of the problem

```
# 请在此处粘贴运行代码（如没有可删除该代码块）
# Paste the runtime code here (delete the code block if you don't have it)
```

### Dependencies

FROM nvcr.io/nvidia/pytorch:22.12-py3
  
WORKDIR /workspace/
ENV PYTHONPATH /workspace/
COPY requirements.txt /workspace/
COPY . /workspace

RUN pip install --no-cache-dir -r /workspace/requirements.txt -i https://mirror.baidu.com/pypi/simple
RUN pip install bitsandbytes --upgrade -i https://mirror.baidu.com/pypi/simple && \
    pip install torch -U  -i https://pypi.tuna.tsinghua.edu.cn/simple --trusted-host pypi.tuna.tsinghua.edu.cn && \
    pip install git+https://github.com/vllm-project/vllm.git -i https://pypi.tuna.tsinghua.edu.cn/simple --trusted-host pypi.tuna.tsinghua.edu.cn

### 运行日志或截图 | Runtime logs or screenshots

RuntimeError: CUDA error: unspecified launch failure
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.

**Comment by xusenlinzy** [comment]
请问您的启动命令和调用方式是？

**Comment by Hkaisense** [comment]
python3 -m vllm.entrypoints.openai.api_server --model source/model/models--Qwen--Qwen-7B-Chat --trust-remote-code我用curl调用您提供的接口地址也一样，两种方式都会报这个错发自我的 iPhone在 2023年8月12日，13:18，xusenlin ***@***.***> 写道：﻿
请问您的启动命令和调用方式是？
