### ISSUE TITLE
求助，ModuleNotFoundError: No module named 'api.constants'

### ISSUE THREAD

**Issue by duronxx** [xusenlinzy/api-for-open-llm#6]
本机安装提示找不到此模块，

![image](https://github.com/xusenlinzy/api-for-open-llm/assets/33643555/fe64b627-7dfc-490d-8dad-5a7e121fa011)

**Comment by duronxx** [comment]
其实就在他目录 下面，这个要怎么修改啊

**Comment by xusenlinzy** [comment]
试一下设置python路径

export PYTHONPATH=.
