### ISSUE TITLE
使用vllm推理starchat报错，错误如下：

### ISSUE THREAD

**Issue by foxxxx001** [xusenlinzy/api-for-open-llm#65]
### 提交前必须检查以下项目 | The following items must be checked before submission

- [X] 请确保使用的是仓库最新代码（git pull），一些问题已被解决和修复。 | Make sure you are using the latest code from the repository (git pull), some issues have already been addressed and fixed.
- [X] 我已阅读[项目文档](https://github.com/xusenlinzy/api-for-open-llm/blob/master/README.md)和[FAQ章节](https://github.com/xusenlinzy/api-for-open-llm/blob/master/docs/FAQ.md)并且已在Issue中对问题进行了搜索，没有找到相似问题和解决方案 | I have searched the existing issues / discussions

### 问题类型 | Type of problem

模型推理和部署 | Model inference and deployment

### 操作系统 | Operating system

None

### 详细描述问题 | Detailed description of the problem

```
# 请在此处粘贴运行代码（如没有可删除该代码块）
# Paste the runtime code here (delete the code block if you don't have it)
```
ImportError: /usr/local/lib/python3.8/dist-packages/vllm/activation_ops.cpython-38-x86_64-linux-gnu.so: undefined symbol: _ZN3c106detail14torchCheckFailEPKcS2_jRKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE

### Dependencies

```
# 请在此处粘贴依赖情况
# Please paste the dependencies here
```

### 运行日志或截图 | Runtime logs or screenshots

```
# 请在此处粘贴运行日志
# Please paste the run log here
```
WARNING 08-14 05:32:59 tokenizer.py:63] Using a slow tokenizer. This might cause a significant slowdown. Consider using a fast tokenizer instead.
Traceback (most recent call last):
  File "api/vllm_server.py", line 14, in <module>
    from api.vllm_routes import chat_router, completion_router
  File "/workspace/./api/vllm_routes/__init__.py", line 1, in <module>
    from api.vllm_routes.chat import chat_router
  File "/workspace/./api/vllm_routes/chat.py", line 20, in <module>
    from api.models import VLLM_ENGINE
  File "/workspace/./api/models.py", line 87, in <module>
    VLLM_ENGINE = get_vllm_engine() if config.USE_VLLM else None
  File "/workspace/./api/models.py", line 65, in get_vllm_engine
    engine = AsyncLLMEngine.from_engine_args(engine_args)
  File "/usr/local/lib/python3.8/dist-packages/vllm/engine/async_llm_engine.py", line 232, in from_engine_args
    engine = cls(engine_args.worker_use_ray,
  File "/usr/local/lib/python3.8/dist-packages/vllm/engine/async_llm_engine.py", line 55, in __init__
    self.engine = engine_class(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/vllm/engine/llm_engine.py", line 101, in __init__
    self._init_workers(distributed_init_method)
  File "/usr/local/lib/python3.8/dist-packages/vllm/engine/llm_engine.py", line 119, in _init_workers
    from vllm.worker.worker import Worker  # pylint: disable=import-outside-toplevel
  File "/usr/local/lib/python3.8/dist-packages/vllm/worker/worker.py", line 10, in <module>
    from vllm.model_executor import get_model, InputMetadata, set_random_seed
  File "/usr/local/lib/python3.8/dist-packages/vllm/model_executor/__init__.py", line 2, in <module>
    from vllm.model_executor.model_loader import get_model
  File "/usr/local/lib/python3.8/dist-packages/vllm/model_executor/model_loader.py", line 9, in <module>
    from vllm.model_executor.models import *  # pylint: disable=wildcard-import
  File "/usr/local/lib/python3.8/dist-packages/vllm/model_executor/models/__init__.py", line 1, in <module>
    from vllm.model_executor.models.baichuan import (BaiChuanForCausalLM,
  File "/usr/local/lib/python3.8/dist-packages/vllm/model_executor/models/baichuan.py", line 33, in <module>
    from vllm.model_executor.layers.activation import SiluAndMul
  File "/usr/local/lib/python3.8/dist-packages/vllm/model_executor/layers/activation.py", line 5, in <module>
    from vllm import activation_ops
ImportError: /usr/local/lib/python3.8/dist-packages/vllm/activation_ops.cpython-38-x86_64-linux-gnu.so: undefined symbol: _ZN3c106detail14torchCheckFailEPKcS2_jRKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE

**Comment by xusenlinzy** [comment]
您好，请问您是本地启动吗？
本地启动方式需要将 torch 版本升级到 2.0.0 以上，再安装 vllm，推荐新建一个python环境：
https://github.com/xusenlinzy/api-for-open-llm/blob/master/docs/FAQ.md#%E6%9C%AC%E5%9C%B0%E7%8E%AF%E5%A2%83

**Comment by foxxxx001** [comment]
docker运行，也需要本地安装vllm和torch?

**Comment by foxxxx001** [comment]
docker run -it -d --gpus all --ipc=host --net=host -p 8282:8282 --name=vllm-server \
    --ulimit memlock=-1 --ulimit stack=67108864 \
    -v `pwd`:/workspace \
    -v /data/model/starchat:/data/model/starchat \
    llm-api:vllm \
    python api/vllm_server.py

**Comment by xusenlinzy** [comment]
y

> docker运行，也需要本地安装vllm和torch?
不需要

**Comment by foxxxx001** [comment]
那这错误怎么回事，而且看日志，似乎vllm中调用百川，File "/usr/local/lib/python3.8/dist-packages/vllm/model_executor/models/init.py", line 1, in
from vllm.model_executor.models.baichuan import (BaiChuanForCausalLM,

**Comment by xusenlinzy** [comment]
之前我遇到这个问题，先将torch升级再安装vllm就没问题了

你的dockerfile内容是下面的这个吗

```
FROM nvcr.io/nvidia/pytorch:22.12-py3

WORKDIR /workspace/
ENV PYTHONPATH /workspace/
COPY requirements.txt /workspace/
COPY . /workspace

RUN pip install --no-cache-dir -r /workspace/requirements.txt -i https://mirror.baidu.com/pypi/simple
RUN pip install bitsandbytes --upgrade -i https://mirror.baidu.com/pypi/simple && \
    pip install torch -U -i https://mirror.baidu.com/pypi/simple && \
    pip install git+https://github.com/vllm-project/vllm.git && \
    pip uninstall transformer-engine -y
```

**Comment by xusenlinzy** [comment]
> 那这错误怎么回事，而且看日志，似乎vllm中调用百川，File "/usr/local/lib/python3.8/dist-packages/vllm/model_executor/models/init.py", line 1, in from vllm.model_executor.models.baichuan import (BaiChuanForCausalLM,

这个是因为vllm导入模块出错，还没到启动模型

**Comment by foxxxx001** [comment]
基本都按你的文档来，除了pip uninstall transformer-engine -y没有，另外几个git地址都直接用了pip中的，如 pip install git+https://github.com/vllm-project/vllm.git && ，替换为requirement中加入了vllm，因为git可能会访问不了，按说应该一样

**Comment by xusenlinzy** [comment]
> 基本都按你的文档来，除了pip uninstall transformer-engine -y没有，另外几个git地址都直接用了pip中的，如 pip install git+https://github.com/vllm-project/vllm.git && ，替换为requirement中加入了vllm，因为git可能会访问不了，按说应该一样

就是这里出问题了

**Comment by xusenlinzy** [comment]
必须要先升级torch，再安装vllm

**Comment by foxxxx001** [comment]
终于好了，非要git+https方式
