### ISSUE TITLE
💡 [REQUEST] - <title> 有什么办法可以让embedding模型的维度扩充到1536维吗，有些系统固定了1536维度，要怎么兼容

### ISSUE THREAD

**Issue by jinghai** [xusenlinzy/api-for-open-llm#66]
### 实现PR | Implementation PR

有什么办法可以让embedding模型的维度扩充到1536维吗，有些系统固定了1536维度，要怎么兼容

### 摘要 | Summary

有什么办法可以让embedding模型的维度扩充到1536维吗，有些系统固定了1536维度，要怎么兼容

### 基本示例 | Basic Example

有什么办法可以让embedding模型的维度扩充到1536维吗，有些系统固定了1536维度，要怎么兼容

### 缺陷 | Drawbacks

有什么办法可以让embedding模型的维度扩充到1536维吗，有些系统固定了1536维度，要怎么兼容

**Comment by xusenlinzy** [comment]
1536刚好是768的两倍，可以试试将每个句子的向量copy一遍拼接在后面？

**Comment by nlfiasel** [comment]
需要补充的部分应该直接填零就行？一般做相似度量是用余弦相似度，都填零的话一方面对计算结果不会有啥影响，另一方面也不会影响原向量的归一化。

**Comment by xusenlinzy** [comment]
填零确实比较合理，不会改变计算结果

```python
import numpy as np

vecs = EMBEDDED_MODEL.encode(batch, normalize_embeddings=True)
embedding = {
    "embedding": np.c_[vecs, np.zeros_like(vecs)].tolist(),
    "token_num": sum([len(i) for i in batch]),
}
```

**Comment by jinghai** [comment]
> 填零确实比较合理，用余弦相似度不会改变计算结果
> 
> ```python
> import numpy as np
> 
> vecs = EMBEDDED_MODEL.encode(batch, normalize_embeddings=True)
> embedding = {
>     "embedding": np.c_[vecs, np.zeros_like(vecs)].tolist(),
>     "token_num": sum([len(i) for i in batch]),
> }
> ```

建议在哪里加个配置，给需要1536维的人配置一下

**Comment by jinghai** [comment]
> 填零确实比较合理，用余弦相似度不会改变计算结果
> 
> ```python
> import numpy as np
> 
> vecs = EMBEDDED_MODEL.encode(batch, normalize_embeddings=True)
> embedding = {
>     "embedding": np.c_[vecs, np.zeros_like(vecs)].tolist(),
>     "token_num": sum([len(i) for i in batch]),
> }
> ```

这段代码要加到哪里，generate.py还是router.py，不太会加

**Comment by jinghai** [comment]
> 1536刚好是768的两倍，可以试试将每个句子的向量copy一遍拼接在后面？
> 
> 修改 https://github.com/xusenlinzy/api-for-open-llm/blob/master/api/routes/embedding.py#L49
> 
> ```python
> import numpy as np
> 
> vecs = EMBEDDED_MODEL.encode(batch, normalize_embeddings=True)
> embedding = {
>     "embedding": np.c_[vecs, vecs].tolist(),
>     "token_num": sum([len(i) for i in batch]),
> }
> ```

哦，我看到了，谢谢

**Comment by xusenlinzy** [comment]
最新代码已更新，设置 `EMBEDDING_SIZE` 环境变量就行了

**Comment by jinghai** [comment]
> 最新代码已更新，设置 `EMBEDDING_SIZE` 环境变量就行了

最近项目变化有点大，才几天没看，就不太一样了，问一下vLLM可以适用于所有模型吗？

**Comment by xusenlinzy** [comment]
支持的模型：https://vllm.readthedocs.io/en/latest/models/supported_models.html

**Comment by jinghai** [comment]
> 最新代码已更新，设置 `EMBEDDING_SIZE` 环境变量就行了

请问一下，原先加在Docker启动命令中的参考现在还生效吗，比如：
--model_name chatglm \
    --model_path models/chatglm-6b \
    --device cuda \
    --gpus 2 \
    --num_gpus 1 \

**Comment by xusenlinzy** [comment]
不行了，现在改为使用环境变量控制参数了

使用方式见 https://github.com/xusenlinzy/api-for-open-llm/blob/master/docs/SCRIPT.md
