### ISSUE TITLE
💡 [REQUEST] - <title>QWen模型流失问答输出个不停，不知道什么问题

### ISSUE THREAD

**Issue by jinghai** [xusenlinzy/api-for-open-llm#68]
### 摘要 | Summary

![image](https://github.com/xusenlinzy/api-for-open-llm/assets/5433705/a3d961f1-dd40-4245-b7d4-bac095ce67fd)

### 基本示例 | Basic Example

![image](https://github.com/xusenlinzy/api-for-open-llm/assets/5433705/6f6141f1-ad6f-40cf-9cac-19f2fb5b7b34)

### 缺陷 | Drawbacks

Docker启动，vllm和非vllm效果都一样

**Comment by xusenlinzy** [comment]
看一下你的 `.env` 文件

**Comment by jinghai** [comment]
MODEL_NAME=qwen
MODEL_PATH=models/Qwen-7B
EMBEDDING_NAME=models/m3e-base
ADAPTER_MODEL_PATH=
QUANTIZE=16
CONTEXT_LEN=
LOAD_IN_8BIT=false
LOAD_IN_4BIT=false
USING_PTUNING_V2=false
STREAM_INTERVERL=2
PROMPT_NAME=

# device related
DEVICE=cuda
DEVICE_MAP=
GPUS=0
NUM_GPUs=1

# patch related
PATCH_TYPE=
TRAINING_LENGTH=4096
WINDOW_SIZE=512

# api related
API_PREFIX=/v1

**Comment by xusenlinzy** [comment]
模型是 `Qwen/Qwen-7B-Chat` 还是 `Qwen/Qwen-7B`，`Qwen/Qwen-7B`是预训练模型 ，`Qwen/Qwen-7B-Chat` 是对话模型，是不是，一般使用对话模型进行对话

**Comment by jinghai** [comment]
当前用的是Qwen/Qwen-7B，刚才env里少了vllm配置，我加上看看

**Comment by xusenlinzy** [comment]
> 当前用的是Qwen/Qwen-7B，刚才env里少了vllm配置，我加上看看

默认是不使用vllm的，Qwen/Qwen-7B模型的话是会出现这种情况的

**Comment by jinghai** [comment]
增加了：
#vllm related
USE_VLLM=true
TRUST_REMOTE_CODE=true
TOKENIZE_MODE=slow
TENSOR_PARALLEL_SIZE=1
DTYPE=half
使用vllm的Docker启动后报错
![image](https://github.com/xusenlinzy/api-for-open-llm/assets/5433705/c0c43e1b-b9ce-40fb-b3ad-ddc34d03709f)

**Comment by jinghai** [comment]
好的，我试一下7B-Chat

**Comment by jinghai** [comment]
![image](https://github.com/xusenlinzy/api-for-open-llm/assets/5433705/379a0f56-fa69-4877-9966-8e1902f3f737)
Qwen-7B-Chat也是一样

**Comment by xusenlinzy** [comment]
![image](https://github.com/xusenlinzy/api-for-open-llm/assets/111472355/95cce231-fb7f-4fa7-96db-8c836e41e595)

```
PORT=7891

# model related
MODEL_NAME=qwen
MODEL_PATH=checkpoints/qwen-7b-chat
EMBEDDING_NAME=checkpoints/m3e-base
PROMPT_NAME=

# api related
API_PREFIX=/v1

# vllm related
USE_VLLM=true
TRUST_REMOTE_CODE=true
TOKENIZE_MODE=slow
TENSOR_PARALLEL_SIZE=1
DTYPE=half
EMBEDDING_SIZE=1536
```

**Comment by xusenlinzy** [comment]
你启动的是 `api/vllm_server` 吗

**Comment by jinghai** [comment]
> 你启动的是 `python api/vllm_server.py` 吗

Sorry,启动错了api/server.py

**Comment by jinghai** [comment]
7B-Chat模型可以，为什么7B不行呢， https://opencompass.org.cn/leaderboard-llm，这里7B的评分很高

**Comment by xusenlinzy** [comment]
7B-Chat是7B针对对话数据优化过的模型，7B是基座模型，不给充足的提示的话，就是续写，所以对话模式下会这样。榜单评测主要是上下文学习能力和知识储备能力

**Comment by jinghai** [comment]
> EMBEDDING_SIZE=1536

![image](https://github.com/xusenlinzy/api-for-open-llm/assets/5433705/da968080-2b6c-4fec-864d-5e7d66de9267)
问到特定的问题时会报错

**Comment by xusenlinzy** [comment]
什么问题

**Comment by xusenlinzy** [comment]
看样子是长度问题，已更新代码

**Comment by jinghai** [comment]
> 看样子是长度问题，已更新代码

好像是，只在vllm下有问题，不使用vllm没有问题，

**Comment by jinghai** [comment]
> 看样子是长度问题，已更新代码
目前API中有强制的长度限制吗，如果用GLM2-16K版本会有问题吗？

**Comment by xusenlinzy** [comment]
不会

**Comment by jinghai** [comment]
建议：可以用docker-compose.yml管理，下午写了一个参考：
version: "3.9"

services:
  llm-api:
    image: llm-api:0.0.5
    container_name: llm-prod
    restart: always
    ports:
      - "6009:8000"
    ulimits:
      stack: 67108864
      memlock: -1
    environment:
      - PORT=8000
      - MODEL_NAME=qwen
      - MODEL_PATH=models/Qwen-7B-Chat
      - EMBEDDING_NAME=models/m3e-base
      - EMBEDDING_SIZE=1536
      - GPUS=3
      - NUM_GPUs=1
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [gpu]
    volumes:
      - /data0/models:/workspace/models 
    command: python api/server.py
