### ISSUE TITLE
vllm下，启动Qwen-7B-Chat 报错

### ISSUE THREAD

**Issue by xcpuma** [xusenlinzy/api-for-open-llm#69]
### 提交前必须检查以下项目 | The following items must be checked before submission

- [X] 请确保使用的是仓库最新代码（git pull），一些问题已被解决和修复。 | Make sure you are using the latest code from the repository (git pull), some issues have already been addressed and fixed.
- [X] 我已阅读[项目文档](https://github.com/xusenlinzy/api-for-open-llm/blob/master/README.md)和[FAQ章节](https://github.com/xusenlinzy/api-for-open-llm/blob/master/docs/FAQ.md)并且已在Issue中对问题进行了搜索，没有找到相似问题和解决方案 | I have searched the existing issues / discussions

### 问题类型 | Type of problem

None

### 操作系统 | Operating system

None

### 详细描述问题 | Detailed description of the problem

CUDA_VISIBLE_DEVICES=1,2 python api/vllm_server.py

ValueError: Model architectures ['QWenLMHeadModel'] are not supported for now. Supported architectures: ['BaiChuanForCausalLM', 'BaichuanForCausalLM', 'BloomForCausalLM', 'FalconForCausalLM', 'GPT2LMHeadModel', 'GPTBigCodeForCausalLM', 'GPTJForCausalLM', 'GPTNeoXForCausalLM', 'LlamaForCausalLM', 'LLaMAForCausalLM', 'MPTForCausalLM', 'OPTForCausalLM', 'RWForCausalLM']

### Dependencies

```
# 请在此处粘贴依赖情况
# Please paste the dependencies here
```

**Comment by xusenlinzy** [comment]
您好，pip安装vllm不支持qwen模型，请从源码安装

```
pip install git+https://github.com/vllm-project/vllm.git
```

**Comment by xcpuma** [comment]
vllm api服务启动成功。但调用是报错，如下：
Retrying langchain.chat_models.openai.ChatOpenAI.completion_with_retry.<locals>._completion_with_retry in 4.0 seconds as it raised APIError: Invalid response object from API: '{"detail":"Not Found"}' (HTTP response code was 404).

**Comment by xusenlinzy** [comment]
我测试是没有问题的

```python
import os

os.environ["OPENAI_API_BASE"] = "http://192.168.0.53:7891/v1"
os.environ["OPENAI_API_KEY"] = "xxx"

from langchain.chat_models import ChatOpenAI
from langchain.schema import HumanMessage

chat = ChatOpenAI()
print(chat([HumanMessage(content="你好")]))
```

```
content='你好! 很高兴能为你提供帮助。' additional_kwargs={} example=False
```

**Comment by xcpuma** [comment]
@xusenlinzy 我的问题，配置文件.env中，vllm改为True就运行正常了，vllm确实快了好多，谢谢你的及时回复。另外，api控制台日志输出prompt 变成了prompt token ids,这个不方便观察啊，能还是prompt输出么？

**Comment by xusenlinzy** [comment]
如果想要观察拼接之后的prompt长什么样，你可以在 

https://github.com/xusenlinzy/api-for-open-llm/blob/master/api/generation/qwen.py#L57

加上一行

```python
if messages[-1].role != Role.ASSISTANT:
    input_tokens += nl_tokens + im_start_tokens + tokenizer.encode("assistant") + nl_tokens
print(tokenizer.decode(input_tokens))
```
