### ISSUE TITLE
关于模型异步调用的问题

### ISSUE THREAD

**Issue by Isfate** [xusenlinzy/api-for-open-llm#70]
### 提交前必须检查以下项目 | The following items must be checked before submission

- [X] 请确保使用的是仓库最新代码（git pull），一些问题已被解决和修复。 | Make sure you are using the latest code from the repository (git pull), some issues have already been addressed and fixed.
- [X] 我已阅读[项目文档](https://github.com/xusenlinzy/api-for-open-llm/blob/master/README.md)和[FAQ章节](https://github.com/xusenlinzy/api-for-open-llm/blob/master/docs/FAQ.md)并且已在Issue中对问题进行了搜索，没有找到相似问题和解决方案 | I have searched the existing issues / discussions

### 问题类型 | Type of problem

模型推理和部署 | Model inference and deployment

### 操作系统 | Operating system

Linux

### 详细描述问题 | Detailed description of the problem

目前项目具备多用户同时调用模型推理的能力么

### Dependencies

```
# 请在此处粘贴依赖情况
# Please paste the dependencies here
```

### 运行日志或截图 | Runtime logs or screenshots

```
# 请在此处粘贴运行日志
# Please paste the run log here
```

**Comment by xusenlinzy** [comment]
项目中提供了两种方式

第一种参考：https://github.com/xusenlinzy/api-for-open-llm/blob/master/docs/SCRIPT.md

该方式每次只能处理一个请求

第二种方式：https://github.com/xusenlinzy/api-for-open-llm/blob/master/docs/VLLM_SCRIPT.md

该方式支持并发请求，推理速度也有提升

**Comment by Isfate** [comment]
我在离线安装vllm, 在我已经将ninja(vllm的依赖包)安装后, 在编译vllm时仍需要网络下载ninja
![image](https://github.com/xusenlinzy/api-for-open-llm/assets/49968353/e03122d9-5815-48e4-9eea-2d9ba932faee)
![image](https://github.com/xusenlinzy/api-for-open-llm/assets/49968353/8f4a808e-04c8-4507-a2de-4c59e2cea9be)
![image](https://github.com/xusenlinzy/api-for-open-llm/assets/49968353/22372f2e-f193-4080-9689-80c06ca534a5)
