### ISSUE TITLE
可以提供一个公共的api供其他电脑使用吗？

### ISSUE THREAD

**Issue by 15899885850** [xusenlinzy/api-for-open-llm#71]
### 提交前必须检查以下项目 | The following items must be checked before submission

- [X] 请确保使用的是仓库最新代码（git pull），一些问题已被解决和修复。 | Make sure you are using the latest code from the repository (git pull), some issues have already been addressed and fixed.
- [X] 我已阅读[项目文档](https://github.com/xusenlinzy/api-for-open-llm/blob/master/README.md)和[FAQ章节](https://github.com/xusenlinzy/api-for-open-llm/blob/master/docs/FAQ.md)并且已在Issue中对问题进行了搜索，没有找到相似问题和解决方案 | I have searched the existing issues / discussions

### 问题类型 | Type of problem

其他问题 | Other issues

### 操作系统 | Operating system

Linux

### 详细描述问题 | Detailed description of the problem

目前我在autodl上已经部署了llama2的项目，并且得到了一个公网的url可以访问webui的界面，但是我现在的想法是，在云端上运行llama2的服务，如何开启一个公共的api提供给其他电脑进行使用？望回复，谢谢！

### Dependencies

```
# 请在此处粘贴依赖情况
# Please paste the dependencies here
```

### 运行日志或截图 | Runtime logs or screenshots

```
# 请在此处粘贴运行日志
# Please paste the run log here
```

**Comment by xusenlinzy** [comment]
您好，你可以参考 https://github.com/xusenlinzy/api-for-open-llm/blob/master/docs/VLLM_SCRIPT.md 
在云端配置好vllm的环境以及相关的环境变量，然后基于本项目执行 `python api/vllm_server.py` 提供对话接口

**Comment by 15899885850** [comment]
> 您好，你可以参考 https://github.com/xusenlinzy/api-for-open-llm/blob/master/docs/VLLM_SCRIPT.md 在云端配置好vllm的环境以及相关的环境变量，然后基于本项目执行 `python api/vllm_server.py` 提供对话接口

谢谢！我会进行尝试！
