### ISSUE TITLE
💡 [REQUEST] - <title>可以单独配置embedding模型使用CPU资源吗？

### ISSUE THREAD

**Issue by jinghai** [xusenlinzy/api-for-open-llm#72]
### 实现PR | Implementation PR

节省GPU内存

### 摘要 | Summary

节省GPU内存

### 基本示例 | Basic Example

节省GPU内存

### 缺陷 | Drawbacks

节省GPU内存

**Comment by xusenlinzy** [comment]
你可以试试使用最新代码，设置环境变量 `EMBEDDING_DEVICE`

`EMBEDDING_DEVICE=cpu`: 使用 `cpu`

`EMBEDDING_DEVICE=cuda`: 使用 `gpu`

也可以设置

`EMBEDDING_DEVICE=cuda:3`: 使用 3 号 `gpu`

**Comment by jinghai** [comment]
谢谢
