### ISSUE TITLE
构建vllm的镜像卡在 Installing build dependencies: started

### ISSUE THREAD

**Issue by bh4ffu** [xusenlinzy/api-for-open-llm#73]
### 提交前必须检查以下项目 | The following items must be checked before submission

- [X] 请确保使用的是仓库最新代码（git pull），一些问题已被解决和修复。 | Make sure you are using the latest code from the repository (git pull), some issues have already been addressed and fixed.
- [X] 我已阅读[项目文档](https://github.com/xusenlinzy/api-for-open-llm/blob/master/README.md)和[FAQ章节](https://github.com/xusenlinzy/api-for-open-llm/blob/master/docs/FAQ.md)并且已在Issue中对问题进行了搜索，没有找到相似问题和解决方案 | I have searched the existing issues / discussions

### 问题类型 | Type of problem

安装环境 | Installation environment

### 操作系统 | Operating system

Linux

### 详细描述问题 | Detailed description of the problem

```
# 请在此处粘贴运行代码（如没有可删除该代码块）
# Paste the runtime code here (delete the code block if you don't have it)
```

### Dependencies

```
# 请在此处粘贴依赖情况
# Please paste the dependencies here
```

### 运行日志或截图 | Runtime logs or screenshots

![image](https://github.com/xusenlinzy/api-for-open-llm/assets/113177453/114abeb4-c224-4b57-aaee-c80b04db4248)

**Comment by xusenlinzy** [comment]
没有卡住，安装vllm这个包比较耗时间。。我安装了差不多半小时

**Comment by xusenlinzy** [comment]
好像是要的

**Comment by bh4ffu** [comment]
确认是网络的问题，换了个pip源解决了，感谢！
