### ISSUE TITLE
VLLM运行Qwen报错

### ISSUE THREAD

**Issue by jinghai** [xusenlinzy/api-for-open-llm#75]
### 提交前必须检查以下项目 | The following items must be checked before submission

- [X] 请确保使用的是仓库最新代码（git pull），一些问题已被解决和修复。 | Make sure you are using the latest code from the repository (git pull), some issues have already been addressed and fixed.
- [X] 我已阅读[项目文档](https://github.com/xusenlinzy/api-for-open-llm/blob/master/README.md)和[FAQ章节](https://github.com/xusenlinzy/api-for-open-llm/blob/master/docs/FAQ.md)并且已在Issue中对问题进行了搜索，没有找到相似问题和解决方案 | I have searched the existing issues / discussions

### 问题类型 | Type of problem

其他问题 | Other issues

### 操作系统 | Operating system

Linux

### 详细描述问题 | Detailed description of the problem

```
# 请在此处粘贴运行代码（如没有可删除该代码块）
# Paste the runtime code here (delete the code block if you don't have it)
```
简短聊天正常，带知识库prompt比较长时报错

### Dependencies

```
# 请在此处粘贴依赖情况
# Please paste the dependencies here
```
简短聊天正常，带知识库prompt比较长时报错

### 运行日志或截图 | Runtime logs or screenshots

```
# 请在此处粘贴运行日志
# Please paste the run log here
```
![image](https://github.com/xusenlinzy/api-for-open-llm/assets/5433705/06ce7ffd-ebf7-4106-b684-2c2efb2d4227)

**Comment by xusenlinzy** [comment]
镜像里面的代码没有更新，需要将本项目的代码挂载到容器里

```
$PWD:/workspace
```

**Comment by jinghai** [comment]
更换最新代码，原先非llm接口也报500，无错误日志输出，vllm也是一样。embedding接口貌似也在报错

**Comment by jinghai** [comment]
另外，每次打包vllm都要花1到2个小时，建议做个打包好的基础镜像

**Comment by jinghai** [comment]
再另外，llama2模型：Llama-2-7b-chat-hf 没有返回结果
model_name llama2
model_path Llama-2-7b-chat-hf

**Comment by xusenlinzy** [comment]
> 更换最新代码，原先llm接口也报500，无错误日志输出，vllm也是一样。embedding接口貌似也在报错

embedding接口有问题吗，我试了一下，没问题

![image](https://github.com/xusenlinzy/api-for-open-llm/assets/111472355/fc4ea48c-e621-4232-80c0-25fcda9af20d)

**Comment by xusenlinzy** [comment]
> 另外，每次打包vllm都要花1到2个小时，建议做个打包好的基础镜像

其实不需要重新打包镜像的，环境不变，更新的是代码，只需要在docker-compose文件中的volumes添加一个代码挂载路径`      - $PWD:/workspace`就行

**Comment by xusenlinzy** [comment]
> 

![image](https://github.com/xusenlinzy/api-for-open-llm/assets/111472355/94d245cd-101a-4228-b93e-79c3849f6599)

我是从 https://huggingface.co/NousResearch/Llama-2-7b-chat-hf 下载的模型文件

如果有问题，对比一下special_tokens_map.json 和 config.json 文件
