### ISSUE TITLE
可不可以建个群交流啊

### ISSUE THREAD

**Issue by queensking** [xusenlinzy/api-for-open-llm#76]
### 提交前必须检查以下项目 | The following items must be checked before submission

- [X] 请确保使用的是仓库最新代码（git pull），一些问题已被解决和修复。 | Make sure you are using the latest code from the repository (git pull), some issues have already been addressed and fixed.
- [X] 我已阅读[项目文档](https://github.com/xusenlinzy/api-for-open-llm/blob/master/README.md)和[FAQ章节](https://github.com/xusenlinzy/api-for-open-llm/blob/master/docs/FAQ.md)并且已在Issue中对问题进行了搜索，没有找到相似问题和解决方案 | I have searched the existing issues / discussions

### 问题类型 | Type of problem

安装环境 | Installation environment

### 操作系统 | Operating system

Windows

### 详细描述问题 | Detailed description of the problem

```
# 请在此处粘贴运行代码（如没有可删除该代码块）
# Paste the runtime code here (delete the code block if you don't have it)
```

### Dependencies

```
(llmApi) D:\Projects\python\api-for-open-llm>pip install torch==1.14 --trusted-host pypi.org --trusted-host pypi.python.org --trusted-host=files.pythonhosted.org
ERROR: Could not find a version that satisfies the requirement torch==1.14 (from versions: 1.7.1, 1.8.0, 1.8.1, 1.9.0, 1.9.1, 1.10.0, 1.10.1, 1.10.2, 1.11.0, 1.12.0, 1.12.1, 1.13.0, 1.13.1, 2.0.0, 2.0.1)
ERROR: No matching distribution found for torch==1.14
```
能不能建个群交流啊

### 运行日志或截图 | Runtime logs or screenshots

```
# 请在此处粘贴运行日志
# Please paste the run log here
```

**Comment by xusenlinzy** [comment]
QQ交流群：870207830

**Comment by xusenlinzy** [comment]
可以试一试安装torch==1.13.1，应该也可以的
