### ISSUE TITLE
运行python api/server.py 后报错，ModuleNotFoundError: No module named 'api.config'

### ISSUE THREAD

**Issue by luchenwei9266** [xusenlinzy/api-for-open-llm#77]
### 提交前必须检查以下项目 | The following items must be checked before submission

- [X] 请确保使用的是仓库最新代码（git pull），一些问题已被解决和修复。 | Make sure you are using the latest code from the repository (git pull), some issues have already been addressed and fixed.
- [X] 我已阅读[项目文档](https://github.com/xusenlinzy/api-for-open-llm/blob/master/README.md)和[FAQ章节](https://github.com/xusenlinzy/api-for-open-llm/blob/master/docs/FAQ.md)并且已在Issue中对问题进行了搜索，没有找到相似问题和解决方案 | I have searched the existing issues / discussions

### 问题类型 | Type of problem

启动命令 | Startup command

### 操作系统 | Operating system

Linux

### 详细描述问题 | Detailed description of the problem

使用如下命令跑baichuan，结果报错了ModuleNotFoundError: No module named 'api.config'
```
 python api/server.py   
     --port 8085   
     --allow-credentials   
     --model_name baichuan-13b-chat   
     --model_path Baichuan-13B/Baichuan-13B-Chat   
     --device cuda   
     --DEVICE_MAP=auto
``` 

### Dependencies

```
# 请在此处粘贴依赖情况
# Please paste the dependencies here
```

### 运行日志或截图 | Runtime logs or screenshots

启动以后报如下错误
```
Traceback (most recent call last):
  File "server.py", line 8, in <module>
    from api.config import config
ModuleNotFoundError: No module named 'api.config'
```

**Comment by xusenlinzy** [comment]
现在参数改成环境变量了，只需要将 [.env.example](https://github.com/xusenlinzy/api-for-open-llm/blob/master/.env.example) 文件内容复制到 `.env` 文件中，然后修改 `.env` 文件中环境变量

```
MODEL_NAME=baichuan-13b-chat   
MODEL_PATH=Baichuan-13B/Baichuan-13B-Chat  
```

**Comment by luchenwei9266** [comment]
试了一下，不行，还是报这个错，
![image](https://github.com/xusenlinzy/api-for-open-llm/assets/9455826/d8623f51-3224-4726-a4c0-abf215c1ebe4)

**Comment by xusenlinzy** [comment]
还是不行的话，试试将 `api/server.py` 里面的

```python
import sys

sys.path.insert(0, ".")
```

替换为

```python
import os
import sys

parent_dir = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, parent_dir)
```

**Comment by xusenlinzy** [comment]
换成这个试试？ `os.path.dirname(os.path.dirname(os.path.abspath(__file__)))`  
`api.xxxx` 换回去

**Comment by luchenwei9266** [comment]
![image](https://github.com/xusenlinzy/api-for-open-llm/assets/9455826/7761b191-9064-43c6-9201-7a46880cac1d)


还是不行。。

**Comment by luchenwei9266** [comment]
解决了，可能是python版本问题。你之前的README里有建议用```conda```建一个3.8的版本，我是在那个环境下跑的。

```conda create -n pytorch python=3.8```

我在```base```环境下跑了一遍，```base```环境我的python是3.10。

![image](https://github.com/xusenlinzy/api-for-open-llm/assets/9455826/ca5d6740-7f35-4ad8-a842-d2f34353c526)
