### ISSUE TITLE
试了下，显存占用明显增加，模型用的Qwen-7B-chat，不知道啥原因

### ISSUE THREAD

**Issue by bh4ffu** [xusenlinzy/api-for-open-llm#78]
### 提交前必须检查以下项目 | The following items must be checked before submission

- [X] 请确保使用的是仓库最新代码（git pull），一些问题已被解决和修复。 | Make sure you are using the latest code from the repository (git pull), some issues have already been addressed and fixed.
- [X] 我已阅读[项目文档](https://github.com/xusenlinzy/api-for-open-llm/blob/master/README.md)和[FAQ章节](https://github.com/xusenlinzy/api-for-open-llm/blob/master/docs/FAQ.md)并且已在Issue中对问题进行了搜索，没有找到相似问题和解决方案 | I have searched the existing issues / discussions

### 问题类型 | Type of problem

模型推理和部署 | Model inference and deployment

### 操作系统 | Operating system

Linux

### 详细描述问题 | Detailed description of the problem

```
# 请在此处粘贴运行代码（如没有可删除该代码块）
# Paste the runtime code here (delete the code block if you don't have it)
```

### Dependencies

```
# 请在此处粘贴依赖情况
# Please paste the dependencies here
```

### 运行日志或截图 | Runtime logs or screenshots

dtype=torch.float16， 显存占用约27G。 
qwem官方的代码跑，只占用17,18G的样子

**Comment by xusenlinzy** [comment]
我这边的测试结果是

## 不使用vllm

### 环境变量

```
PORT=8000
MODEL_NAME=qwen
MODEL_PATH=checkpoints/qwen-7b-chat
DEVICE_MAP=auto
```
### 显存占用

16G

## 使用vllm

### 显存占用

20G

**Comment by bh4ffu** [comment]
https://github.com/vllm-project/vllm/discussions/241
