### ISSUE TITLE
starchat模型使用vllm推理乱码

### ISSUE THREAD

**Issue by skingko** [xusenlinzy/api-for-open-llm#79]
### 提交前必须检查以下项目 | The following items must be checked before submission

- [X] 请确保使用的是仓库最新代码（git pull），一些问题已被解决和修复。 | Make sure you are using the latest code from the repository (git pull), some issues have already been addressed and fixed.
- [X] 我已阅读[项目文档](https://github.com/xusenlinzy/api-for-open-llm/blob/master/README.md)和[FAQ章节](https://github.com/xusenlinzy/api-for-open-llm/blob/master/docs/FAQ.md)并且已在Issue中对问题进行了搜索，没有找到相似问题和解决方案 | I have searched the existing issues / discussions

### 问题类型 | Type of problem

效果问题 | Effectiveness issues

### 操作系统 | Operating system

Linux

### 详细描述问题 | Detailed description of the problem

centos系统，在不使用vllm推理时一切正常，其他模型使用vllm推理一切正常，推理模型为bigcode基于starcode微调模型，已经修改了正确的提示词，使用vllm推理速度很快，但是乱码

### Dependencies

peft                          0.5.0.dev0
sentence-transformers         2.2.2
torch                         2.0.1
torchaudio                    2.0.2
torchvision                   0.15.2
transformers                  4.31.0
transformers-stream-generator 0.0.4

### 运行日志或截图 | Runtime logs or screenshots

![image](https://github.com/xusenlinzy/api-for-open-llm/assets/131801581/d3342b40-9894-4ba3-ba9a-eb51914a31ea)

**Comment by xusenlinzy** [comment]
请问你使用的模型是HuggingFaceH4/starchat-beta吗

**Comment by skingko** [comment]
不是的，是同一家公司在starchat基础上微调的
https://github.com/bigcode-project/octopack

**Comment by xusenlinzy** [comment]
https://github.com/bigcode-project/octopack 这个项目采用的 `prompt` 模板变了

![image](https://github.com/xusenlinzy/api-for-open-llm/assets/111472355/a9edd3c2-a6a0-4d53-bf5e-8fcf022d00ab)

试一下拉去最新代码，并且指定 `PROMPT_NAME=octopack`
