### ISSUE TITLE
模型输出没有完毕前，客户端停止输出，服务端报错。

### ISSUE THREAD

**Issue by jinghai** [xusenlinzy/api-for-open-llm#80]
### 提交前必须检查以下项目 | The following items must be checked before submission

- [X] 请确保使用的是仓库最新代码（git pull），一些问题已被解决和修复。 | Make sure you are using the latest code from the repository (git pull), some issues have already been addressed and fixed.
- [X] 我已阅读[项目文档](https://github.com/xusenlinzy/api-for-open-llm/blob/master/README.md)和[FAQ章节](https://github.com/xusenlinzy/api-for-open-llm/blob/master/docs/FAQ.md)并且已在Issue中对问题进行了搜索，没有找到相似问题和解决方案 | I have searched the existing issues / discussions

### 问题类型 | Type of problem

模型推理和部署 | Model inference and deployment

### 操作系统 | Operating system

Linux

### 详细描述问题 | Detailed description of the problem

```
# 请在此处粘贴运行代码（如没有可删除该代码块）
# Paste the runtime code here (delete the code block if you don't have it)
```
llm docker启动，chatglm2模型，在模型输出没有完毕时，客户端停止输出，服务端报错

### Dependencies

```
# 请在此处粘贴依赖情况
# Please paste the dependencies here
```

### 运行日志或截图 | Runtime logs or screenshots

```
# 请在此处粘贴运行日志
# Please paste the run log here
```
![image](https://github.com/xusenlinzy/api-for-open-llm/assets/5433705/eed231ee-3077-4d19-a16a-45784caa318f)

**Comment by jinghai** [comment]
补充：后期发现这个现象本身是模型不断循环重复输出造成的，应该是模型本身的问题，chatglm2和千问都有发生过。
api项目里有没有什么办法能够发现这种重复输出，及时停止模型输出呢？

**Comment by jinghai** [comment]
前端：
![image](https://github.com/xusenlinzy/api-for-open-llm/assets/5433705/6b4a3161-966f-4e7a-830a-b7bc59cae8ed)
后端：
![image](https://github.com/xusenlinzy/api-for-open-llm/assets/5433705/733b15f0-92f9-454c-b0a2-970b933a4f29)
一重复就会重复好久，期间显卡资源都占用了

**Comment by jinghai** [comment]
![image](https://github.com/xusenlinzy/api-for-open-llm/assets/5433705/f3ca9bd5-5a6c-4224-b5c2-1e9d2dd0573e)
现象是这样的，后面还有好多重复，这是模型的问题吧，有什么办法可以在程序中控制吗？

**Comment by xusenlinzy** [comment]
https://github.com/xusenlinzy/api-for-open-llm/commit/e8eb4923bc797f40674947262fa1bd0b12f22839
刚刚增加了 `repetition_penalty` 参数调整生成，你试试 `repetition_penalty=1.1` 情况下还有重复吗

**Comment by jinghai** [comment]
请问repetition_penalty参数的作用是？

**Comment by jinghai** [comment]
> [e8eb492](https://github.com/xusenlinzy/api-for-open-llm/commit/e8eb4923bc797f40674947262fa1bd0b12f22839) 刚刚增加了 `repetition_penalty` 参数调整生成，你试试 `repetition_penalty=1.1` 情况下还有重复吗

这个参数在哪里配置？

**Comment by xusenlinzy** [comment]
> 请问repetition_penalty参数的作用是？

减轻模型重复生成的现象

**Comment by xusenlinzy** [comment]
> > [e8eb492](https://github.com/xusenlinzy/api-for-open-llm/commit/e8eb4923bc797f40674947262fa1bd0b12f22839) 刚刚增加了 `repetition_penalty` 参数调整生成，你试试 `repetition_penalty=1.1` 情况下还有重复吗
> 
> 这个参数在哪里配置？

https://github.com/xusenlinzy/api-for-open-llm/blob/e8eb4923bc797f40674947262fa1bd0b12f22839/api/utils/protocol.py#L95

新的代码里面默认设置成了1.1

**Comment by aoyifei** [comment]
> > > [e8eb492](https://github.com/xusenlinzy/api-for-open-llm/commit/e8eb4923bc797f40674947262fa1bd0b12f22839) 刚刚增加了 `repetition_penalty` 参数调整生成，你试试 `repetition_penalty=1.1` 情况下还有重复吗
> > 
> > 
> > 这个参数在哪里配置？
> 
> https://github.com/xusenlinzy/api-for-open-llm/blob/e8eb4923bc797f40674947262fa1bd0b12f22839/api/utils/protocol.py#L95
> 
> 新的代码里面默认设置成了1.1

这个设置看起来没有没有对code llama生效
![image](https://github.com/xusenlinzy/api-for-open-llm/assets/45986406/3758e7ff-dd01-4004-b12b-4b8f26704444)

![image](https://github.com/xusenlinzy/api-for-open-llm/assets/45986406/aecfdcb9-e6e2-485d-90dd-3af2edae5a47)

**Comment by Tendo33** [comment]
frequency penalty, presence penalty, repetition penalty 这三个参数都调整的话怎么起作用啊
