### ISSUE TITLE
💡 [REQUEST] - 是否支持chatglm2的多轮对话？

### ISSUE THREAD

**Issue by huanglx27** [xusenlinzy/api-for-open-llm#82]
### 摘要 | Summary

在chatglm自己的方法里，多轮对话是通过传入history，找了一下代码好像没有相关调用

### 基本示例 | Basic Example
```
for chunk in openai.ChatCompletion.create(
        model="chatglm2-6b",
        messages=[
            {"role": "user", "content": "你好"},{"role": "assistance", "content": "你好"}
        ],
        stream=True
    ):
        if hasattr(chunk.choices[0].delta, "content"):
            print(chunk.choices[0].delta.content, end="", flush=True)
```

### 缺陷 | Drawbacks

满足多轮会话需求

**Comment by xusenlinzy** [comment]
您好，本项目所有模型都是支持多轮对话的，多轮对话通过 `messages` 参数传入，根据不同的模型适配不同的 `prompt`，比如 `chatglm2` 采用的方式是：
https://github.com/xusenlinzy/api-for-open-llm/blob/master/api/apapter/conversation.py#L101
