### ISSUE TITLE
Qwen model outputs are different from Vllm server vs normal server.

### ISSUE THREAD

**Issue by monksgoyal** [xusenlinzy/api-for-open-llm#83]
### 提交前必须检查以下项目 | The following items must be checked before submission

- [X] 请确保使用的是仓库最新代码（git pull），一些问题已被解决和修复。 | Make sure you are using the latest code from the repository (git pull), some issues have already been addressed and fixed.
- [X] 我已阅读[项目文档](https://github.com/xusenlinzy/api-for-open-llm/blob/master/README.md)和[FAQ章节](https://github.com/xusenlinzy/api-for-open-llm/blob/master/docs/FAQ.md)并且已在Issue中对问题进行了搜索，没有找到相似问题和解决方案 | I have searched the existing issues / discussions

### 问题类型 | Type of problem

None

### 操作系统 | Operating system

None

### 详细描述问题 | Detailed description of the problem

```
# 请在此处粘贴运行代码（如没有可删除该代码块）
# Paste the runtime code here (delete the code block if you don't have it)
```

### Dependencies

```
# 请在此处粘贴依赖情况
# Please paste the dependencies here
```

### 运行日志或截图 | Runtime logs or screenshots

```
# 请在此处粘贴运行日志
# Please paste the run log here
```

**Comment by monksgoyal** [comment]
I tried running vllm server vs normal server to see difference in outputs and indeed realized the outputs are different in both the cases. 
I guess normal is running via standard huggingface implementation but Vllm one is implemented by vllm team. can some one confirm this.

**Comment by xusenlinzy** [comment]
Yes, they are different.

normal implementation :
https://github.com/xusenlinzy/api-for-open-llm/blob/master/api/generation/core.py#L22

vllm implementation :
https://github.com/vllm-project/vllm/blob/main/vllm/model_executor/layers/sampler.py

**Comment by monksgoyal** [comment]
vllm implementation is not fetching desired results at all, will vllm fix it ?

**Comment by monksgoyal** [comment]
@xusenlinzy any update here?
