### ISSUE TITLE
"GET /v1 HTTP/1.1" 404 Not Found

### ISSUE THREAD

**Issue by YunFenLei** [xusenlinzy/api-for-open-llm#84]
### 提交前必须检查以下项目 | The following items must be checked before submission

- [X] 请确保使用的是仓库最新代码（git pull），一些问题已被解决和修复。 | Make sure you are using the latest code from the repository (git pull), some issues have already been addressed and fixed.
- [X] 我已阅读[项目文档](https://github.com/xusenlinzy/api-for-open-llm/blob/master/README.md)和[FAQ章节](https://github.com/xusenlinzy/api-for-open-llm/blob/master/docs/FAQ.md)并且已在Issue中对问题进行了搜索，没有找到相似问题和解决方案 | I have searched the existing issues / discussions

### 问题类型 | Type of problem

启动命令 | Startup command

### 操作系统 | Operating system

Linux

### 详细描述问题 | Detailed description of the problem

```
# 请在此处粘贴运行代码（如没有可删除该代码块）
启动 api目录下的 server.py  通过访问IP:8000/v1，提示
{
    "detail": "Not Found"
}
```

### Dependencies

```
# 请在此处粘贴依赖情况
# Please paste the dependencies here
```

### 运行日志或截图 | Runtime logs or screenshots

```
# 请在此处粘贴运行日志
# Please paste the run log here
Config: {'HOST': '0.0.0.0', 'PORT': 8000, 'MODEL_NAME': 'baichuan-7b', 'MODEL_PATH': '/www/wwwroot/api/api/baichuan-inc/baichuan-7b', 'ADAPTER_MODEL_PATH': None, 'DEVICE': 'cuda', 'DEVICE_MAP': 'auto', 'GPUS': '', 'NUM_GPUs': 1, 'QUANTIZE': 16, 'EMBEDDING_NAME': '/www/wwwroot/api/api/moka-ai/m3e-base', 'CONTEXT_LEN': None, 'LOAD_IN_8BIT': False, 'LOAD_IN_4BIT': False, 'USING_PTUNING_V2': False, 'STREAM_INTERVERL': 2, 'PROMPT_NAME': None, 'PATCH_TYPE': None, 'TRAINING_LENGTH': 4096, 'WINDOW_SIZE': 512, 'API_PREFIX': '/v1', 'USE_VLLM': False, 'TRUST_REMOTE_CODE': False, 'TOKENIZE_MODE': 'auto', 'TENSOR_PARALLEL_SIZE': 1, 'DTYPE': 'half', 'EMBEDDING_SIZE': None, 'EMBEDDING_DEVICE': 'cuda'}
INFO: Started server process [24544]
INFO: Waiting for application startup.
INFO: Application startup complete.
INFO: Uvicorn running on http://0.0.0.0:8000 (Press CTRL+C to quit)
INFO: 192.168.123.115:52983 - "GET /v1 HTTP/1.1" 404 Not Found
```

**Comment by wuQi-666** [comment]
我是使用postman测试接口api的，其中访问的端口号是 ip:8000/v1/chat/completions  进行测试，可以返回结果，你看对你会不会有帮助
