### ISSUE TITLE
对于qwen模型，在使用completion接口时，decode参数存在的问题

### ISSUE THREAD

**Issue by nlfiasel** [xusenlinzy/api-for-open-llm#86]
### 提交前必须检查以下项目 | The following items must be checked before submission

- [X] 请确保使用的是仓库最新代码（git pull），一些问题已被解决和修复。 | Make sure you are using the latest code from the repository (git pull), some issues have already been addressed and fixed.
- [X] 我已阅读[项目文档](https://github.com/xusenlinzy/api-for-open-llm/blob/master/README.md)和[FAQ章节](https://github.com/xusenlinzy/api-for-open-llm/blob/master/docs/FAQ.md)并且已在Issue中对问题进行了搜索，没有找到相似问题和解决方案 | I have searched the existing issues / discussions

### 问题类型 | Type of problem

其他问题 | Other issues

### 操作系统 | Operating system

Windows

### 详细描述问题 | Detailed description of the problem

对于api/generation/core.py中generate_stream的实现，在使用completion接口时，对于qwen-7B的react_demo，行为不符合预期。

对于react_demo.py的修改如下：
```python
def text_completion(input_text: str, stop_words) -> str:  # 作为一个文本续写模型来使用
    im_end = '<|im_end|>'
    if im_end not in stop_words:
        stop_words = stop_words + [im_end]
    response = openai.Completion.create(
        model="qwen",
        prompt=input_text,
        temperature=0,
        stop=stop_words,
    )
    output = response.choices[0].text
    print(output)
    output = output.replace('<|endoftext|>', '').replace(im_end, '')
    for stop_str in stop_words:
        idx = output.find(stop_str)
        if idx != -1:
            output = output[: idx + len(stop_str)]
    return output  # 续写 input_text 的结果，不包含 input_text 的内容
```

与generate_stream实现相关的问题：
```python
output = tokenizer.decode(
     tmp_output_ids,
     skip_special_tokens=True, # 在使用completion接口时，为True存在问题，需要改为False避免跳过im_end
     spaces_between_special_tokens=False,
     clean_up_tokenization_spaces=True,
)
```

**Comment by xusenlinzy** [comment]
确实有这个 `bug`，代码已修正，测试代码见 https://github.com/xusenlinzy/api-for-open-llm/blob/master/examples/qwen_react_demo.py
