### ISSUE TITLE
执行sudo docker build -f docker/Dockerfile -t llm-api:pytorch . 命令中，远程连接仓库报错

### ISSUE THREAD

**Issue by xxs980** [xusenlinzy/api-for-open-llm#87]
### 提交前必须检查以下项目 | The following items must be checked before submission

- [X] 请确保使用的是仓库最新代码（git pull），一些问题已被解决和修复。 | Make sure you are using the latest code from the repository (git pull), some issues have already been addressed and fixed.
- [X] 我已阅读[项目文档](https://github.com/xusenlinzy/api-for-open-llm/blob/master/README.md)和[FAQ章节](https://github.com/xusenlinzy/api-for-open-llm/blob/master/docs/FAQ.md)并且已在Issue中对问题进行了搜索，没有找到相似问题和解决方案 | I have searched the existing issues / discussions

### 问题类型 | Type of problem

安装环境 | Installation environment

### 操作系统 | Operating system

Linux

### 详细描述问题 | Detailed description of the problem

![image](https://github.com/xusenlinzy/api-for-open-llm/assets/75365118/66dfc6d3-0008-4a69-92a5-ed7ff9844568)

### Dependencies

```
# 请在此处粘贴依赖情况
# Please paste the dependencies here
```

### 运行日志或截图 | Runtime logs or screenshots

```
# 请在此处粘贴运行日志
# Please paste the run log here
```

**Comment by xusenlinzy** [comment]
换个源或者把 `-i` 部分删掉试试

**Comment by xxs980** [comment]
> 换个源或者把 `-i` 部分删掉试试

你好呀，我尝试不要安装源，或则使用https://pypi.ngc.nvidia.com, https://pypi.ngc.nvidia.com 安装源都无法成功执行这一步，请问有合适的安装源吗

**Comment by xusenlinzy** [comment]
是不是网络问题

**Comment by xxs980** [comment]
![image](https://github.com/xusenlinzy/api-for-open-llm/assets/75365118/3c8a68de-cc5d-4430-8a96-db8a4e65f2c6)
能够ping通google

**Comment by xxs980** [comment]
> 是不是网络问题
![image](https://github.com/xusenlinzy/api-for-open-llm/assets/75365118/49e9c4ac-5a32-4d9c-af39-760a0dc4ee32)
能够ping通google

**Comment by xusenlinzy** [comment]
可能是代理的问题，你试试先把代理关了？

**Comment by xxs980** [comment]
代理关了也没用用处...
![image](https://github.com/xusenlinzy/api-for-open-llm/assets/75365118/abbfda55-9040-4f6e-9a65-ce63fc1b7d17)

**Comment by xusenlinzy** [comment]
好像是因为不能访问github的原因

**Comment by xxs980** [comment]
> 

好的   非常感谢hh
