### ISSUE TITLE
usage.first_tokens = content["usage"].get("first_tokens", None)

### ISSUE THREAD

**Issue by uulichen** [xusenlinzy/api-for-open-llm#88]
### 提交前必须检查以下项目 | The following items must be checked before submission

- [X] 请确保使用的是仓库最新代码（git pull），一些问题已被解决和修复。 | Make sure you are using the latest code from the repository (git pull), some issues have already been addressed and fixed.
- [X] 我已阅读[项目文档](https://github.com/xusenlinzy/api-for-open-llm/blob/master/README.md)和[FAQ章节](https://github.com/xusenlinzy/api-for-open-llm/blob/master/docs/FAQ.md)并且已在Issue中对问题进行了搜索，没有找到相似问题和解决方案 | I have searched the existing issues / discussions

### 问题类型 | Type of problem

其他问题 | Other issues

### 操作系统 | Operating system

None

### 详细描述问题 | Detailed description of the problem

completion返回时这里 first_tokens  是 None。
查看代码确实有这个问题：       
usage.first_tokens = content["usage"].get("first_tokens", None)

导致Langchain在回调统计token时拿first_tokens累加报错， 是不是应该改成0？

### Dependencies

```
# 请在此处粘贴依赖情况
# Please paste the dependencies here
```

### 运行日志或截图 | Runtime logs or screenshots

```
# 请在此处粘贴运行日志
# Please paste the run log here
```

**Comment by xusenlinzy** [comment]
您好，统计 `token` 数目不是通过下面三个属性值吗
![image](https://github.com/xusenlinzy/api-for-open-llm/assets/111472355/3231f010-c1b8-4745-84d2-25218fa7227c)

这个 `first_tokens ` 属性是我自己增加的，用来做选择题，因为选择题只需要第一个 `token`

**Comment by xusenlinzy** [comment]
![image](https://github.com/xusenlinzy/api-for-open-llm/assets/111472355/095a89f0-3128-439c-8679-babe01f7edd4)
看源码应该不会有影响，是不是langchain的版本问题

**Comment by uulichen** [comment]
https://api.python.langchain.com/en/latest/_modules/langchain/chat_models/openai.html#ChatOpenAI
308行 
    def _combine_llm_outputs(self, llm_outputs: List[Optional[dict]]) -> dict:
        overall_token_usage: dict = {}
        for output in llm_outputs:
            if output is None:
                # Happens in streaming
                continue
            token_usage = output["token_usage"]
            for k, v in token_usage.items():
                if k in overall_token_usage:
                    overall_token_usage[k] += v
                else:
                    overall_token_usage[k] = v
        return {"token_usage": overall_token_usage, "model_name": self.model_name}

通过调用 get_openai_callback（）  的 total_tokens方法会走到这里

**Comment by xusenlinzy** [comment]
确实，`OpenAI` 类做了限制，`ChatOpenAI` 没有做限制

**Comment by xusenlinzy** [comment]
我把 `first_tokens` 相关的代码删了，你拉取最新的代码试试
