### ISSUE TITLE
[help]考虑支持一下codellama吧？

### ISSUE THREAD

**Issue by bh4ffu** [xusenlinzy/api-for-open-llm#90]
### 提交前必须检查以下项目 | The following items must be checked before submission

- [X] 请确保使用的是仓库最新代码（git pull），一些问题已被解决和修复。 | Make sure you are using the latest code from the repository (git pull), some issues have already been addressed and fixed.
- [X] 我已阅读[项目文档](https://github.com/xusenlinzy/api-for-open-llm/blob/master/README.md)和[FAQ章节](https://github.com/xusenlinzy/api-for-open-llm/blob/master/docs/FAQ.md)并且已在Issue中对问题进行了搜索，没有找到相似问题和解决方案 | I have searched the existing issues / discussions

### 问题类型 | Type of problem

其他问题 | Other issues

### 操作系统 | Operating system

Linux

### 详细描述问题 | Detailed description of the problem

支持一下codellama

### Dependencies

```
# 请在此处粘贴依赖情况
# Please paste the dependencies here
```

### 运行日志或截图 | Runtime logs or screenshots

```
# 请在此处粘贴运行日志
# Please paste the run log here
```

**Comment by WCwalker** [comment]
加载 code-llama后出现以下问题: 1. 代码颜色不清楚；2.出现莫名类似html的 代码
![1693214991405](https://github.com/xusenlinzy/api-for-open-llm/assets/36464439/f99e732c-dd2b-4115-a7d9-5e38d9ace32f)

**Comment by xusenlinzy** [comment]
![image](https://github.com/xusenlinzy/api-for-open-llm/assets/111472355/ebde554f-1c2e-49fb-b866-c5f336be4258)
这是我跑的结果，可能是gradio的版本问题，你试试安装gradio==3.28.0

**Comment by WCwalker** [comment]
我请教一下为什么codellama会返回很多个 ‘\n’，应该怎么处理
