### ISSUE TITLE
新代码运行报错

### ISSUE THREAD

**Issue by xsun15** [xusenlinzy/api-for-open-llm#91]
### 提交前必须检查以下项目 | The following items must be checked before submission

- [X] 请确保使用的是仓库最新代码（git pull），一些问题已被解决和修复。 | Make sure you are using the latest code from the repository (git pull), some issues have already been addressed and fixed.
- [X] 我已阅读[项目文档](https://github.com/xusenlinzy/api-for-open-llm/blob/master/README.md)和[FAQ章节](https://github.com/xusenlinzy/api-for-open-llm/blob/master/docs/FAQ.md)并且已在Issue中对问题进行了搜索，没有找到相似问题和解决方案 | I have searched the existing issues / discussions

### 问题类型 | Type of problem

None

### 操作系统 | Operating system

None

### 详细描述问题 | Detailed description of the problem

```
# 请在此处粘贴运行代码（如没有可删除该代码块）
# Paste the runtime code here (delete the code block if you don't have it)
```
huggingface_hub.utils._validators.HFValidationError: Repo id must use alphanumeric chars or '-', '_', '.', '--' and '..' are forbidden, '-' and '.' cannot start or end the name, max length is 96: ''

### Dependencies

```
# 请在此处粘贴依赖情况
# Please paste the dependencies here
```

### 运行日志或截图 | Runtime logs or screenshots

```
# 请在此处粘贴运行日志
# Please paste the run log here
```

**Comment by xusenlinzy** [comment]
您好，这个是模型路径的问题，请检查您的文件路径有没有问题

**Comment by xsun15** [comment]
好的，多谢哈。我后来直接修改py文件了，就可以了（之前是通过命令行传参的，10号之前的版本可以，这个版本不行）
```json
export CUDA_VISIBLE_DEVICES=0
python api/app.py \
    --port 8093 \
    --allow-credentials \
    --model_name baichuan-13b-chat \
    --model_path export_model_0826_18000 \
    --device cuda
```
