### ISSUE TITLE
13B模型量化加载提示显存溢出

### ISSUE THREAD

**Issue by chelovek21** [xusenlinzy/api-for-open-llm#92]
### 提交前必须检查以下项目 | The following items must be checked before submission

- [X] 请确保使用的是仓库最新代码（git pull），一些问题已被解决和修复。 | Make sure you are using the latest code from the repository (git pull), some issues have already been addressed and fixed.
- [X] 我已阅读[项目文档](https://github.com/xusenlinzy/api-for-open-llm/blob/master/README.md)和[FAQ章节](https://github.com/xusenlinzy/api-for-open-llm/blob/master/docs/FAQ.md)并且已在Issue中对问题进行了搜索，没有找到相似问题和解决方案 | I have searched the existing issues / discussions

### 问题类型 | Type of problem

None

### 操作系统 | Operating system

None

### 详细描述问题 | Detailed description of the problem

```
# 请在此处粘贴运行代码（如没有可删除该代码块）
# Paste the runtime code here (delete the code block if you don't have it)
```
每次单卡加载13B模型，会提示显存不够溢出。
BaseModelAdapter里面的load_model函数调整一下，先默认将模型加载到CPU，然后做量化加载到GPU。
现在的情况下，13B的模型24G单卡根本跑步起来，总是提示显存溢出。
谢谢

### Dependencies

```
# 请在此处粘贴依赖情况
# Please paste the dependencies here
```

### 运行日志或截图 | Runtime logs or screenshots

```
# 请在此处粘贴运行日志
# Please paste the run log here
```

**Comment by xusenlinzy** [comment]
您好，BaseModelAdapter里面的load_model有先默认将模型加载到CPU，然后做量化加载到GPU的逻辑，修改环境变量DEVICE_MAP=和DEVICE=cuda应该就行了

**Comment by chelovek21** [comment]
好的，感谢
