### ISSUE TITLE
现在启动模式使用环境变量配置，如果我需要在一台机器上启动2个模型实例，如何配置？

### ISSUE THREAD

**Issue by anyshu** [xusenlinzy/api-for-open-llm#93]
### 提交前必须检查以下项目 | The following items must be checked before submission

- [X] 请确保使用的是仓库最新代码（git pull），一些问题已被解决和修复。 | Make sure you are using the latest code from the repository (git pull), some issues have already been addressed and fixed.
- [X] 我已阅读[项目文档](https://github.com/xusenlinzy/api-for-open-llm/blob/master/README.md)和[FAQ章节](https://github.com/xusenlinzy/api-for-open-llm/blob/master/docs/FAQ.md)并且已在Issue中对问题进行了搜索，没有找到相似问题和解决方案 | I have searched the existing issues / discussions

### 问题类型 | Type of problem

启动命令 | Startup command

### 操作系统 | Operating system

Linux

### 详细描述问题 | Detailed description of the problem

```
# 请在此处粘贴运行代码（如没有可删除该代码块）
# Paste the runtime code here (delete the code block if you don't have it)
```

### Dependencies

```
# 请在此处粘贴依赖情况
# Please paste the dependencies here
```

### 运行日志或截图 | Runtime logs or screenshots

```
# 请在此处粘贴运行日志
# Please paste the run log here
```

**Comment by xusenlinzy** [comment]
分别启动两个模型，每个模型修改对应的环境变量，例如

```
# 启动chatglm
PORT=8000
MODEL_NAME=qwen
MODEL_PATH=Qwen/Qwen-7B-Chat
DEVICE_MAP=auto

CUDA_VISIBLE_DEVICES=0 python python api/server.py


# 启动qwen
PORT=8001
MODEL_NAME=chatglm2
MODEL_PATH=THUDM/chatglm2-6b
DEVICE_MAP=auto

CUDA_VISIBLE_DEVICES=1 python api/server.py
```
