### ISSUE TITLE
codellama-34b-instruct-hf 回复内容出现截断

### ISSUE THREAD

**Issue by anyshu** [xusenlinzy/api-for-open-llm#97]
### 提交前必须检查以下项目 | The following items must be checked before submission

- [X] 请确保使用的是仓库最新代码（git pull），一些问题已被解决和修复。 | Make sure you are using the latest code from the repository (git pull), some issues have already been addressed and fixed.
- [X] 我已阅读[项目文档](https://github.com/xusenlinzy/api-for-open-llm/blob/master/README.md)和[FAQ章节](https://github.com/xusenlinzy/api-for-open-llm/blob/master/docs/FAQ.md)并且已在Issue中对问题进行了搜索，没有找到相似问题和解决方案 | I have searched the existing issues / discussions

### 问题类型 | Type of problem

模型推理和部署 | Model inference and deployment

### 操作系统 | Operating system

Linux

### 详细描述问题 | Detailed description of the problem

```
# 请在此处粘贴运行代码（如没有可删除该代码块）
# Paste the runtime code here (delete the code block if you don't have it)
```

### Dependencies

```
# 请在此处粘贴依赖情况
# Please paste the dependencies here
```

### 运行日志或截图 | Runtime logs or screenshots
请求：
curl  https://facerec-rtc1.lx-qa.com/llm_codellama_34b_instruct_4090/v1/chat/completions  \
-H "Content-Type: application/json" \
-H "Authorization: Bearer xxx" \
-d '{
"model": "code-llama",
"messages": [{"role": "user", "content": "write a login webpage with vue!"}]
}'

回复：（rgba的地方截断了）
```
{"id":"chatcmpl-abb2e08a2793160c8ee2db1a",
"object":"chat.completion","created":1693374690,"model":"code-llama",
"choices":[
{"index":0,"message":
{"role":"assistant","content":"Sure, here's an example of a basic login webpage using Vue.js:\n\nHTML:\n```\n<div id=\"app\">\n  <form @submit.prevent=\"login\">\n    <label for=\"username\">Username:</label>\n    <input type=\"text\" id=\"username\" v-model=\"username\" />\n    <br>\n    <label for=\"password\">Password:</label>\n    <input type=\"password\" id=\"password\" v-model=\"password\" />\n    <br>\n    <button type=\"submit\">Login</button>\n  </form>\n</div>\n```\nCSS:\n```\n#app {\n  font-family: Arial, sans-serif;\n  text-align: center;\n}\n\nform {\n  max-width: 400px;\n  margin: 0 auto;\n  padding: 20px;\n  background-color: #f7f7f7;\n  border: 1px solid #ccc;\n  box-shadow: 0 0 10px rgba(0, 0, 0, 0.",
"name":null,
"functions":null,
"function_call":null},
"finish_reason":"stop"}],
"usage":{"prompt_tokens":146,"total_tokens":401,"completion_tokens":255}}
```
 运行example/code-llama/instruction.py
<img width="1069" alt="截屏2023-08-30 15 00 25" src="https://github.com/xusenlinzy/api-for-open-llm/assets/13213426/7398a9ab-4ae8-4602-9ece-ef0000a24391">

**Comment by xusenlinzy** [comment]
是的，这里存在一个bug，最新的代码已经修复了，通过max_tokens传入max_new_tokens的值

**Comment by anyshu** [comment]
😊
